import type { WorkspaceDefinition } from "@/lib/platform/execution-engine/types";

const WORK_NAV = (base: string, items: { id: string; label: string; capabilityKey?: string }[]) =>
  items.map((item) => ({
    id: item.id,
    label: item.label,
    href: `${base}?work=${item.id}`,
    capabilityKey: item.capabilityKey,
  }));

/** Registered enterprise workspace definitions — Teacher is the reference implementation. */
export const WORKSPACE_DEFINITIONS: WorkspaceDefinition[] = [
  {
    workspaceKey: "teacher",
    title: "Teacher Workspace",
    description: "Work-centered instructional workspace — open work, not pages.",
    basePath: "/dashboard/teacher",
    status: "published",
    capabilityKeys: [
      "cap.teacher.session_delivery",
      "cap.teacher.progress_recording",
      "cap.paj.evidence_intake",
    ],
    managePermission: "teacher.manage",
    accessPermissions: ["teacher.view"],
    sortOrder: 10,
    navigation: WORK_NAV("/dashboard/teacher", [
      { id: "today", label: "Today's Work" },
      { id: "highest_priorities", label: "My Highest Priorities" },
      { id: "awaiting_review", label: "Awaiting My Review" },
      { id: "needs_human_decision", label: "Needs Human Decision" },
      { id: "ready_to_teach", label: "Ready To Teach", capabilityKey: "cap.teacher.session_delivery" },
      { id: "ready_for_family_communication", label: "Ready For Family Communication" },
      { id: "ready_for_completion", label: "Ready For Completion", capabilityKey: "cap.paj.evidence_intake" },
    ]),
  },
  {
    workspaceKey: "admissions",
    title: "Admissions & Enrollment",
    description: "Enrollment funnel — open work, not pages.",
    basePath: "/dashboard/admissions",
    status: "published",
    capabilityKeys: [
      "cap.admissions.case_review",
      "cap.admissions.enrollment_handoff",
      "cap.paj.evidence_intake",
    ],
    managePermission: "admissions.manage",
    accessPermissions: ["admissions.view", "admissions.accept"],
    sortOrder: 20,
    navigation: WORK_NAV("/dashboard/admissions", [
      { id: "today", label: "Today's Work" },
      { id: "highest_priorities", label: "Highest Priorities" },
      { id: "awaiting_review", label: "Awaiting My Review" },
      { id: "needs_human_decision", label: "Needs Human Decision" },
      { id: "documents_pending", label: "Documents Pending", capabilityKey: "cap.admissions.case_review" },
      { id: "ready_for_enrollment", label: "Ready For Enrollment", capabilityKey: "cap.admissions.enrollment_handoff" },
    ]),
  },
  {
    workspaceKey: "students",
    title: "Student Information",
    description: "Student Success (SSIS) — records, enrollment, and profiles.",
    basePath: "/dashboard/students",
    status: "published",
    capabilityKeys: [
      "cap.students.record_management",
      "cap.students.enrollment_management",
      "cap.paj.evidence_intake",
    ],
    managePermission: "students.edit",
    accessPermissions: ["students.view"],
    sortOrder: 25,
    navigation: WORK_NAV("/dashboard/students", [
      { id: "today", label: "Today's Work" },
      { id: "highest_priorities", label: "Highest Priorities" },
      { id: "awaiting_review", label: "Awaiting My Review" },
      { id: "needs_human_decision", label: "Needs Human Decision" },
      { id: "records_incomplete", label: "Records Incomplete", capabilityKey: "cap.students.record_management" },
      { id: "enrollment_pending", label: "Enrollment Pending", capabilityKey: "cap.students.enrollment_management" },
    ]),
  },
  {
    workspaceKey: "scheduling",
    title: "Scheduling Intelligence",
    description: "Authoritative scheduling engine — placement, conflicts, capacity, and coverage.",
    basePath: "/dashboard/scheduling",
    status: "published",
    capabilityKeys: [
      "cap.scheduling.intelligence",
      "cap.scheduling.placement",
      "cap.scheduling.conflict_resolution",
    ],
    managePermission: "scheduling.manage",
    accessPermissions: ["scheduling.view", "scheduling.executive"],
    sortOrder: 28,
    navigation: WORK_NAV("/dashboard/scheduling", [
      { id: "today", label: "Today's Work" },
      { id: "highest_priorities", label: "Highest Priorities" },
      { id: "awaiting_review", label: "Awaiting My Review" },
      { id: "needs_human_decision", label: "Needs Human Decision" },
      { id: "conflicts_due", label: "Conflicts Due", capabilityKey: "cap.scheduling.conflict_resolution" },
      { id: "placement_gaps", label: "Placement Gaps", capabilityKey: "cap.scheduling.placement" },
      { id: "coverage_needed", label: "Coverage Needed", capabilityKey: "cap.scheduling.conflict_resolution" },
      { id: "capacity_optimization", label: "Capacity Optimization", capabilityKey: "cap.scheduling.intelligence" },
    ]),
  },
  {
    workspaceKey: "finance",
    title: "Finance",
    description: "Billing, collections, and revenue operations.",
    basePath: "/dashboard/finance",
    status: "published",
    capabilityKeys: [
      "cap.finance.billing_operations",
      "cap.finance.executive_reporting",
    ],
    managePermission: "finance.override_tuition",
    accessPermissions: ["finance.view", "finance.billing"],
    sortOrder: 70,
    navigation: WORK_NAV("/dashboard/finance", [
      { id: "today", label: "Today's Work" },
      { id: "highest_priorities", label: "Highest Priorities" },
      { id: "awaiting_review", label: "Awaiting My Review" },
      { id: "needs_human_decision", label: "Needs Human Decision" },
      { id: "collections_due", label: "Collections Due", capabilityKey: "cap.finance.billing_operations" },
      { id: "ready_to_post", label: "Ready To Post", capabilityKey: "cap.finance.billing_operations" },
    ]),
  },
  {
    workspaceKey: "hr",
    title: "Human Resources",
    description: "Workforce, recruiting, compliance, and onboarding.",
    basePath: "/dashboard/hr",
    status: "published",
    capabilityKeys: [
      "cap.hr.workforce_operations",
      "cap.platform.workflow_execution",
    ],
    managePermission: "hr.manage",
    accessPermissions: ["hr.view", "hr.compliance", "hr.recruiting"],
    sortOrder: 60,
    navigation: WORK_NAV("/dashboard/hr", [
      { id: "today", label: "Today's Work" },
      { id: "highest_priorities", label: "Highest Priorities" },
      { id: "awaiting_review", label: "Awaiting My Review" },
      { id: "needs_human_decision", label: "Needs Human Decision" },
      { id: "compliance_due", label: "Compliance Due", capabilityKey: "cap.hr.workforce_operations" },
      { id: "ready_to_onboard", label: "Ready To Onboard", capabilityKey: "cap.hr.workforce_operations" },
    ]),
  },
  {
    workspaceKey: "executive",
    title: "Executive Intelligence",
    description: "Strategic oversight — decisions, risk, and board readiness.",
    basePath: "/dashboard/executive",
    status: "published",
    capabilityKeys: [
      "cap.executive.intelligence",
      "cap.platform.workflow_execution",
    ],
    managePermission: "executive.intelligence",
    accessPermissions: ["executive.dashboard", "executive.intelligence", "global.reporting"],
    sortOrder: 50,
    navigation: WORK_NAV("/dashboard/executive", [
      { id: "today", label: "Today's Work" },
      { id: "highest_priorities", label: "Highest Priorities" },
      { id: "awaiting_review", label: "Awaiting My Review" },
      { id: "needs_human_decision", label: "Needs Human Decision" },
      { id: "strategic_decisions", label: "Strategic Decisions", capabilityKey: "cap.executive.intelligence" },
      { id: "board_ready", label: "Board Ready", capabilityKey: "cap.executive.intelligence" },
    ]),
  },
  {
    workspaceKey: "parent",
    title: "Parent Portal",
    description: "Family and parent experience.",
    basePath: "/portal",
    status: "draft",
    capabilityKeys: [],
    sortOrder: 30,
    navigation: [],
  },
  {
    workspaceKey: "student",
    title: "Student Workspace",
    description: "Learner-facing workspace.",
    basePath: "/portal/student",
    status: "draft",
    capabilityKeys: [],
    sortOrder: 40,
    navigation: [],
  },
  {
    workspaceKey: "leadership",
    title: "Founder Workspace",
    description: "Organization leadership and oversight.",
    basePath: "/dashboard",
    status: "draft",
    capabilityKeys: ["cap.platform.workflow_execution"],
    sortOrder: 55,
    navigation: [],
  },
];
