import type { ModuleReleaseDefinition } from "./types";

/**
 * Module Completion Registry — source of truth for readiness claims.
 * New modules start as `building` / `planned` and advance only as gates pass.
 */
export const MODULE_RELEASE_REGISTRY: ModuleReleaseDefinition[] = [
  {
    id: "students",
    label: "Students",
    status: "production-ready",
    entityKeys: ["student"],
    requiredEvents: [
      "student.created",
      "student.updated",
      "student.archived",
      "student.restored",
      "student.deleted",
    ],
    docsPath: "docs/features/student-management.md",
    testPaths: ["tests/unit/students"],
    communicationsRelevant: true,
    extensionRelevant: false,
  },
  {
    id: "families",
    label: "Families",
    status: "production-ready",
    entityKeys: ["family"],
    requiredEvents: [
      "family.created",
      "family.updated",
      "family.archived",
      "family.restored",
      "family.deleted",
      "family.merged",
      "family.split",
    ],
    docsPath: "docs/features/family-management.md",
    testPaths: ["tests/unit/families"],
    communicationsRelevant: true,
    extensionRelevant: false,
  },
  {
    id: "communications",
    label: "Communications",
    status: "production-ready",
    entityKeys: ["communication", "announcement", "template", "notification"],
    requiredEvents: [
      "communication.created",
      "communication.sent",
      "communication.archived",
      "announcement.published",
      "template.created",
    ],
    docsPath: "docs/features/communications.md",
    testPaths: ["tests/unit/communications"],
    communicationsRelevant: true,
    extensionRelevant: true,
    notes: "Provider adapters deferred (Gmail/Twilio) via extension API.",
  },
  {
    id: "workflows",
    label: "Workflow Engine",
    status: "production-ready",
    entityKeys: ["workflow"],
    requiredEvents: [
      "workflow.created",
      "workflow.enabled",
      "workflow.disabled",
      "workflow.archived",
      "workflow.duplicated",
    ],
    docsPath: "docs/features/workflow-engine.md",
    testPaths: ["tests/unit/workflows"],
    communicationsRelevant: true,
    extensionRelevant: true,
  },
  {
    id: "calendar",
    label: "Calendar",
    status: "tested",
    entityKeys: ["calendar_event", "meeting", "resource"],
    requiredEvents: [
      "calendar.created",
      "calendar.updated",
      "calendar.cancelled",
      "meeting.scheduled",
      "class.scheduled",
    ],
    docsPath: "docs/features/calendar-platform.md",
    testPaths: ["tests/unit/calendar"],
    communicationsRelevant: true,
    extensionRelevant: true,
    notes: "Google Meet adapter stubbed; full resource UX still maturing.",
  },
  {
    id: "admissions",
    label: "Admissions",
    status: "building",
    entityKeys: ["admission"],
    requiredEvents: ["lead.created", "enrollment.accepted"],
    docsPath: "docs/features/admissions.md",
    testPaths: ["tests/unit/admissions", "tests/integration"],
    communicationsRelevant: true,
    extensionRelevant: false,
    notes: "CRUD lifecycle parity with Students still in progress.",
  },
  {
    id: "hr",
    label: "HR / Employees",
    status: "tested",
    entityKeys: ["employee", "teacher"],
    requiredEvents: [
      "employee.created",
      "employee.updated",
      "employee.deactivated",
      "employee.restored",
      "employee.hired",
      "employee.promoted",
      "employee.assigned",
      "employee.certification.expiring",
      "employee.review.completed",
      "employee.leave.approved",
      "employee.terminated",
      "employee.onboarding.completed",
      "employee.offer.extended",
    ],
    docsPath: "docs/features/human-capital-platform.md",
    testPaths: ["tests/unit/hr", "tests/unit/employees", "tests/unit/hr-platform"],
    communicationsRelevant: true,
    extensionRelevant: true,
    notes:
      "RC8 HCM platform — lifecycle, recruiting, onboarding, contracts, certs, performance, PD, time off; HRIS adapters deferred.",
  },
  {
    id: "billing",
    label: "Billing",
    status: "tested",
    entityKeys: ["invoice", "payment"],
    requiredEvents: [
      "finance.account.created",
      "invoice.created",
      "invoice.sent",
      "invoice.paid",
      "invoice.overdue",
      "payment.received",
      "payment.failed",
      "scholarship.applied",
      "discount.applied",
      "refund.created",
      "refund.completed",
    ],
    docsPath: "docs/features/finance-platform.md",
    testPaths: ["tests/unit/billing", "tests/unit/finance", "tests/unit/finance-platform"],
    communicationsRelevant: true,
    extensionRelevant: true,
    notes:
      "RC7 Finance platform — family accounts, tuition, invoices, payments, plans, aging, refunds; accounting adapters deferred.",
  },
  {
    id: "scholarships",
    label: "Scholarships",
    status: "building",
    entityKeys: ["scholarship"],
    requiredEvents: ["scholarship.awarded"],
    docsPath: "docs/features/scholarships.md",
    testPaths: ["tests/unit/scholarships"],
    communicationsRelevant: true,
    extensionRelevant: false,
  },
  {
    id: "scheduling",
    label: "Academic Operations",
    status: "building",
    entityKeys: ["class"],
    requiredEvents: ["class.scheduled"],
    docsPath: "docs/features/scheduling.md",
    testPaths: ["tests/unit/scheduling"],
    communicationsRelevant: false,
    extensionRelevant: true,
  },
  {
    id: "documents",
    label: "Documents",
    status: "tested",
    entityKeys: ["document"],
    requiredEvents: [
      "document.created",
      "document.updated",
      "document.versioned",
      "document.archived",
      "document.deleted",
      "document.restored",
      "document.uploaded",
      "template.used",
      "signature.requested",
    ],
    docsPath: "docs/features/document-management.md",
    testPaths: ["tests/unit/documents"],
    communicationsRelevant: false,
    extensionRelevant: true,
  },
  {
    id: "founder",
    label: "Founder Intelligence",
    status: "tested",
    entityKeys: ["founder_insight", "founder_decision"],
    requiredEvents: [
      "founder.insight.created",
      "founder.recommendation.created",
      "founder.decision.approved",
      "founder.decision.dismissed",
      "founder.decision.delegated",
      "founder.decision.scheduled",
      "founder.decision.resolved",
      "founder.brief.generated",
      "founder.health.scored",
    ],
    docsPath: "docs/features/founder-intelligence.md",
    testPaths: ["tests/unit/founder-intelligence"],
    communicationsRelevant: true,
    extensionRelevant: false,
    notes:
      "RC9 Founder Intelligence — consumes EI via JAG Intelligence Engine pipeline.",
  },
  {
    id: "jag",
    label: "JAG Intelligence Engine",
    status: "tested",
    entityKeys: ["jag_insight", "jag_knowledge_edge"],
    requiredEvents: [
      "jag.pipeline.completed",
      "jag.insight.created",
      "jag.insight.resolved",
      "jag.anomaly.detected",
      "jag.feedback.recorded",
      "jag.context.updated",
    ],
    docsPath: "docs/platform/jag-intelligence-engine.md",
    testPaths: ["tests/unit/jag-intelligence"],
    communicationsRelevant: true,
    extensionRelevant: true,
    notes:
      "RC10 JAG Intelligence Engine — pipeline, knowledge graph, context, confidence, providers, feedback.",
  },
  {
    id: "settings",
    label: "Settings",
    status: "planned",
    entityKeys: ["school", "program", "setting"],
    requiredEvents: [],
    docsPath: "docs/features/settings.md",
    testPaths: [],
    communicationsRelevant: false,
    extensionRelevant: false,
  },
];

export function getModuleDefinition(id: string): ModuleReleaseDefinition | undefined {
  return MODULE_RELEASE_REGISTRY.find((m) => m.id === id);
}

export function listModuleDefinitions(): ModuleReleaseDefinition[] {
  return MODULE_RELEASE_REGISTRY;
}
