import type { EventDefinition } from "@/lib/platform/events/types";

export const PAJ_EVENT_DEFINITIONS: EventDefinition[] = [
  {
    eventType: "learning.journey.created",
    name: "Learning Journey Created",
    description: "Personal Learning Journey initialized for a student",
    domain: "learning",
    version: 1,
    status: "active",
    dispatchMode: "both",
    scopes: ["internal"],
    entityTypes: ["learning_journey"],
    sortOrder: 100,
    tags: ["learning", "paj", "lifecycle"],
  },
  {
    eventType: "learning.placement.completed",
    name: "Learning Placement Completed",
    description: "Initial domain placement confirmed for a journey",
    domain: "learning",
    version: 1,
    status: "active",
    dispatchMode: "both",
    scopes: ["internal"],
    entityTypes: ["learning_journey", "placement"],
    sortOrder: 110,
    tags: ["learning", "paj", "placement"],
  },
  {
    eventType: "learning.competency.assigned",
    name: "Competency Assigned",
    description: "Active competency assigned on a domain enrollment",
    domain: "learning",
    version: 1,
    status: "active",
    dispatchMode: "sync",
    scopes: ["internal"],
    entityTypes: ["learning_journey", "competency"],
    sortOrder: 120,
    tags: ["learning", "paj", "competency"],
  },
  {
    eventType: "learning.mastery.updated",
    name: "Mastery Updated",
    description: "Competency or skill mastery level updated from evidence",
    domain: "learning",
    version: 1,
    status: "active",
    dispatchMode: "both",
    scopes: ["internal"],
    entityTypes: ["learning_journey", "competency", "skill"],
    sortOrder: 130,
    tags: ["learning", "paj", "mastery", "kee"],
  },
  {
    eventType: "learning.competency.advanced",
    name: "Competency Advanced",
    description: "Student advanced to next competency after L3 confirmation",
    domain: "learning",
    version: 1,
    status: "active",
    dispatchMode: "both",
    scopes: ["internal"],
    entityTypes: ["learning_journey", "competency"],
    sortOrder: 140,
    tags: ["learning", "paj", "progression"],
  },
];
