import type { AdmissionsEntityDefinition } from "@/lib/admissions/registry/types";

/** Core Admissions OS entity catalog (B-03 Phase 1). */
export const ADMISSIONS_ENTITIES: AdmissionsEntityDefinition[] = [
  {
    key: "inquiry",
    label: "Inquiry",
    pluralLabel: "Inquiries",
    table: "admissions_leads",
    moduleKey: "admissions",
    status: "live",
    description: "Initial family interest captured via portal or staff entry.",
  },
  {
    key: "prospective_family",
    label: "Prospective Family",
    pluralLabel: "Prospective Families",
    table: "admissions_lead_guardians",
    moduleKey: "admissions",
    status: "live",
    description: "Guardian and household context prior to SIS family creation.",
  },
  {
    key: "prospective_student",
    label: "Prospective Student",
    pluralLabel: "Prospective Students",
    table: "admissions_leads",
    moduleKey: "admissions",
    status: "live",
    description: "Student prospect record linked to inquiry and application.",
  },
  {
    key: "application",
    label: "Application",
    pluralLabel: "Applications",
    table: "admissions_applications",
    moduleKey: "admissions",
    status: "live",
    description: "Formal enrollment application with checklist and documents.",
  },
  {
    key: "evaluation",
    label: "Evaluation",
    pluralLabel: "Evaluations",
    table: "admissions_decisions",
    moduleKey: "admissions",
    status: "partial",
    description: "Committee review outcomes including request-for-info decisions.",
  },
  {
    key: "interview",
    label: "Interview",
    pluralLabel: "Interviews",
    table: "admissions_interviews",
    moduleKey: "admissions",
    status: "live",
    description: "Scheduled family or student interviews.",
  },
  {
    key: "tour",
    label: "Tour",
    pluralLabel: "Tours",
    table: "admissions_tours",
    moduleKey: "admissions",
    status: "live",
    description: "Campus tour scheduling and completion.",
  },
  {
    key: "assessment",
    label: "Assessment",
    pluralLabel: "Assessments",
    table: null,
    moduleKey: "admissions",
    status: "planned",
    description: "Admissions assessments — entity table planned for Phase 2.",
  },
  {
    key: "decision",
    label: "Decision",
    pluralLabel: "Decisions",
    table: "admissions_decisions",
    moduleKey: "admissions",
    status: "live",
    description: "Accept, waitlist, deny, or request-info decisions.",
  },
  {
    key: "enrollment",
    label: "Enrollment",
    pluralLabel: "Enrollments",
    table: "enrollment_packets",
    moduleKey: "admissions",
    status: "live",
    description: "Enrollment packet generation, signatures, and SIS conversion.",
  },
  {
    key: "waitlist",
    label: "Waitlist",
    pluralLabel: "Waitlist",
    table: "admissions_leads",
    moduleKey: "admissions",
    status: "live",
    description: "Waitlisted prospects tracked via pipeline stage.",
  },
];
