/**
 * Governance profiles — configuration only; one codebase for all structures.
 */

import type { GovernanceProfile, GovernanceProfileId } from "../types";
import { GOVERNANCE_PROFILE_IDS } from "../types";

function profile(
  partial: GovernanceProfile
): GovernanceProfile {
  return Object.freeze(partial);
}

const CATALOG: Record<GovernanceProfileId, GovernanceProfile> = {
  sole_proprietorship: profile({
    id: "sole_proprietorship",
    title: "Sole Proprietorship",
    description: "Single-owner operating entity with direct authority.",
    defaultGovernanceModel: "owner-operator",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "goals_only",
    typicalCompliance: Object.freeze(["local_business_license", "tax_filing"]),
    typicalDecisionRules: Object.freeze([
      "Owner has final authority on spending and hiring",
    ]),
    allowsBoard: false,
    allowsEquity: false,
    publicReporting: false,
  }),
  single_member_llc: profile({
    id: "single_member_llc",
    title: "Single-member LLC",
    description: "Limited liability company with one member.",
    defaultGovernanceModel: "member-managed",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "goals_only",
    typicalCompliance: Object.freeze(["state_llc_filing", "operating_agreement"]),
    typicalDecisionRules: Object.freeze(["Sole member approves material commitments"]),
    allowsBoard: false,
    allowsEquity: true,
    publicReporting: false,
  }),
  multi_member_llc: profile({
    id: "multi_member_llc",
    title: "Multi-member LLC",
    description: "LLC with multiple members and operating agreement.",
    defaultGovernanceModel: "operating-agreement",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["operating_agreement", "member_votes"]),
    typicalDecisionRules: Object.freeze([
      "Material decisions require member vote per operating agreement",
    ]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  partnership: profile({
    id: "partnership",
    title: "Partnership",
    description: "General partnership with shared liability and authority.",
    defaultGovernanceModel: "partnership-agreement",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["partnership_agreement", "tax_k1"]),
    typicalDecisionRules: Object.freeze(["Partners approve major commitments jointly"]),
    allowsBoard: false,
    allowsEquity: true,
    publicReporting: false,
  }),
  llp: profile({
    id: "llp",
    title: "LLP",
    description: "Limited liability partnership.",
    defaultGovernanceModel: "llp-agreement",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["llp_registration", "professional_rules"]),
    typicalDecisionRules: Object.freeze(["Designated partners approve spending above threshold"]),
    allowsBoard: false,
    allowsEquity: true,
    publicReporting: false,
  }),
  s_corp: profile({
    id: "s_corp",
    title: "S-Corp",
    description: "S corporation with shareholder constraints.",
    defaultGovernanceModel: "board-shareholder",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["s_election", "shareholder_limits", "payroll"]),
    typicalDecisionRules: Object.freeze(["Board approves budgets; officers execute within thresholds"]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  c_corp: profile({
    id: "c_corp",
    title: "C-Corp",
    description: "C corporation suitable for broad equity and boards.",
    defaultGovernanceModel: "board-centric",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["corporate_minutes", "equity_plans", "tax_filings"]),
    typicalDecisionRules: Object.freeze([
      "Board approves strategy; officers execute under delegation matrix",
    ]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  holding_company: profile({
    id: "holding_company",
    title: "Holding Company",
    description: "Parent entity governing subsidiaries and capital allocation.",
    defaultGovernanceModel: "holding-board",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["intercompany_policies", "subsidiary_governance"]),
    typicalDecisionRules: Object.freeze([
      "Subsidiary commitments above threshold require holding approval",
    ]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  family_office: profile({
    id: "family_office",
    title: "Family Office",
    description: "Family capital and governance vehicle.",
    defaultGovernanceModel: "family-council",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["investment_policy", "related_party_rules"]),
    typicalDecisionRules: Object.freeze(["Family council approves strategic capital moves"]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  esop: profile({
    id: "esop",
    title: "ESOP",
    description: "Employee stock ownership company.",
    defaultGovernanceModel: "esop-trustee-board",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["erisa", "esop_valuation", "fiduciary_duties"]),
    typicalDecisionRules: Object.freeze(["Trustee and board jointly oversee major transactions"]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  venture_backed_startup: profile({
    id: "venture_backed_startup",
    title: "Venture-backed Startup",
    description: "High-growth company with investor governance.",
    defaultGovernanceModel: "investor-board",
    defaultRiskTolerance: "aggressive",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["investor_rights", "cap_table", "preferred_stock"]),
    typicalDecisionRules: Object.freeze([
      "Protective provisions require investor consent for major actions",
    ]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  private_company: profile({
    id: "private_company",
    title: "Private Company",
    description: "Privately held operating company.",
    defaultGovernanceModel: "private-board",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["corporate_records", "tax_filings"]),
    typicalDecisionRules: Object.freeze(["Board or owners approve annual budget"]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  public_company: profile({
    id: "public_company",
    title: "Public Company",
    description: "Publicly traded company with disclosure duties.",
    defaultGovernanceModel: "public-board-committees",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["sec_reporting", "sox", "insider_trading_policy"]),
    typicalDecisionRules: Object.freeze([
      "Audit and compensation committees oversee key domains; board approves strategy",
    ]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: true,
  }),
  franchise: profile({
    id: "franchise",
    title: "Franchise",
    description: "Franchisee operating under franchisor system.",
    defaultGovernanceModel: "franchise-agreement",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "goals_only",
    typicalCompliance: Object.freeze(["franchise_agreement", "brand_standards"]),
    typicalDecisionRules: Object.freeze([
      "Local ops decisions within brand standards; system changes require franchisor",
    ]),
    allowsBoard: false,
    allowsEquity: true,
    publicReporting: false,
  }),
  cooperative: profile({
    id: "cooperative",
    title: "Cooperative",
    description: "Member-owned cooperative.",
    defaultGovernanceModel: "member-democratic",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["cooperative_bylaws", "member_voting"]),
    typicalDecisionRules: Object.freeze(["Members elect board; board sets policy"]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  nonprofit: profile({
    id: "nonprofit",
    title: "Nonprofit",
    description: "Mission-driven nonprofit organization.",
    defaultGovernanceModel: "nonprofit-board",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["501c", "form_990", "conflict_of_interest"]),
    typicalDecisionRules: Object.freeze([
      "Board approves mission-critical strategy and major gifts/spending",
    ]),
    allowsBoard: true,
    allowsEquity: false,
    publicReporting: false,
  }),
  foundation: profile({
    id: "foundation",
    title: "Foundation",
    description: "Grantmaking or operating foundation.",
    defaultGovernanceModel: "foundation-board",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["private_foundation_rules", "payout_requirements"]),
    typicalDecisionRules: Object.freeze(["Board approves grant strategy and large awards"]),
    allowsBoard: true,
    allowsEquity: false,
    publicReporting: false,
  }),
  association: profile({
    id: "association",
    title: "Association",
    description: "Membership association or trade group.",
    defaultGovernanceModel: "association-board",
    defaultRiskTolerance: "moderate",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["bylaws", "membership_rules"]),
    typicalDecisionRules: Object.freeze(["Board and membership vote per bylaws"]),
    allowsBoard: true,
    allowsEquity: false,
    publicReporting: false,
  }),
  university: profile({
    id: "university",
    title: "University",
    description: "Higher-education institution.",
    defaultGovernanceModel: "university-board-senate",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["accreditation", "title_iv", "research_compliance"]),
    typicalDecisionRules: Object.freeze([
      "Board sets institutional strategy; academic governance for curriculum",
    ]),
    allowsBoard: true,
    allowsEquity: false,
    publicReporting: false,
  }),
  school_system: profile({
    id: "school_system",
    title: "School System",
    description: "K-12 school system or network.",
    defaultGovernanceModel: "school-board",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["education_regs", "student_privacy", "procurement"]),
    typicalDecisionRules: Object.freeze([
      "Board approves budget and policy; superintendent executes operations",
    ]),
    allowsBoard: true,
    allowsEquity: false,
    publicReporting: false,
  }),
  hospital: profile({
    id: "hospital",
    title: "Hospital",
    description: "Hospital operating entity.",
    defaultGovernanceModel: "hospital-board-medical-staff",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["hipaa", "cms", "joint_commission"]),
    typicalDecisionRules: Object.freeze([
      "Board oversees quality and finance; medical staff governs clinical practice",
    ]),
    allowsBoard: true,
    allowsEquity: false,
    publicReporting: false,
  }),
  healthcare_network: profile({
    id: "healthcare_network",
    title: "Healthcare Network",
    description: "Multi-facility healthcare system.",
    defaultGovernanceModel: "system-board",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["hipaa", "system_quality", "payer_contracts"]),
    typicalDecisionRules: Object.freeze([
      "System board approves capital and network strategy",
    ]),
    allowsBoard: true,
    allowsEquity: true,
    publicReporting: false,
  }),
  government_agency: profile({
    id: "government_agency",
    title: "Government Agency",
    description: "Public agency under statutory authority.",
    defaultGovernanceModel: "statutory-agency",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["foia", "procurement_law", "ethics"]),
    typicalDecisionRules: Object.freeze([
      "Authority limited to statute; major spending follows public procurement",
    ]),
    allowsBoard: false,
    allowsEquity: false,
    publicReporting: true,
  }),
  municipality: profile({
    id: "municipality",
    title: "Municipality",
    description: "City/town government.",
    defaultGovernanceModel: "council-manager-or-mayor",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["open_meetings", "public_budget", "procurement"]),
    typicalDecisionRules: Object.freeze(["Council approves ordinances and budget"]),
    allowsBoard: true,
    allowsEquity: false,
    publicReporting: true,
  }),
  tribal_government: profile({
    id: "tribal_government",
    title: "Tribal Government",
    description: "Tribal nation governing body.",
    defaultGovernanceModel: "tribal-council",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_driven",
    typicalCompliance: Object.freeze(["tribal_law", "sovereign_protocols", "federal_compacts"]),
    typicalDecisionRules: Object.freeze(["Council or designated officers approve per tribal code"]),
    allowsBoard: true,
    allowsEquity: false,
    publicReporting: false,
  }),
  religious_organization: profile({
    id: "religious_organization",
    title: "Religious Organization",
    description: "Faith-based organization with ecclesiastical governance.",
    defaultGovernanceModel: "faith-governance",
    defaultRiskTolerance: "conservative",
    defaultStrategyMode: "strategy_assisted",
    typicalCompliance: Object.freeze(["nonprofit_or_church_rules", "safeguarding"]),
    typicalDecisionRules: Object.freeze([
      "Governing body or polity approves mission and major commitments",
    ]),
    allowsBoard: true,
    allowsEquity: false,
    publicReporting: false,
  }),
};

export function listGovernanceProfiles(): readonly GovernanceProfile[] {
  return Object.freeze(GOVERNANCE_PROFILE_IDS.map((id) => CATALOG[id]));
}

export function getGovernanceProfile(
  id: string
): GovernanceProfile | null {
  if ((GOVERNANCE_PROFILE_IDS as readonly string[]).includes(id)) {
    return CATALOG[id as GovernanceProfileId];
  }
  return null;
}

export function normalizeGovernanceProfileId(
  input?: string | null
): GovernanceProfileId {
  if (input && getGovernanceProfile(input)) {
    return input as GovernanceProfileId;
  }
  return "private_company";
}
