-- ============================================================================
-- 509 — A QUEUED LETTER IS CLAIMED BEFORE IT IS SENT
-- 5 October 2026
--
-- Lisa Roy received the same letter three times on 5 October. Resend's own log
-- and admissions_communications agree on all three. The cause is in
-- processCommunicationQueue:
--
--     read   status = 'pending' and scheduled_for <= now, limit 50
--     send   each one
--     mark   status = 'sent'
--
-- Between the read and the mark the row is STILL 'pending'. Any overlapping
-- run reads the same row and sends the same letter again. The cron is
-- */5 * * * *, so overlap needs only one slow batch.
--
-- A row cannot be claimed while there is no state meaning "being sent right
-- now", and migration 068 pinned the column to four values:
--
--     check (status in ('pending', 'sent', 'cancelled', 'failed'))
--
-- This file adds the fifth, and a column to say when the claim was taken.
--
-- THE CONSTRAINT IS DROPPED BY LOOKUP, NOT BY NAME. 068 declared it inline on
-- the column, so its name was generated by Postgres and guessing it is how a
-- migration becomes a no-op that reports success. Same approach migration 497
-- took with lead_call_outcomes.
--
-- WHY claimed_at AND NOT updated_at. updated_at already exists and moves for
-- any write. A claim needs a timestamp that means one thing, because the only
-- consumer is "has this claim gone stale", and a reader should not have to
-- know which writes touch updated_at to answer that.
--
-- NOTHING IN THIS FILE CHANGES BEHAVIOUR. It widens a constraint and adds a
-- nullable column. The claim itself is in the code change that travels with
-- it; until that deploys, no row is ever written as 'sending'.
-- ============================================================================


-- ── 1. Before ───────────────────────────────────────────────────────────────

select 'BEFORE'                       as stage,
       con.conname                    as constraint_name,
       pg_get_constraintdef(con.oid)  as definition
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace nsp on nsp.oid = rel.relnamespace
 where nsp.nspname = 'public'
   and rel.relname = 'admissions_communication_queue'
   and con.contype = 'c'
   and pg_get_constraintdef(con.oid) ilike '%pending%';


-- ── 2. The fifth status ─────────────────────────────────────────────────────

do $$
declare
  v_name text;
begin
  select con.conname into v_name
    from pg_constraint con
    join pg_class rel on rel.oid = con.conrelid
    join pg_namespace nsp on nsp.oid = rel.relnamespace
   where nsp.nspname = 'public'
     and rel.relname = 'admissions_communication_queue'
     and con.contype = 'c'
     and pg_get_constraintdef(con.oid) ilike '%pending%'
   limit 1;

  if v_name is null then
    raise exception 'No status check constraint found on admissions_communication_queue - stopping rather than guessing.';
  end if;

  execute format(
    'alter table public.admissions_communication_queue drop constraint %I',
    v_name
  );
end $$;

alter table public.admissions_communication_queue
  add constraint admissions_communication_queue_status_check
  check (status in ('pending', 'sending', 'sent', 'cancelled', 'failed'));


-- ── 3. When the claim was taken ─────────────────────────────────────────────

alter table public.admissions_communication_queue
  add column if not exists claimed_at timestamptz;

comment on column public.admissions_communication_queue.claimed_at is
  'Set when a run claims this row (status sending). Cleared on sent or failed. A claim older than the release window belonged to a run that died - the route is capped at maxDuration = 60, so no live run can hold one longer than a minute.';


-- ── 4. No row should be sitting in the new state yet ────────────────────────

do $$
declare
  v_sending integer;
begin
  select count(*) into v_sending
    from public.admissions_communication_queue
   where status = 'sending';

  if v_sending <> 0 then
    raise exception
      '% row(s) already read as sending, before any code can write it - investigate.',
      v_sending;
  end if;
end $$;


-- ── 5. After ────────────────────────────────────────────────────────────────
--
-- WHAT GOOD LOOKS LIKE: the definition lists five statuses including
-- 'sending', and claimed_at reads timestamp with time zone, is_nullable YES.

select 'AFTER'                        as stage,
       con.conname                    as constraint_name,
       pg_get_constraintdef(con.oid)  as definition
  from pg_constraint con
  join pg_class rel on rel.oid = con.conrelid
  join pg_namespace nsp on nsp.oid = rel.relnamespace
 where nsp.nspname = 'public'
   and rel.relname = 'admissions_communication_queue'
   and con.contype = 'c'
   and pg_get_constraintdef(con.oid) ilike '%pending%'

union all

select 'AFTER',
       'column: ' || column_name,
       data_type || ', nullable ' || is_nullable
  from information_schema.columns
 where table_schema = 'public'
   and table_name = 'admissions_communication_queue'
   and column_name = 'claimed_at';
