/**
 * JAG Intelligence — Phase 1 foundation public API.
 *
 * Shared cognitive services for the autonomous intelligence layer.
 * See `docs/architecture/JAG_INTELLIGENCE_ARCHITECTURE.md`.
 *
 * Phase B / H-A11: Prefer subpath imports (`intelligence/wisdom`, `intelligence/registration`,
 * `intelligence/create-service`, domain packages). This mega-barrel remains for compatibility
 * but app/platform code should not add new deep dependencies through it.
 */

export * from "@/lib/platform/intelligence/types";
export * from "@/lib/platform/intelligence/context";
export * from "@/lib/platform/intelligence/context/builder";
export * from "@/lib/platform/intelligence/context/cache";
export * from "@/lib/platform/intelligence/context/executive-context";
export * from "@/lib/platform/intelligence/context/finance-context";
export * from "@/lib/platform/intelligence/context/student-context";
export * from "@/lib/platform/intelligence/context/organization-context";
export * from "@/lib/platform/intelligence/memory";
export * from "@/lib/platform/intelligence/memory/index";
export * from "@/lib/platform/intelligence/reasoning";
export * from "@/lib/platform/intelligence/planner";
export * from "@/lib/platform/intelligence/execution";
export * from "@/lib/platform/intelligence/knowledge/foundation";
export * from "@/lib/platform/intelligence/confidence";
export * from "@/lib/platform/intelligence/learning";
export * from "@/lib/platform/intelligence/case-engine";
export * from "@/lib/platform/intelligence/events";
export * from "@/lib/platform/intelligence/explain";
export * from "@/lib/platform/intelligence/orchestrator";
export * from "@/lib/platform/intelligence/contracts";
export * from "@/lib/platform/intelligence/registry";
export * from "@/lib/platform/intelligence/router";
export * from "@/lib/platform/intelligence/service";
export * from "@/lib/platform/intelligence/create-service";
export * from "@/lib/platform/intelligence/domains/support";
export * from "@/lib/platform/intelligence/domains/executive";
export * from "@/lib/platform/intelligence/domains/strategic";
export * from "@/lib/platform/intelligence/decision";
export * from "@/lib/platform/intelligence/organization";
export {
  EXECUTIVE_GRAPH_ANALYZER_VERSION,
  createExecutiveGraphAnalyzer,
  GraphAnalyzer,
  GraphBuilder,
  GraphRepository,
  RootCauseAnalyzer,
  DependencyAnalyzer,
  CascadeAnalyzer,
  RiskPropagation,
  ExecutiveReasoner,
  OpportunityEngine,
  ConstraintEngine,
  CriticalityScore,
  ExecutivePriority as ExecutiveGraphPriorityRanker,
  ConfidenceScore as ExecutiveGraphConfidenceScorer,
  ExecutiveQueries,
  GraphSearch,
  DashboardProjection as ExecutiveGraphDashboardProjector,
} from "@/lib/platform/intelligence/executive-graph";
export type {
  CreateExecutiveGraphAnalyzerOptions,
  ExecutiveGraphAnalyzerStack,
  Graph as ExecutiveReasoningGraph,
  GraphNode as ExecutiveReasoningGraphNode,
  GraphEdge as ExecutiveReasoningGraphEdge,
  GraphAnalysisResult,
  GraphBuildInput,
} from "@/lib/platform/intelligence/executive-graph";
export {
  EXECUTIVE_DECISION_INTELLIGENCE_VERSION,
  createExecutiveDecisionIntelligence,
  createPresetScenario,
  DecisionEngine,
  ExecutiveDecisionService,
  ScenarioSimulator,
  RecommendationEngine,
  StrategyEngine,
  TradeoffAnalyzer,
  ImpactForecast,
  DecisionConfidence,
  DecisionHistory,
  ScenarioRepository,
  DecisionQueries,
  DecisionScoring,
  DecisionProjection,
  decisionModels,
} from "@/lib/platform/intelligence/executive-decision";
export type {
  CreateExecutiveDecisionOptions,
  ExecutiveDecisionStack,
  ExecutiveDecisionRequest,
  ExecutiveDecisionResult,
  ExecutiveDecisionRecommendation,
  DecisionScenarioDefinition,
  ScenarioSimulationResult,
  DecisionProjectionResult,
} from "@/lib/platform/intelligence/executive-decision";
export {
  PREDICTIVE_INTELLIGENCE_VERSION,
  createPredictiveIntelligence,
  createForecastScenario,
  PredictionEngine,
  PredictionService,
  ForecastEngine,
  TrendAnalyzer,
  ForecastRepository,
  ForecastQueries,
  ForecastProjection,
  PredictionConfidence,
  ForecastScoring,
  ForecastHistory,
  predictionModels,
} from "@/lib/platform/intelligence/predictive-intelligence";
export type {
  CreatePredictiveIntelligenceOptions,
  PredictiveIntelligenceStack,
  PredictionRequest,
  PredictionResult,
  ForecastScenarioDefinition,
  ForecastProjectionResult,
  ScenarioForecast,
  DomainForecast,
} from "@/lib/platform/intelligence/predictive-intelligence";
export {
  BOARD_GOVERNANCE_INTELLIGENCE_VERSION,
  createBoardGovernanceIntelligence,
  BoardIntelligenceEngine,
  GovernanceService,
  GovernanceEngine,
  BoardPacketGenerator,
  ExecutiveBriefGenerator,
  CommitteeReporting,
  StrategicInitiativeTracker,
  GovernanceDashboard,
  BoardKPIDashboard,
  RiskRegister,
  ComplianceMonitor,
  ExecutiveScorecards,
  ResolutionTracker,
  GovernanceCalendar,
  BoardQueries,
  GovernanceProjection,
  GovernanceRepository,
  governanceModels,
} from "@/lib/platform/intelligence/board-governance";
export type {
  CreateBoardGovernanceOptions,
  BoardGovernanceStack,
  GovernanceRequest,
  GovernanceResult,
  BoardPacket,
  BoardPacketKind,
  ExecutiveBrief,
  GovernanceDashboardView,
  BoardKpiDashboardView,
} from "@/lib/platform/intelligence/board-governance";
export {
  ORGANIZATION_DNA_VERSION,
  createOrganizationDnaIntelligence,
  OrganizationDnaEngine,
  OrganizationService,
  CompanyBuilder,
  OrganizationStageDetector,
  OrganizationLifecycle,
  BusinessModelEngine,
  BusinessPlanBuilder,
  LeanCanvasGenerator,
  SwotGenerator,
  ValuePropositionBuilder,
  CustomerPersonaBuilder,
  RevenueModelBuilder,
  FundingModelBuilder,
  GoToMarketPlanner,
  CompanyReadinessAssessmentEngine,
  ReadinessScoringEngine,
  ExecutiveRoadmapBuilder,
  OrganizationBlueprintBuilder,
  OrganizationDnaComposer,
  organizationDnaModels,
} from "@/lib/platform/intelligence/organization-dna";
export type {
  CreateOrganizationDnaOptions,
  OrganizationDnaStack,
  OrganizationDnaRequest,
  OrganizationDnaResult,
  OrganizationDNA,
  OrganizationProfile,
  CompanyBuilderSeed,
  OrganizationStage,
  CompanyBuilderArtifactKind,
} from "@/lib/platform/intelligence/organization-dna";
export {
  OIOS_VERSION,
  OIOS_INTELLIGENCE_DOMAINS,
  createOiosOperatingSystem,
  OrganizationOperatingSystem,
  OiosEngine,
  OiosService,
  IntelligenceDomainRegistry as OiosIntelligenceDomainRegistry,
  OrganizationalDigitalTwin,
  OrganizationalLifecycle,
  OrganizationalStateEngine,
  OrganizationalContext,
  OrganizationalMemory,
  OrganizationalKnowledgeGraph,
  OrganizationCapabilitiesRegistry,
  OrganizationImprovementEngine,
  ContinuousImprovementLoop,
  OrganizationalHealthIndex,
  OrganizationMaturityModel,
  OrganizationScorecard,
  OrganizationBenchmarking,
  OrganizationObjectives,
  OrganizationStrategy,
  OrganizationExecutionModel,
  OrganizationOperatingModel,
  OrganizationConfiguration,
  OrganizationPolicies,
  OrganizationStandards,
  OrganizationGovernanceModel,
  oiosModels,
} from "@/lib/platform/oios";
export type {
  CreateOiosOptions,
  OiosStack,
  OiosRequest,
  OiosResult,
  OiosIntelligenceDomain,
  DigitalTwinSnapshot,
  OrganizationalState,
  HealthIndex as OiosHealthIndex,
  MaturityAssessment,
  ImprovementCycle,
} from "@/lib/platform/oios";
export {
  HUMAN_CAPITAL_INTELLIGENCE_VERSION,
  createHumanCapitalIntelligence,
  HumanCapitalEngine,
  HumanCapitalService,
  WorkforceIntelligence,
  WorkforceRepository,
  HumanCapitalDashboard,
  CandidatePipeline,
  CandidateScoring,
  ResumeIntelligence,
  InterviewIntelligence,
  ReferenceIntelligence,
  HiringRecommendations,
  HiringRecommendationEngine,
  OfferOptimization,
  TalentSourcing,
  EmployerBrandingInsights,
  RecruitingAnalytics,
  EmployeeProfileEngine,
  SkillsInventory,
  CompetencyFramework,
  PerformanceEngine,
  GoalManagement,
  FeedbackEngine,
  CoachingEngine,
  RecognitionEngine,
  BehaviorInsights,
  ProductivityInsights,
  LeadershipAssessment,
  LeadershipDevelopment,
  SuccessionPlanning,
  TalentMatrix,
  OrganizationalDesign,
  ManagerEffectiveness,
  HighPotentialIdentification,
  LeadershipBenchStrength,
  BurnoutDetection,
  RetentionPrediction,
  EngagementAnalysis,
  StayInterviewInsights,
  ExitAnalysis,
  EmployeeSentiment,
  CultureHealth,
  LearningPlans,
  CareerPathing,
  CertificationTracking,
  MentorshipMatching,
  TrainingRecommendations,
  KnowledgeTransfer,
  DevelopmentRecommendations,
  SalaryBenchmarking,
  CompensationAnalysis,
  PayEquityAnalysis,
  BonusModeling,
  BenefitsAnalysis,
  IncentiveModeling,
  WorkforceForecast,
  CapacityPlanning,
  HiringForecast,
  OrganizationalScenarioPlanning,
  SkillsGapAnalysis,
  FutureWorkforceModel,
  HumanCapitalProjection,
  HumanCapitalQueries,
  ExecutiveWorkforceBriefGenerator,
  CareerPlanComposer,
  BurnoutRiskDashboard,
  OrganizationalCapabilityIndex,
  workforceModels,
} from "@/lib/platform/intelligence/human-capital";
export type {
  CreateHumanCapitalOptions,
  HumanCapitalStack,
  HumanCapitalRequest,
  HumanCapitalResult,
  HumanCapitalQueryRequest,
  HumanCapitalQueryResult,
  ExecutiveWorkforceBrief,
  HiringPriorityDashboard,
  SuccessionReadinessSummary,
  CareerDevelopmentPlan,
  HumanCapitalDashboardResult,
  BurnoutRiskDashboardResult,
  OrganizationalCapabilityIndexResult,
} from "@/lib/platform/intelligence/human-capital";
export {
  REVENUE_INTELLIGENCE_VERSION,
  createRevenueIntelligence,
  RevenueIntelligenceEngine,
  RevenueIntelligenceService,
  RevenueEngine,
  RevenueService,
  RevenueIntelligence,
  RevenueRepository,
  RevenueDashboard,
  RevenueHealth,
  RevenueStrategyEngine,
  RevenueMixAnalysis,
  RevenueDiversification,
  RecurringRevenueAnalysis,
  RevenueRiskAnalysis,
  RevenueOptimization,
  RevenueGrowthPlanner,
  RevenueForecasting,
  RevenueScenarioPlanning,
  PricingEngine,
  DynamicPricing,
  PriceElasticity,
  CompetitivePricing,
  DiscountOptimization,
  ScholarshipPricing,
  ContractPricing,
  SubscriptionPricing,
  OfferingAnalysis,
  ProductProfitability,
  ServiceProfitability,
  MarginAnalysis,
  LifecycleAnalysis,
  ExpansionRecommendations,
  RetirementRecommendations,
  CustomerLifetimeValue,
  RetentionRevenue,
  ExpansionRevenue,
  CrossSellEngine,
  UpsellEngine,
  CustomerProfitability,
  SegmentProfitability,
  PipelineForecast,
  WinRateAnalysis,
  SalesPerformance,
  SalesCapacity,
  TerritoryOptimization,
  ConversionAnalysis,
  MarketExpansion,
  CompetitorRevenue,
  DemandForecast,
  OpportunityScoring,
  GeographicExpansion,
  IndustryBenchmarks,
  GrossMarginAnalysis,
  NetMarginAnalysis,
  ContributionMargin,
  BreakEvenAnalysis,
  UnitEconomics,
  CashGenerationAnalysis,
  RevenueSensitivity,
  PricingDashboard,
  MarginDashboard,
  CustomerValueDashboard,
  ExecutiveRevenueBriefGenerator,
  RevenueProjection,
  RevenueQueries,
  revenueModels,
} from "@/lib/platform/intelligence/revenue";
export type {
  CreateRevenueOptions,
  RevenueStack,
  RevenueRequest,
  RevenueResult,
  RevenueQueryRequest,
  RevenueQueryResult,
  ExecutiveRevenueBrief,
  RevenueDashboardResult,
  PricingDashboardResult,
  MarginDashboardResult,
  CustomerValueDashboardResult,
  RevenueHealthResult,
} from "@/lib/platform/intelligence/revenue";
export {
  FUNDING_INTELLIGENCE_VERSION,
  createFundingIntelligence,
  FundingIntelligenceEngine,
  FundingIntelligenceService,
  FundingEngine,
  FundingService,
  FundingIntelligence,
  FundingRepository,
  FundingDashboard,
  FundingHealth,
  FundingStrategyEngine,
  FundingMixOptimization,
  FundingDiversification,
  FundingRiskAnalysis,
  FundingScenarioPlanning,
  CashRunwayOptimization,
  CapitalPlanning,
  FederalFunding,
  StateFunding,
  CountyFunding,
  CityFunding,
  EducationFunding,
  HealthcareFunding,
  InfrastructureFunding,
  EconomicDevelopmentFunding,
  DisasterFunding,
  ResearchFunding,
  GrantDiscovery,
  GrantMatching,
  GrantScoring,
  GrantCalendar,
  GrantForecasting,
  GrantRequirements,
  GrantCompliance,
  GrantReporting,
  GrantRenewals,
  GrantIntelligencePipeline,
  GovernmentContracts,
  CorporateContracts,
  RFPDiscovery,
  BidScoring,
  ProposalOptimization,
  ContractForecast,
  FoundationMatching,
  MajorDonorInsights,
  CorporateGiving,
  FamilyFoundations,
  CommunityFoundations,
  CapitalCampaignPlanning,
  AngelInvestors,
  VentureCapital,
  PrivateEquity,
  StrategicInvestors,
  DebtFinancing,
  RevenueBasedFinancing,
  Crowdfunding,
  Sponsorships,
  TaxCredits,
  TaxIncentives,
  OpportunityZones,
  NewMarketsTaxCredits,
  CarbonCredits,
  LicensingRevenue,
  RoyaltyRevenue,
  GrantPipelineDashboard,
  CapitalStrategyDashboard,
  FundingDiversificationDashboard,
  FundingRiskDashboard,
  FundingCalendarComposer,
  ExecutiveFundingBriefGenerator,
  FundingProjection,
  FundingQueries,
  fundingModels,
} from "@/lib/platform/intelligence/funding";
export type {
  CreateFundingOptions,
  FundingStack,
  FundingRequest,
  FundingResult,
  FundingQueryRequest,
  FundingQueryResult,
  ExecutiveFundingBrief,
  FundingDashboardResult,
  GrantPipelineDashboardResult,
  CapitalStrategyDashboardResult,
  FundingDiversificationDashboardResult,
  FundingRiskDashboardResult,
  FundingHealthResult,
} from "@/lib/platform/intelligence/funding";
export {
  OPPORTUNITY_INTELLIGENCE_VERSION,
  createOpportunityIntelligence,
  OpportunityIntelligenceEngine,
  OpportunityIntelligenceService,
  OpportunityService,
  OpportunityIntelligence,
  OpportunityRepository,
  OpportunityDashboard,
  OpportunityHealth,
  OpportunityModels,
  OpportunityCategoryEngine,
  OpportunityAnalysisEngine,
  OpportunityRankingEngine,
  OpportunityExchange,
  OpportunityRegistry,
  OpportunityScoring as OpportunityAnalysisScoring,
  ROIAnalysis,
  ImpactAnalysis,
  RiskAnalysis,
  ConfidenceScoring,
  DependencyAnalysis,
  ResourceRequirements,
  TimeToValueAnalysis,
  StrategicAlignment,
  RevenueOpportunities,
  FundingOpportunities,
  CostReductionOpportunities,
  PricingOpportunities,
  MarketExpansionOpportunities,
  GeographicExpansionOpportunities,
  CustomerGrowthOpportunities,
  RetentionOpportunities,
  PartnershipOpportunities,
  StrategicAllianceOpportunities,
  AcquisitionOpportunities,
  MergerOpportunities,
  TechnologyOpportunities,
  AutomationOpportunities,
  VendorOptimizationOpportunities,
  ProcurementSavingsOpportunities,
  RealEstateOpportunities,
  AssetOptimizationOpportunities,
  LicensingOpportunities,
  IntellectualPropertyOpportunities,
  InnovationOpportunities,
  MissionImpactOpportunities,
  TopOpportunitiesDashboard,
  QuickWinsDashboard,
  StrategicInvestmentDashboard,
  MissionOpportunityDashboard,
  OpportunityHeatMap,
  OpportunityPipelineComposer,
  ExecutiveOpportunityBriefGenerator,
  OpportunityProjection,
  OpportunityQueries,
  opportunityModels,
} from "@/lib/platform/intelligence/opportunity";
export type {
  CreateOpportunityOptions,
  OpportunityStack,
  OpportunityRequest,
  OpportunityResult,
  OpportunityQueryRequest,
  OpportunityQueryResult,
  ExecutiveOpportunityBrief,
  OpportunityDashboardResult,
  TopOpportunitiesDashboardResult,
  QuickWinsDashboardResult,
  StrategicInvestmentDashboardResult,
  MissionOpportunityDashboardResult,
  OpportunityHealthResult,
  OpportunityExchangeRecord,
  OpportunityLensImpact,
} from "@/lib/platform/intelligence/opportunity";
export {
  IMPROVEMENT_INTELLIGENCE_VERSION,
  createOrganizationalImprovementIntelligence,
  OrganizationalImprovementEngine,
  ImprovementIntelligenceService,
  ImprovementService,
  ImprovementIntelligence,
  ImprovementRepository,
  ImprovementDashboard,
  ImprovementHealth,
  ImprovementModels,
  ImprovementSourceEngine,
  ImprovementAnalysisEngine,
  ImprovementPlanner,
  ImprovementRegistry,
  PriorityScoring,
  ImpactScoring,
  MissionAlignmentAnalysis,
  FinancialImpactAnalysis,
  RiskReductionAnalysis,
  TimeToValueAnalysis as ImprovementTimeToValueAnalysis,
  ResourceRequirementsAnalysis,
  OrganizationalCapacityAnalysis,
  DependencyResolution,
  ImprovementConfidenceAnalysis,
  QuickWinsPlanner,
  StrategicInitiativesPlanner,
  LongTermTransformationPlanner,
  WeeklyPlanComposer,
  MonthlyPlanComposer,
  QuarterlyPlanComposer,
  AnnualRoadmapComposer,
  ContinuousImprovementLoop as OrganizationalContinuousImprovementLoop,
  MissionImprovementDashboard,
  FinancialImprovementDashboard,
  PeopleImprovementDashboard,
  TodaysPrioritiesComposer,
  ImprovementHeatMap,
  DailyExecutiveBriefGenerator,
  ExecutiveImprovementBriefGenerator,
  ImprovementProjection,
  ImprovementQueries,
  improvementModels,
} from "@/lib/platform/intelligence/organizational-improvement";
export type {
  CreateImprovementOptions,
  ImprovementStack,
  ImprovementRequest,
  ImprovementResult,
  ImprovementQueryRequest,
  ImprovementQueryResult,
  DailyExecutiveBrief,
  ExecutiveImprovementBrief,
  ImprovementDashboardResult,
  MissionImprovementDashboardResult,
  FinancialImprovementDashboardResult,
  PeopleImprovementDashboardResult,
  ImprovementHealthResult,
  ImprovementRecord,
  ImprovementLensImpact,
  ContinuousImprovementLoopResult,
} from "@/lib/platform/intelligence/organizational-improvement";
export {
  BUSINESS_MODEL_INTELLIGENCE_VERSION,
  createBusinessModelIntelligence,
  BusinessModelIntelligenceEngine,
  BusinessModelIntelligenceService,
  BusinessModelService,
  BusinessModelIntelligence,
  BusinessModelRepository,
  BusinessModelDashboard,
  BusinessModelHealth,
  BusinessModelModels,
  BusinessModelRegistry,
  BusinessModelSimulator,
  BusinessModelCanvasBuilder,
  LeanCanvasBuilder,
  OrganizationDesignEngine,
  BusinessModelScenarioPlanner,
  CompetitivePositionAnalyzer,
  BusinessModelRiskAnalyzer,
  BusinessModelOpportunityAnalyzer,
  BusinessModelEvolutionPlanner,
  BusinessModelRecommendationComposer,
  ExecutiveBusinessBriefGenerator,
  BusinessModelProjection,
  BusinessModelQueries,
  businessModelModels,
} from "@/lib/platform/intelligence/business-model";
export type {
  CreateBusinessModelOptions,
  BusinessModelStack,
  BusinessModelRequest,
  BusinessModelResult,
  BusinessModelQueryRequest,
  BusinessModelQueryResult,
  ExecutiveBusinessBrief,
  BusinessModelDashboardResult,
  BusinessModelHealthResult,
  BusinessModelCanvasResult,
  LeanCanvasResult,
  BusinessModelLensImpact,
  OrganizationDesignSuite,
  BusinessModelScenarioSuite,
  BusinessModelComparisonResult,
} from "@/lib/platform/intelligence/business-model";
export {
  OPERATIONS_INTELLIGENCE_VERSION,
  createOperationsIntelligence,
  OperationsIntelligenceEngine,
  OperationsIntelligenceService,
  OperationsService,
  OperationsIntelligence,
  OperationsRepository,
  OperationsDashboard,
  OperationsHealth,
  OperationsModels,
  OperationsRegistry,
  WorkflowHealthEngine,
  ProcessMonitoringEngine,
  StaffingAnalyticsEngine,
  CapacityPlanner,
  ResourceUtilizationAnalyzer,
  AutomationOpportunityEngine,
  OperationsRiskAnalyzer,
  OperationsOpportunityAnalyzer,
  OperationsRecommendationComposer,
  ExecutiveOperationsBriefGenerator,
  OperationsProjection,
  OperationsQueries,
  operationsModels,
  WORKFLOW_HEALTH_DIMENSIONS,
  PROCESS_MONITORING_AREAS,
  AUTOMATION_OPPORTUNITY_KINDS,
  CAPACITY_PLANNING_HORIZONS,
} from "@/lib/platform/intelligence/operations";
export type {
  CreateOperationsOptions,
  OperationsStack,
  OperationsRequest,
  OperationsResult,
  OperationsQueryRequest,
  OperationsQueryResult,
  ExecutiveOperationsBrief,
  OperationsDashboardResult,
  OperationsHealthResult,
  OperationsLensImpact,
  WorkflowHealthResult,
  ProcessMonitoringSuite,
  StaffingAnalyticsResult,
  CapacityPlanResult,
  AutomationOpportunitySuite,
  ResourceUtilizationResult,
} from "@/lib/platform/intelligence/operations";
export {
  CUSTOMER_INTELLIGENCE_VERSION,
  createCustomerIntelligence,
  CustomerIntelligenceEngine,
  CustomerIntelligenceService,
  CustomerService,
  CustomerIntelligence,
  CustomerRepository,
  CustomerDashboard,
  CustomerHealth,
  CustomerModels,
  CustomerRegistry,
  JourneyMapEngine,
  EngagementEngine,
  SatisfactionEngine,
  RetentionRiskEngine,
  CommunityBelongingEngine,
  CustomerRiskAnalyzer,
  CustomerOpportunityAnalyzer,
  CustomerRecommendationComposer,
  ExecutiveCustomerBriefGenerator,
  CustomerProjection,
  CustomerQueries,
  customerModels,
  JOURNEY_STAGES,
  ENGAGEMENT_DIMENSIONS,
  SATISFACTION_SIGNALS,
  RETENTION_RISK_FACTORS,
  COMMUNITY_BELONGING_PILLARS,
} from "@/lib/platform/intelligence/customer";
export type {
  CreateCustomerOptions,
  CustomerStack,
  CustomerRequest,
  CustomerResult,
  CustomerQueryRequest,
  CustomerQueryResult,
  ExecutiveCustomerBrief,
  CustomerDashboardResult,
  CustomerHealthResult,
  CustomerLensImpact,
  JourneyMapResult,
  EngagementResult,
  SatisfactionSuite,
  RetentionWatchlistResult,
  CommunityHealthResult,
} from "@/lib/platform/intelligence/customer";
export {
  KNOWLEDGE_INTELLIGENCE_VERSION,
  createKnowledgeIntelligence,
  KnowledgeIntelligenceEngine,
  KnowledgeIntelligenceService,
  KnowledgeService,
  KnowledgeIntelligence,
  KnowledgeRepository,
  KnowledgeDashboard,
  KnowledgeHealth,
  KnowledgeModels,
  KnowledgeRegistry,
  KnowledgeCaptureEngine,
  KnowledgeGraphEngine,
  KnowledgeSearchEngine,
  KnowledgeReasoner,
  KnowledgeGapEngine,
  ExpertiseMapEngine,
  KnowledgeProvenanceEngine,
  KnowledgeQualityEngine,
  KnowledgeValidation,
  KnowledgeFreshness,
  KnowledgeCompleteness,
  KnowledgeAccuracy,
  KnowledgeConsistency,
  KnowledgeConflictDetection,
  KnowledgeRedundancyDetection,
  KnowledgeCoverageAnalysis,
  KnowledgeLifecycleManagement,
  OrganizationalMemoryEngine,
  KnowledgeEvolutionEngine,
  DecisionTraceabilityEngine,
  KnowledgeRiskAnalyzer,
  KnowledgeOpportunityAnalyzer,
  KnowledgeRecommendationComposer,
  ExecutiveKnowledgeBriefGenerator,
  KnowledgeProjection,
  KnowledgeQueries,
  knowledgeModels,
  KNOWLEDGE_TYPES,
  KNOWLEDGE_SOURCES,
  KNOWLEDGE_SOURCE_TYPES,
  KNOWLEDGE_RELATION_KINDS,
  KNOWLEDGE_GAP_CATEGORIES,
  KNOWLEDGE_QUALITY_DIMENSIONS,
  KNOWLEDGE_EVOLUTION_ACTIONS,
  KNOWLEDGE_APPROVAL_STATUSES,
  ORGANIZATIONAL_MEMORY_KINDS,
  EXPERTISE_DOMAINS,
} from "@/lib/platform/intelligence/knowledge";
export type {
  CreateKnowledgeOptions,
  KnowledgeStack,
  KnowledgeRequest,
  KnowledgeResult,
  KnowledgeQueryRequest,
  KnowledgeQueryResult,
  ExecutiveKnowledgeBrief,
  KnowledgeDashboardResult,
  KnowledgeHealthResult,
  KnowledgeLensImpact,
  KnowledgeCatalogResult,
  KnowledgeGraphResult,
  KnowledgeSearchResult,
  KnowledgeReasoningResult,
  KnowledgeGapResult,
  ExpertiseMapResult,
  KnowledgeProvenanceSuite,
  KnowledgeQualitySuite,
  OrganizationalMemorySuite,
  KnowledgeEvolutionResult,
  DecisionTraceabilityResult,
  KnowledgeRecommendationRecord,
} from "@/lib/platform/intelligence/knowledge";
export {
  DOCUMENT_INTELLIGENCE_VERSION,
  createDocumentIntelligence,
  DocumentIntelligenceEngine,
  DocumentIntelligenceService,
  DocumentService,
  DocumentIntelligence,
  DocumentRepository,
  DocumentDashboard,
  DocumentHealth,
  DocumentModels,
  DocumentRegistry,
  DocumentParser,
  DocumentClassifier,
  DocumentMetadataIntelligence,
  DocumentEntityRelationshipIntelligence,
  DocumentVersionDuplicateIntelligence,
  DocumentSummarizationClauseIntelligence,
  DocumentRiskComplianceIntelligence,
  DocumentExpirationIntelligence,
  DocumentKnowledgeContributionEngine,
  DocumentReasoner,
  DocumentRiskAnalyzer,
  DocumentOpportunityAnalyzer,
  DocumentRecommendationComposer,
  ExecutiveDocumentBriefGenerator,
  DocumentProjection,
  DocumentQueries,
  DocumentSpecializedDashboards,
  documentModels,
  DOCUMENT_TYPES,
  DOCUMENT_CAPABILITIES,
  DOCUMENT_RELATION_KINDS,
  DOCUMENT_RISK_CATEGORIES,
  DOCUMENT_COMPLIANCE_TAGS,
  DOCUMENT_ARTIFACT_STATUSES,
} from "@/lib/platform/intelligence/document";
export type {
  CreateDocumentOptions,
  DocumentStack,
  DocumentRequest,
  DocumentResult,
  DocumentQueryRequest,
  DocumentQueryResult,
  ExecutiveDocumentBrief,
  DocumentDashboardResult,
  DocumentHealthResult,
  DocumentLensImpact,
  DocumentCatalogResult,
  DocumentKnowledgeContribution,
  DocumentRecommendationRecord,
  ContractDashboardResult,
  PolicyDashboardResult,
  GrantDashboardResult,
  ComplianceDashboardResult,
} from "@/lib/platform/intelligence/document";
export {
  LEGAL_COMPLIANCE_RISK_INTELLIGENCE_VERSION,
  createLegalComplianceRiskIntelligence,
  LegalComplianceRiskIntelligenceEngine,
  LegalComplianceRiskIntelligenceService,
  LegalComplianceRiskService,
  LegalComplianceRiskIntelligence,
  LegalComplianceRiskRepository,
  LegalComplianceRiskDashboard,
  LegalComplianceRiskHealth,
  LegalComplianceRiskModels,
  LegalComplianceRiskRegistry,
  LegalComplianceRiskReasoner,
  LegalComplianceRiskKnowledgeContributionEngine,
  LegalComplianceRiskSpecializedDashboards,
  LegalComplianceRiskRiskAnalyzer,
  LegalComplianceRiskOpportunityAnalyzer,
  LegalComplianceRiskRecommendationComposer,
  CorrectiveActionPlanner,
  ExecutiveRiskBriefGenerator,
  BoardComplianceBriefGenerator,
  LegalComplianceRiskProjection,
  LegalComplianceRiskQueries,
  ContractIntelligence,
  RegulatoryIntelligence,
  ComplianceIntelligence,
  EnterpriseRiskIntelligence,
  PolicyIntelligence,
  AuditIntelligence,
  LicensePermitIntelligence,
  InsuranceIntelligence,
  LitigationIntelligence,
  VendorThirdPartyRiskIntelligence,
  CyberGovernanceIntelligence,
  legalComplianceRiskModels,
  RISK_CATEGORIES,
  COMPLIANCE_SCOPES,
  LEGAL_COMPLIANCE_RISK_CAPABILITIES,
} from "@/lib/platform/intelligence/legal-compliance-risk";
export type {
  CreateLegalComplianceRiskOptions,
  LegalComplianceRiskStack,
  LegalComplianceRiskRequest,
  LegalComplianceRiskResult,
  LegalComplianceRiskQueryRequest,
  LegalComplianceRiskQueryResult,
  ExecutiveRiskBrief,
  BoardComplianceBrief,
  LegalComplianceRiskDashboardResult,
  EnterpriseRiskDashboardResult,
  ComplianceDashboardResult as LegalComplianceRiskComplianceDashboardResult,
  ContractDashboardResult as LegalComplianceRiskContractDashboardResult,
  AuditDashboardResult,
  CorrectiveActionPlanResult,
  LegalComplianceRiskHealthResult,
  LegalComplianceRiskLens,
  LegalComplianceRiskRecommendationRecord,
  RiskCategory,
  ComplianceScope,
} from "@/lib/platform/intelligence/legal-compliance-risk";
export {
  MARKET_INTELLIGENCE_VERSION,
  createMarketIntelligence,
  MarketIntelligenceEngine,
  MarketIntelligenceService,
  MarketService,
  MarketIntelligence,
  MarketRepository,
  MarketDashboard,
  MarketHealth,
  MarketModels,
  MarketRegistry,
  MarketReasoner,
  MarketKnowledgeContributionEngine,
  MarketSpecializedDashboards,
  MarketRiskAnalyzer,
  MarketOpportunityAnalyzer,
  MarketRecommendationComposer,
  ExecutiveMarketBriefGenerator,
  MarketProjection,
  MarketQueries,
  IndustryIntelligence,
  MarketCompetitiveIntelligence,
  CompetitiveIntelligence,
  MarketSizeIntelligence,
  PricingIntelligence,
  CustomerDemandIntelligence,
  DemographicIntelligence,
  GeographicExpansionIntelligence,
  EconomicTrendIntelligence,
  TechnologyTrendIntelligence,
  PartnershipIntelligence,
  MergersAcquisitionsIntelligence,
  WhiteSpaceIntelligence,
  marketModels,
  MARKET_CAPABILITIES,
  MARKET_SIGNAL_KINDS,
} from "@/lib/platform/intelligence/market";
export type {
  CreateMarketOptions,
  MarketStack,
  MarketRequest,
  MarketResult,
  MarketQueryRequest,
  MarketQueryResult,
  ExecutiveMarketBrief,
  MarketDashboardResult,
  CompetitiveDashboardResult,
  ExpansionDashboardResult,
  TrendDashboardResult,
  MarketHealthResult,
  MarketLens,
  MarketRecommendationRecord,
  MarketSignalKind,
} from "@/lib/platform/intelligence/market";
export {
  INNOVATION_INTELLIGENCE_VERSION,
  createInnovationIntelligence,
  InnovationIntelligenceEngine,
  InnovationIntelligenceService,
  InnovationService,
  InnovationIntelligence,
  InnovationRepository,
  InnovationDashboard,
  InnovationHealth,
  InnovationModels,
  InnovationRegistry,
  InnovationReasoner,
  InnovationKnowledgeContributionEngine,
  InnovationSpecializedDashboards,
  InnovationRiskAnalyzer,
  InnovationOpportunityAnalyzer,
  InnovationRecommendationComposer,
  ExecutiveInnovationBriefGenerator,
  InnovationProjection,
  InnovationQueries,
  IdeaManagementIntelligence,
  ResearchDevelopmentIntelligence,
  ProductServiceInnovationIntelligence,
  ProcessInnovationIntelligence,
  AiOpportunityIntelligence,
  TechnologyAdoptionIntelligence,
  EmergingTechnologyIntelligence,
  InnovationPortfolioIntelligence,
  ExperimentManagementIntelligence,
  ProofOfConceptIntelligence,
  IntellectualPropertyIntelligence,
  ContinuousImprovementIntelligence,
  StrategicRoadmapIntelligence,
  innovationModels,
  INNOVATION_CAPABILITIES,
  INNOVATION_HORIZONS,
  IDEA_STATUSES,
  EXPERIMENT_STATUSES,
  TECHNOLOGY_RADAR_RINGS,
  IP_KINDS,
} from "@/lib/platform/intelligence/innovation";
export type {
  CreateInnovationOptions,
  InnovationStack,
  InnovationRequest,
  InnovationResult,
  InnovationQueryRequest,
  InnovationQueryResult,
  ExecutiveInnovationBrief,
  InnovationDashboardResult,
  InnovationPipelineResult,
  IdeaBacklogResult,
  ExperimentDashboardResult,
  InnovationPortfolioResult,
  TechnologyRadarResult,
  InnovationHealthResult,
  InnovationLens,
  InnovationRecommendationRecord,
  InnovationHorizon,
} from "@/lib/platform/intelligence/innovation";
export {
  IMPACT_INTELLIGENCE_VERSION,
  IMPACT_CAPABILITIES,
  IMPACT_AREAS,
  INDICATOR_TYPES,
  MEASUREMENT_KINDS,
  IMPACT_HEALTH_STATUSES,
  IMPACT_PRIORITY_BANDS,
  IMPACT_ARTIFACT_STATUSES,
  IMPACT_CONFIDENCE_LEVELS,
  createImpactIntelligence,
  ImpactIntelligenceEngine,
  ImpactIntelligenceService,
  ImpactService,
  ImpactIntelligence,
  ImpactRepository,
  ImpactRegistry,
  ImpactModels,
  ImpactReasoner,
  ImpactMeasurementEngine,
  OutcomeEngine,
  RoiEngine,
  ImpactKnowledgeContributionEngine,
  ClosedLearningLoop,
  ImpactRecommendationComposer,
  ImpactProjection,
  ImpactQueries,
  MissionImpactIntelligence,
  CustomerImpactIntelligence,
  EmployeeImpactIntelligence,
  StudentImpactIntelligence,
  CommunityImpactIntelligence,
  FinancialImpactIntelligence,
  GrantImpactIntelligence,
  ProgramEffectivenessImpactIntelligence,
  StrategicGoalAchievementImpactIntelligence,
  OperationalImpactIntelligence,
  InnovationImpactIntelligence,
  LongTermOrganizationalImpactIntelligence,
  impactModels,
} from "@/lib/platform/intelligence/impact";
export type {
  CreateImpactOptions,
  ImpactStack,
  ImpactRequest,
  ImpactResult,
  ImpactQueryRequest,
  ImpactQueryResult,
  ImpactLens,
  ImpactBaseline,
  ImpactHealthScore,
  ImpactDashboard,
  MissionImpactDashboard,
  OutcomeDashboard,
  ProgramEffectivenessDashboard,
  RoiDashboard,
  SroiDashboard,
  ExecutiveImpactBrief,
  BoardImpactReport,
  ImpactRecommendationRecord,
  ImpactMeasurementSuite,
  OutcomeSuite,
  RoiSuite,
  ImpactKnowledgeContribution,
  ClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/impact";
export {
  ECONOMIC_INTELLIGENCE_VERSION,
  ECONOMIC_CAPABILITIES,
  ECONOMIC_AREAS,
  ECONOMIC_SCENARIOS,
  ECONOMIC_ANALYSIS_KINDS,
  ECONOMIC_HEALTH_STATUSES,
  ECONOMIC_PRIORITY_BANDS,
  ECONOMIC_ARTIFACT_STATUSES,
  ECONOMIC_CONFIDENCE_LEVELS,
  ECONOMIC_OUTLOOKS,
  createEconomicIntelligence,
  EconomicIntelligenceEngine,
  EconomicIntelligenceService,
  EconomicService,
  EconomicIntelligence,
  EconomicRepository,
  EconomicRegistry,
  EconomicModels,
  EconomicReasoner,
  EconomicForecastEngine,
  EconomicScenarioEngine,
  EconomicTrendEngine,
  EconomicAnalysisEngine,
  EconomicKnowledgeContributionEngine,
  ClosedLearningLoop as EconomicClosedLearningLoop,
  EconomicRecommendationComposer,
  EconomicProjection,
  EconomicQueries,
  InflationIntelligence,
  InterestRatesIntelligence,
  GdpIntelligence,
  EmploymentIntelligence,
  LaborMarketIntelligence,
  WageTrendsIntelligence,
  HousingIntelligence,
  HealthcareIntelligence,
  EnergyIntelligence,
  SupplyChainsIntelligence,
  CommodityPricesIntelligence,
  CurrencyIntelligence,
  GovernmentSpendingIntelligence,
  TaxEnvironmentIntelligence,
  ConsumerSpendingIntelligence,
  IndustryConditionsIntelligence,
  RegionalEconomicsIntelligence,
  InternationalEconomicsIntelligence,
  economicModels,
} from "@/lib/platform/intelligence/economic";
export type {
  CreateEconomicOptions,
  EconomicStack,
  EconomicRequest,
  EconomicResult,
  EconomicQueryRequest,
  EconomicQueryResult,
  EconomicLens,
  EconomicBaseline,
  EconomicHealthScore,
  EconomicDashboard,
  EconomicOutlookDashboard,
  InflationDashboard,
  LaborMarketDashboard,
  CostPressureDashboard,
  EconomicForecastDashboard,
  ExecutiveEconomicBrief,
  BoardEconomicReport,
  EconomicRecommendationRecord,
  EconomicForecastSuite,
  EconomicScenarioSuite,
  EconomicAnalysisSuite,
  EconomicKnowledgeContribution,
  ClosedLearningLoopContribution as EconomicClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/economic";
export {
  createCompetitiveIntelligence,
  COMPETITIVE_INTELLIGENCE_VERSION,
  COMPETITIVE_AREAS,
  COMPETITIVE_SCENARIOS,
  COMPETITIVE_ANALYSIS_KINDS,
  COMPETITIVE_CAPABILITIES,
  competitiveModels,
} from "@/lib/platform/intelligence/competitive";
export type {
  CreateCompetitiveOptions,
  CompetitiveStack,
  CompetitiveRequest,
  CompetitiveResult,
  CompetitiveQueryRequest,
  CompetitiveQueryResult,
  CompetitiveLens,
  CompetitiveBaseline,
  CompetitiveHealthScore,
  CompetitiveDashboard,
  CompetitiveOutlookDashboard,
  ThreatDashboard,
  DifferentiationDashboard,
  SignalMonitoringDashboard,
  CompetitiveForecastDashboard,
  ExecutiveCompetitiveBrief,
  BoardCompetitiveReport,
  CompetitiveRecommendationRecord,
  CompetitiveForecastSuite,
  CompetitiveScenarioSuite,
  CompetitiveAnalysisSuite,
  CompetitiveKnowledgeContribution,
  ClosedLearningLoopContribution as CompetitiveClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/competitive";
export {
  createPoliticalIntelligence,
  POLITICAL_INTELLIGENCE_VERSION,
  POLITICAL_AREAS,
  POLITICAL_SCENARIOS,
  POLITICAL_ANALYSIS_KINDS,
  POLITICAL_CAPABILITIES,
  politicalModels,
} from "@/lib/platform/intelligence/political";
export type {
  CreatePoliticalOptions,
  PoliticalStack,
  PoliticalRequest,
  PoliticalResult,
  PoliticalQueryRequest,
  PoliticalQueryResult,
  PoliticalLens,
  PoliticalBaseline,
  PoliticalHealthScore,
  PoliticalDashboard,
  PoliticalOutlookDashboard,
  RegulatoryDashboard,
  LegislativeDashboard,
  FundingOpportunitiesDashboard,
  PoliticalRiskDashboard,
  TradeInternationalDashboard,
  ElectionImpactDashboard,
  ExecutivePoliticalBrief,
  BoardPoliticalReport,
  PoliticalRecommendationRecord,
  PoliticalForecastSuite,
  PoliticalScenarioSuite,
  PoliticalAnalysisSuite,
  PoliticalKnowledgeContribution,
  ClosedLearningLoopContribution as PoliticalClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/political";
export {
  createEnvironmentalIntelligence,
  ENVIRONMENTAL_INTELLIGENCE_VERSION,
  ENVIRONMENTAL_AREAS,
  ENVIRONMENTAL_SCENARIOS,
  ENVIRONMENTAL_ANALYSIS_KINDS,
  ENVIRONMENTAL_CAPABILITIES,
  environmentalModels,
} from "@/lib/platform/intelligence/environmental";
export type {
  CreateEnvironmentalOptions,
  EnvironmentalStack,
  EnvironmentalRequest,
  EnvironmentalResult,
  EnvironmentalQueryRequest,
  EnvironmentalQueryResult,
  EnvironmentalLens,
  EnvironmentalBaseline,
  EnvironmentalHealthScore,
  EnvironmentalDashboard,
  EnvironmentalOutlookDashboard,
  ClimateDashboard,
  DisasterRiskDashboard,
  SustainabilityDashboard,
  InfrastructureDashboard,
  ResourceMonitoringDashboard,
  EsgOverviewDashboard,
  ExecutiveEnvironmentalBrief,
  BoardEnvironmentalReport,
  EnvironmentalRecommendationRecord,
  EnvironmentalForecastSuite,
  EnvironmentalScenarioSuite,
  EnvironmentalAnalysisSuite,
  EnvironmentalKnowledgeContribution,
  ClosedLearningLoopContribution as EnvironmentalClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/environmental";
export {
  createStakeholderIntelligence,
  STAKEHOLDER_INTELLIGENCE_VERSION,
  STAKEHOLDER_AREAS,
  STAKEHOLDER_SCENARIOS,
  STAKEHOLDER_ANALYSIS_KINDS,
  STAKEHOLDER_CAPABILITIES,
  stakeholderModels,
} from "@/lib/platform/intelligence/stakeholder";
export type {
  CreateStakeholderOptions,
  StakeholderStack,
  StakeholderRequest,
  StakeholderResult,
  StakeholderQueryRequest,
  StakeholderQueryResult,
  StakeholderLens,
  StakeholderBaseline,
  StakeholderHealthScore,
  StakeholderDashboard,
  InfluenceMapDashboard,
  RelationshipsDashboard,
  EngagementDashboard,
  SentimentDashboard,
  TrustDashboard,
  CollaborationOpportunitiesDashboard,
  StakeholderForecastDashboard,
  ExecutiveStakeholderBrief,
  BoardStakeholderReport,
  StakeholderRecommendationRecord,
  StakeholderForecastSuite,
  StakeholderScenarioSuite,
  StakeholderAnalysisSuite,
  StakeholderKnowledgeContribution,
  ClosedLearningLoopContribution as StakeholderClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/stakeholder";
export {
  createReputationIntelligence,
  REPUTATION_INTELLIGENCE_VERSION,
  REPUTATION_AREAS,
  REPUTATION_SCENARIOS,
  REPUTATION_ANALYSIS_KINDS,
  REPUTATION_CAPABILITIES,
  reputationModels,
} from "@/lib/platform/intelligence/reputation";
export type {
  CreateReputationOptions,
  ReputationStack,
  ReputationRequest,
  ReputationResult,
  ReputationQueryRequest,
  ReputationQueryResult,
  ReputationLens,
  ReputationBaseline,
  ReputationHealthScore,
  ReputationDashboard,
  TrustDashboard as ReputationTrustDashboard,
  BrandReputationDashboard,
  MediaIntelligenceDashboard,
  NarrativeAnalysisDashboard,
  CrisisMonitoringDashboard,
  ReputationRecoveryDashboard,
  ReputationForecastDashboard,
  ExecutiveReputationBrief,
  BoardReputationReport,
  ReputationRecommendationRecord,
  ReputationForecastSuite,
  ReputationScenarioSuite,
  ReputationAnalysisSuite,
  ReputationKnowledgeContribution,
  ClosedLearningLoopContribution as ReputationClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/reputation";
export {
  createBehavioralIntelligence,
  BEHAVIORAL_INTELLIGENCE_VERSION,
  BEHAVIORAL_AREAS,
  BEHAVIORAL_SCENARIOS,
  BEHAVIORAL_ANALYSIS_KINDS,
  BEHAVIORAL_CAPABILITIES,
  behavioralModels,
} from "@/lib/platform/intelligence/behavioral";
export type {
  CreateBehavioralOptions,
  BehavioralStack,
  BehavioralRequest,
  BehavioralResult,
  BehavioralQueryRequest,
  BehavioralQueryResult,
  BehavioralLens,
  BehavioralBaseline,
  BehavioralHealthScore,
  BehavioralDashboard,
  DecisionIntelligenceDashboard,
  OrganizationalChangeDashboard,
  LeadershipDashboard,
  TeamDynamicsDashboard,
  CollaborationDashboard as BehavioralCollaborationDashboard,
  AdoptionForecastDashboard,
  BehavioralOutlookDashboard,
  ExecutiveBehavioralBrief,
  BoardBehavioralReport,
  BehavioralRecommendationRecord,
  BehavioralForecastSuite,
  BehavioralScenarioSuite,
  BehavioralAnalysisSuite,
  BehavioralKnowledgeContribution,
  ClosedLearningLoopContribution as BehavioralClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/behavioral";
export {
  createCulturalIntelligence,
  CULTURAL_INTELLIGENCE_VERSION,
  CULTURAL_AREAS,
  CULTURAL_SCENARIOS,
  CULTURAL_ANALYSIS_KINDS,
  CULTURAL_CAPABILITIES,
  culturalModels,
} from "@/lib/platform/intelligence/cultural";
export type {
  CreateCulturalOptions,
  CulturalStack,
  CulturalRequest,
  CulturalResult,
  CulturalQueryRequest,
  CulturalQueryResult,
  CulturalLens,
  CulturalBaseline,
  CulturalHealthScore,
  CulturalDashboard,
  OrganizationalCultureDashboard,
  MissionValuesDashboard,
  EmployeeEngagementDashboard,
  CollaborationDashboard as CulturalCollaborationDashboard,
  InnovationCultureDashboard,
  CulturalTransformationDashboard,
  CulturalForecastDashboard,
  ExecutiveCulturalBrief,
  BoardCulturalReport,
  CulturalRecommendationRecord,
  CulturalForecastSuite,
  CulturalScenarioSuite,
  CulturalAnalysisSuite,
  CulturalKnowledgeContribution,
  ClosedLearningLoopContribution as CulturalClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/cultural";
export {
  createEthicalIntelligence,
  ETHICAL_INTELLIGENCE_VERSION,
  ETHICAL_AREAS,
  ETHICAL_SCENARIOS,
  ETHICAL_ANALYSIS_KINDS,
  ETHICAL_CAPABILITIES,
  ethicalModels,
} from "@/lib/platform/intelligence/ethical";
export type {
  CreateEthicalOptions,
  EthicalStack,
  EthicalRequest,
  EthicalResult,
  EthicalQueryRequest,
  EthicalQueryResult,
  EthicalLens,
  EthicalBaseline,
  EthicalHealthScore,
  EthicalDashboard,
  ValuesAlignmentDashboard,
  FairnessDashboard,
  AiEthicsDashboard,
  HumanImpactDashboard,
  GovernanceDashboard as EthicalGovernanceDashboard,
  EthicalRiskDashboard,
  EthicalOutlookDashboard,
  ExecutiveEthicalBrief,
  BoardEthicalReport,
  EthicalRecommendationRecord,
  EthicalForecastSuite,
  EthicalScenarioSuite,
  EthicalAnalysisSuite,
  EthicalKnowledgeContribution,
  ClosedLearningLoopContribution as EthicalClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/ethical";
export {
  createSystemsIntelligence,
  SYSTEMS_INTELLIGENCE_VERSION,
  SYSTEMS_AREAS,
  SYSTEMS_SCENARIOS,
  SYSTEMS_ANALYSIS_KINDS,
  SYSTEMS_CAPABILITIES,
  systemsModels,
} from "@/lib/platform/intelligence/systems";
export type {
  CreateSystemsOptions,
  SystemsStack,
  SystemsRequest,
  SystemsResult,
  SystemsQueryRequest,
  SystemsQueryResult,
  SystemsLens,
  SystemsBaseline,
  SystemsHealthScore,
  SystemsDashboard,
  DependencyMapDashboard,
  FeedbackLoopsDashboard,
  BottlenecksDashboard,
  SystemHealthDashboard,
  ComplexityAnalysisDashboard,
  AdaptiveCapacityDashboard,
  SystemsForecastDashboard,
  ExecutiveSystemsBrief,
  BoardSystemsReport,
  SystemsRecommendationRecord,
  SystemsForecastSuite,
  SystemsScenarioSuite,
  SystemsAnalysisSuite,
  SystemsKnowledgeContribution,
  ClosedLearningLoopContribution as SystemsClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/systems";
export {
  createResilienceIntelligence,
  RESILIENCE_INTELLIGENCE_VERSION,
  RESILIENCE_AREAS,
  RESILIENCE_SCENARIOS,
  RESILIENCE_ANALYSIS_KINDS,
  RESILIENCE_CAPABILITIES,
  resilienceModels,
} from "@/lib/platform/intelligence/resilience";
export type {
  CreateResilienceOptions,
  ResilienceStack,
  ResilienceRequest,
  ResilienceResult,
  ResilienceQueryRequest,
  ResilienceQueryResult,
  ResilienceLens,
  ResilienceBaseline,
  ResilienceHealthScore,
  ResilienceDashboard,
  BusinessContinuityDashboard,
  DisasterRecoveryDashboard,
  OperationalStabilityDashboard,
  FinancialResilienceDashboard,
  CyberInfrastructureDashboard,
  StressTestingDashboard,
  ResilienceForecastDashboard,
  ExecutiveResilienceBrief,
  BoardResilienceReport,
  ResilienceRecommendationRecord,
  ResilienceForecastSuite,
  ResilienceScenarioSuite,
  ResilienceAnalysisSuite,
  ResilienceKnowledgeContribution,
  ClosedLearningLoopContribution as ResilienceClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/resilience";
export {
  createEcosystemIntelligence,
  ECOSYSTEM_INTELLIGENCE_VERSION,
  ECOSYSTEM_AREAS,
  ECOSYSTEM_SCENARIOS,
  ECOSYSTEM_ANALYSIS_KINDS,
  ECOSYSTEM_CAPABILITIES,
  ecosystemModels,
} from "@/lib/platform/intelligence/ecosystem";
export type {
  CreateEcosystemOptions,
  EcosystemStack,
  EcosystemRequest,
  EcosystemResult,
  EcosystemQueryRequest,
  EcosystemQueryResult,
  EcosystemLens,
  EcosystemBaseline,
  EcosystemHealthScore,
  EcosystemDashboard,
  EcosystemMapDashboard,
  StrategicPartnershipsDashboard,
  AlliancesDashboard,
  DependenciesDashboard,
  CollaborationOpportunitiesDashboard as EcosystemCollaborationOpportunitiesDashboard,
  EcosystemHealthDashboard,
  EcosystemForecastDashboard,
  ExecutiveEcosystemBrief,
  BoardEcosystemReport,
  EcosystemRecommendationRecord,
  EcosystemForecastSuite,
  EcosystemScenarioSuite,
  EcosystemAnalysisSuite,
  EcosystemKnowledgeContribution,
  ClosedLearningLoopContribution as EcosystemClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/ecosystem";
export {
  createInstitutionalMemoryIntelligence,
  INSTITUTIONAL_MEMORY_INTELLIGENCE_VERSION,
  INSTITUTIONAL_MEMORY_AREAS,
  INSTITUTIONAL_MEMORY_SCENARIOS,
  INSTITUTIONAL_MEMORY_ANALYSIS_KINDS,
  INSTITUTIONAL_MEMORY_CAPABILITIES,
  institutionalMemoryModels,
} from "@/lib/platform/intelligence/institutional-memory";
export type {
  CreateInstitutionalMemoryOptions,
  InstitutionalMemoryStack,
  InstitutionalMemoryRequest,
  InstitutionalMemoryResult,
  InstitutionalMemoryQueryRequest,
  InstitutionalMemoryQueryResult,
  InstitutionalMemoryLens,
  InstitutionalMemoryBaseline,
  InstitutionalMemoryHealthScore,
  InstitutionalMemoryDashboard,
  KnowledgeGraphDashboard,
  OrganizationalMemoryDashboard,
  ExpertiseMapDashboard,
  LessonsLearnedDashboard,
  KnowledgeQualityDashboard,
  KnowledgeGapsDashboard,
  InstitutionalMemoryForecastDashboard,
  ExecutiveInstitutionalMemoryBrief,
  BoardInstitutionalMemoryReport,
  InstitutionalMemoryRecommendationRecord,
  InstitutionalMemoryForecastSuite,
  InstitutionalMemoryScenarioSuite,
  InstitutionalMemoryAnalysisSuite,
  InstitutionalMemoryKnowledgeContribution,
  ClosedLearningLoopContribution as InstitutionalMemoryClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/institutional-memory";
export {
  createCollectiveIntelligence,
  COLLECTIVE_INTELLIGENCE_VERSION,
  COLLECTIVE_AREAS,
  COLLECTIVE_SCENARIOS,
  COLLECTIVE_ANALYSIS_KINDS,
  COLLECTIVE_CAPABILITIES,
  collectiveModels,
} from "@/lib/platform/intelligence/collective";
export type {
  CreateCollectiveOptions,
  CollectiveStack,
  CollectiveRequest,
  CollectiveResult,
  CollectiveQueryRequest,
  CollectiveQueryResult,
  CollectiveLens,
  CollectiveBaseline,
  CollectiveHealthScore,
  CollectiveDashboard,
  ConsensusDashboard,
  CrossDomainIntelligenceDashboard,
  ExpertiseNetworkDashboard,
  OrganizationalAlignmentDashboard,
  CollaborationHealthDashboard,
  CollectiveLearningDashboard,
  CollectiveForecastDashboard,
  ExecutiveCollectiveBrief,
  BoardCollectiveReport,
  CollectiveRecommendationRecord,
  CollectiveForecastSuite,
  CollectiveScenarioSuite,
  CollectiveAnalysisSuite,
  CollectiveKnowledgeContribution,
  ClosedLearningLoopContribution as CollectiveClosedLearningLoopContribution,
} from "@/lib/platform/intelligence/collective";
export {
  createWisdomIntelligence,
  WISDOM_INTELLIGENCE_VERSION,
  WISDOM_AREAS,
  WISDOM_SCENARIOS,
  WISDOM_ANALYSIS_KINDS,
  WISDOM_CAPABILITIES,
  wisdomModels,
} from "@/lib/platform/intelligence/wisdom";
export type {
  CreateWisdomOptions,
  WisdomStack,
  WisdomRequest,
  WisdomResult,
  WisdomQueryRequest,
  WisdomQueryResult,
  WisdomLens,
  WisdomBaseline,
  WisdomHealthScore,
  WisdomDashboard,
  StrategicJudgmentDashboard,
  CrossDomainSynthesisDashboard,
  TradeOffAnalysisDashboard,
  OrganizationalPrioritiesDashboard,
  ConfidenceDashboard,
  LongTermOutlookDashboard,
  WisdomForecastDashboard,
  ExecutiveWisdomBrief,
  BoardWisdomReport,
  WisdomRecommendationRecord,
  WisdomForecastSuite,
  WisdomScenarioSuite,
  WisdomAnalysisSuite,
  WisdomKnowledgeContribution,
  ClosedLearningLoopContribution as WisdomClosedLearningLoopContribution,
  ExecutiveJudgmentFramework,
} from "@/lib/platform/intelligence/wisdom";
export {
  createSynthesisIntelligence,
  SYNTHESIS_INTELLIGENCE_VERSION,
  SYNTHESIS_MODULE_ID,
  SYNTHESIS_PRIORITIES,
  SYNTHESIS_HORIZONS,
  SYNTHESIS_TREND_WINDOWS,
} from "@/lib/platform/intelligence/synthesis";
export type {
  CreateSynthesisOptions,
  SynthesisStack,
  SynthesisRequest,
  SynthesisResult,
  ExecutiveBrief as SynthesisExecutiveBrief,
  SynthesizedInsight,
  DomainSignalLight,
  SynthesisAnalyzer,
} from "@/lib/platform/intelligence/synthesis";
export {
  createBriefingIntelligence,
  BRIEFING_INTELLIGENCE_VERSION,
  BRIEFING_MODULE_ID,
  BRIEFING_ROLES,
  BRIEFING_TIMELINE_WINDOWS,
  BRIEFING_ACTIONS,
} from "@/lib/platform/intelligence/briefing";
export type {
  CreateBriefingOptions,
  BriefingStack,
  BriefingRequest,
  BriefingResult,
  ExecutiveBriefing,
  MorningBriefSections,
  DecisionCard as BriefingDecisionCard,
  OpportunityCard as BriefingOpportunityCard,
  BriefingCard,
  BriefingPersonalizer,
} from "@/lib/platform/intelligence/briefing";
export {
  createExecutiveMemoryIntelligence,
  EXECUTIVE_MEMORY_VERSION,
  EXECUTIVE_MEMORY_MODULE_ID,
  MEMORY_ENTITY_KINDS,
  MEMORY_RETENTION_POLICIES,
} from "@/lib/platform/intelligence/executive-memory";
export type {
  CreateExecutiveMemoryOptions,
  ExecutiveMemoryStack,
  ExecutiveMemoryRequest,
  ExecutiveMemoryResult,
  MemoryRecallQuery,
  MemoryRecallResult,
  DecisionMemory,
  BriefingMemory,
  LessonMemory,
} from "@/lib/platform/intelligence/executive-memory";
export {
  createDecisionIntelligence,
  DECISION_INTELLIGENCE_VERSION,
  DECISION_INTELLIGENCE_MODULE_ID,
  DECISION_APPROVAL_LEVELS,
  DECISION_ISSUE_KINDS,
} from "@/lib/platform/intelligence/decision-intelligence";
export type {
  CreateDecisionIntelligenceOptions,
  DecisionIntelligenceStack,
  DecisionIntelligenceRequest,
  DecisionIntelligenceResult,
  DecisionRecommendation,
  DecisionOption,
  DecisionScorecard,
} from "@/lib/platform/intelligence/decision-intelligence";
export {
  createExecutivePredictiveIntelligence,
  EXECUTIVE_PREDICTIVE_VERSION,
  EXECUTIVE_PREDICTIVE_MODULE_ID,
  FORECAST_SUBJECTS,
  FORECAST_HORIZONS,
  SCENARIO_KINDS,
} from "@/lib/platform/intelligence/executive-predictive";
export type {
  CreateExecutivePredictiveOptions,
  ExecutivePredictiveStack,
  ExecutivePredictiveRequest,
  ExecutivePredictiveResult,
  OrganizationalForecast,
  ScenarioProjection,
  EmergingSignal,
  DecisionImpactForecast,
} from "@/lib/platform/intelligence/executive-predictive";
export {
  createExecutiveAutonomousIntelligence,
  EXECUTIVE_AUTONOMOUS_VERSION,
  EXECUTIVE_AUTONOMOUS_MODULE_ID,
  WORKFLOW_KINDS,
  APPROVAL_ROLES,
  READINESS_STATES,
} from "@/lib/platform/intelligence/executive-autonomous";
export type {
  CreateExecutiveAutonomousOptions,
  ExecutiveAutonomousStack,
  AutonomousRequest,
  AutonomousResult,
  ExecutionPlan,
  AutonomousPreparation,
} from "@/lib/platform/intelligence/executive-autonomous";
export {
  createExecutiveCopilotIntelligence,
  EXECUTIVE_COPILOT_VERSION,
  EXECUTIVE_COPILOT_MODULE_ID,
  COPILOT_INTENTS,
  COPILOT_DOMAIN_KEYS,
} from "@/lib/platform/intelligence/executive-copilot";
export type {
  CreateExecutiveCopilotOptions,
  ExecutiveCopilotStack,
  CopilotRequest,
  CopilotResult,
  CopilotExplainability,
  CopilotInvestigation,
} from "@/lib/platform/intelligence/executive-copilot";
export {
  createExecutiveCommandCenter,
  EXECUTIVE_COMMAND_CENTER_VERSION,
  EXECUTIVE_COMMAND_CENTER_MODULE_ID,
  COMMAND_CENTER_ROLES,
  DRILL_DOWN_ACTIONS,
} from "@/lib/platform/intelligence/executive-command-center";
export type {
  CreateExecutiveCommandCenterOptions,
  ExecutiveCommandCenterStack,
  CommandCenterRequest,
  CommandCenterResult,
  WorkspaceWidget,
  CommandCenterRole,
} from "@/lib/platform/intelligence/executive-command-center";
export {
  createInitiativeIntelligence,
  INITIATIVE_INTELLIGENCE_VERSION,
  INITIATIVE_INTELLIGENCE_MODULE_ID,
  INITIATIVE_LIFECYCLE_STATES,
  INITIATIVE_OWNERSHIP_ROLES,
} from "@/lib/platform/intelligence/initiative-intelligence";
export type {
  CreateInitiativeIntelligenceOptions,
  InitiativeIntelligenceStack,
  InitiativeRequest,
  InitiativeResult,
  Initiative,
  InitiativeLifecycleState,
} from "@/lib/platform/intelligence/initiative-intelligence";
export {
  createPortfolioIntelligence,
  PORTFOLIO_INTELLIGENCE_VERSION,
  PORTFOLIO_INTELLIGENCE_MODULE_ID,
  PORTFOLIO_HEALTH_STATES,
} from "@/lib/platform/intelligence/portfolio-intelligence";
export type {
  CreatePortfolioIntelligenceOptions,
  PortfolioIntelligenceStack,
  PortfolioRequest,
  PortfolioResult,
  PortfolioHealth,
} from "@/lib/platform/intelligence/portfolio-intelligence";
export {
  createDigitalTwin,
  DIGITAL_TWIN_VERSION,
  DIGITAL_TWIN_MODULE_ID,
} from "@/lib/platform/intelligence/digital-twin";
export type {
  CreateDigitalTwinOptions,
  DigitalTwinStack,
  TwinRequest,
  TwinResult,
  SimulationState,
  ScenarioKind as DigitalTwinScenarioKind,
} from "@/lib/platform/intelligence/digital-twin";
export {
  createEcosystemFederation,
  ECOSYSTEM_FEDERATION_VERSION,
  ECOSYSTEM_INTELLIGENCE_MODULE_ID,
} from "@/lib/platform/intelligence/ecosystem-intelligence";
export type {
  CreateEcosystemFederationOptions,
  EcosystemFederationStack,
  EcosystemFederationRequest,
  EcosystemFederationResult,
} from "@/lib/platform/intelligence/ecosystem-intelligence";
export {
  INTELLIGENCE_PLATFORM_VERSION,
  createIntelligencePlatform,
  createIntelligenceRegistry,
  createIntelligencePipeline,
  createDefaultIntelligenceModules,
  IntelligenceRegistry,
  IntelligencePipeline,
  IntelligenceCache,
  IntelligenceMetrics,
  IntelligenceTelemetry,
  IntelligenceLifecycle,
  IntelligenceScheduler,
  IntelligenceConfiguration,
  IntelligenceHealth,
  IntelligenceDiagnostics,
  IntelligenceVersioning,
  IntelligenceEvents,
  IntelligenceProvider,
} from "@/lib/platform/intelligence/infrastructure";
export type {
  CreateIntelligencePlatformOptions,
  IntelligencePlatformStack,
  IntelligenceModule,
  IntelligenceExecutionRequest,
  IntelligencePipelineResult,
  IntelligencePlatformHealth,
  IntelligenceDiagnosticsReport,
} from "@/lib/platform/intelligence/infrastructure";
