/**
 * JAG Intelligence — Phase 1 foundation public API.
 *
 * Shared cognitive services for the autonomous intelligence layer.
 * See `docs/architecture/JAG_INTELLIGENCE_ARCHITECTURE.md`.
 */

export * from "@/lib/platform/intelligence/types";
export * from "@/lib/platform/intelligence/context";
export * from "@/lib/platform/intelligence/context/builder";
export * from "@/lib/platform/intelligence/context/cache";
export * from "@/lib/platform/intelligence/context/executive-context";
export * from "@/lib/platform/intelligence/context/finance-context";
export * from "@/lib/platform/intelligence/context/student-context";
export * from "@/lib/platform/intelligence/context/organization-context";
export * from "@/lib/platform/intelligence/memory";
export * from "@/lib/platform/intelligence/memory/index";
export * from "@/lib/platform/intelligence/reasoning";
export * from "@/lib/platform/intelligence/planner";
export * from "@/lib/platform/intelligence/execution";
export * from "@/lib/platform/intelligence/knowledge/foundation";
export * from "@/lib/platform/intelligence/confidence";
export * from "@/lib/platform/intelligence/learning";
export * from "@/lib/platform/intelligence/case-engine";
export * from "@/lib/platform/intelligence/events";
export * from "@/lib/platform/intelligence/explain";
export * from "@/lib/platform/intelligence/orchestrator";
export * from "@/lib/platform/intelligence/contracts";
export * from "@/lib/platform/intelligence/registry";
export * from "@/lib/platform/intelligence/router";
export * from "@/lib/platform/intelligence/service";
export * from "@/lib/platform/intelligence/create-service";
export * from "@/lib/platform/intelligence/domains/support";
export * from "@/lib/platform/intelligence/domains/executive";
export * from "@/lib/platform/intelligence/domains/strategic";
export * from "@/lib/platform/intelligence/decision";
export * from "@/lib/platform/intelligence/organization";
export {
  EXECUTIVE_GRAPH_ANALYZER_VERSION,
  createExecutiveGraphAnalyzer,
  GraphAnalyzer,
  GraphBuilder,
  GraphRepository,
  RootCauseAnalyzer,
  DependencyAnalyzer,
  CascadeAnalyzer,
  RiskPropagation,
  ExecutiveReasoner,
  OpportunityEngine,
  ConstraintEngine,
  CriticalityScore,
  ExecutivePriority as ExecutiveGraphPriorityRanker,
  ConfidenceScore as ExecutiveGraphConfidenceScorer,
  ExecutiveQueries,
  GraphSearch,
  DashboardProjection as ExecutiveGraphDashboardProjector,
} from "@/lib/platform/intelligence/executive-graph";
export type {
  CreateExecutiveGraphAnalyzerOptions,
  ExecutiveGraphAnalyzerStack,
  Graph as ExecutiveReasoningGraph,
  GraphNode as ExecutiveReasoningGraphNode,
  GraphEdge as ExecutiveReasoningGraphEdge,
  GraphAnalysisResult,
  GraphBuildInput,
} from "@/lib/platform/intelligence/executive-graph";
export {
  EXECUTIVE_DECISION_INTELLIGENCE_VERSION,
  createExecutiveDecisionIntelligence,
  createPresetScenario,
  DecisionEngine,
  ExecutiveDecisionService,
  ScenarioSimulator,
  RecommendationEngine,
  StrategyEngine,
  TradeoffAnalyzer,
  ImpactForecast,
  DecisionConfidence,
  DecisionHistory,
  ScenarioRepository,
  DecisionQueries,
  DecisionScoring,
  DecisionProjection,
  decisionModels,
} from "@/lib/platform/intelligence/executive-decision";
export type {
  CreateExecutiveDecisionOptions,
  ExecutiveDecisionStack,
  ExecutiveDecisionRequest,
  ExecutiveDecisionResult,
  ExecutiveDecisionRecommendation,
  DecisionScenarioDefinition,
  ScenarioSimulationResult,
  DecisionProjectionResult,
} from "@/lib/platform/intelligence/executive-decision";
export {
  PREDICTIVE_INTELLIGENCE_VERSION,
  createPredictiveIntelligence,
  createForecastScenario,
  PredictionEngine,
  PredictionService,
  ForecastEngine,
  TrendAnalyzer,
  ForecastRepository,
  ForecastQueries,
  ForecastProjection,
  PredictionConfidence,
  ForecastScoring,
  ForecastHistory,
  predictionModels,
} from "@/lib/platform/intelligence/predictive-intelligence";
export type {
  CreatePredictiveIntelligenceOptions,
  PredictiveIntelligenceStack,
  PredictionRequest,
  PredictionResult,
  ForecastScenarioDefinition,
  ForecastProjectionResult,
  ScenarioForecast,
  DomainForecast,
} from "@/lib/platform/intelligence/predictive-intelligence";
export {
  BOARD_GOVERNANCE_INTELLIGENCE_VERSION,
  createBoardGovernanceIntelligence,
  BoardIntelligenceEngine,
  GovernanceService,
  GovernanceEngine,
  BoardPacketGenerator,
  ExecutiveBriefGenerator,
  CommitteeReporting,
  StrategicInitiativeTracker,
  GovernanceDashboard,
  BoardKPIDashboard,
  RiskRegister,
  ComplianceMonitor,
  ExecutiveScorecards,
  ResolutionTracker,
  GovernanceCalendar,
  BoardQueries,
  GovernanceProjection,
  GovernanceRepository,
  governanceModels,
} from "@/lib/platform/intelligence/board-governance";
export type {
  CreateBoardGovernanceOptions,
  BoardGovernanceStack,
  GovernanceRequest,
  GovernanceResult,
  BoardPacket,
  BoardPacketKind,
  ExecutiveBrief,
  GovernanceDashboardView,
  BoardKpiDashboardView,
} from "@/lib/platform/intelligence/board-governance";
export {
  ORGANIZATION_DNA_VERSION,
  createOrganizationDnaIntelligence,
  OrganizationDnaEngine,
  OrganizationService,
  CompanyBuilder,
  OrganizationStageDetector,
  OrganizationLifecycle,
  BusinessModelEngine,
  BusinessPlanBuilder,
  LeanCanvasGenerator,
  SwotGenerator,
  ValuePropositionBuilder,
  CustomerPersonaBuilder,
  RevenueModelBuilder,
  FundingModelBuilder,
  GoToMarketPlanner,
  CompanyReadinessAssessmentEngine,
  ReadinessScoringEngine,
  ExecutiveRoadmapBuilder,
  OrganizationBlueprintBuilder,
  OrganizationDnaComposer,
  organizationDnaModels,
} from "@/lib/platform/intelligence/organization-dna";
export type {
  CreateOrganizationDnaOptions,
  OrganizationDnaStack,
  OrganizationDnaRequest,
  OrganizationDnaResult,
  OrganizationDNA,
  OrganizationProfile,
  CompanyBuilderSeed,
  OrganizationStage,
  CompanyBuilderArtifactKind,
} from "@/lib/platform/intelligence/organization-dna";
export {
  OIOS_VERSION,
  OIOS_INTELLIGENCE_DOMAINS,
  createOiosOperatingSystem,
  OrganizationOperatingSystem,
  OiosEngine,
  OiosService,
  IntelligenceDomainRegistry as OiosIntelligenceDomainRegistry,
  OrganizationalDigitalTwin,
  OrganizationalLifecycle,
  OrganizationalStateEngine,
  OrganizationalContext,
  OrganizationalMemory,
  OrganizationalKnowledgeGraph,
  OrganizationCapabilitiesRegistry,
  OrganizationImprovementEngine,
  ContinuousImprovementLoop,
  OrganizationalHealthIndex,
  OrganizationMaturityModel,
  OrganizationScorecard,
  OrganizationBenchmarking,
  OrganizationObjectives,
  OrganizationStrategy,
  OrganizationExecutionModel,
  OrganizationOperatingModel,
  OrganizationConfiguration,
  OrganizationPolicies,
  OrganizationStandards,
  OrganizationGovernanceModel,
  oiosModels,
} from "@/lib/platform/oios";
export type {
  CreateOiosOptions,
  OiosStack,
  OiosRequest,
  OiosResult,
  OiosIntelligenceDomain,
  DigitalTwinSnapshot,
  OrganizationalState,
  HealthIndex as OiosHealthIndex,
  MaturityAssessment,
  ImprovementCycle,
} from "@/lib/platform/oios";
export {
  HUMAN_CAPITAL_INTELLIGENCE_VERSION,
  createHumanCapitalIntelligence,
  HumanCapitalEngine,
  HumanCapitalService,
  WorkforceIntelligence,
  WorkforceRepository,
  HumanCapitalDashboard,
  CandidatePipeline,
  CandidateScoring,
  ResumeIntelligence,
  InterviewIntelligence,
  ReferenceIntelligence,
  HiringRecommendations,
  HiringRecommendationEngine,
  OfferOptimization,
  TalentSourcing,
  EmployerBrandingInsights,
  RecruitingAnalytics,
  EmployeeProfileEngine,
  SkillsInventory,
  CompetencyFramework,
  PerformanceEngine,
  GoalManagement,
  FeedbackEngine,
  CoachingEngine,
  RecognitionEngine,
  BehaviorInsights,
  ProductivityInsights,
  LeadershipAssessment,
  LeadershipDevelopment,
  SuccessionPlanning,
  TalentMatrix,
  OrganizationalDesign,
  ManagerEffectiveness,
  HighPotentialIdentification,
  LeadershipBenchStrength,
  BurnoutDetection,
  RetentionPrediction,
  EngagementAnalysis,
  StayInterviewInsights,
  ExitAnalysis,
  EmployeeSentiment,
  CultureHealth,
  LearningPlans,
  CareerPathing,
  CertificationTracking,
  MentorshipMatching,
  TrainingRecommendations,
  KnowledgeTransfer,
  DevelopmentRecommendations,
  SalaryBenchmarking,
  CompensationAnalysis,
  PayEquityAnalysis,
  BonusModeling,
  BenefitsAnalysis,
  IncentiveModeling,
  WorkforceForecast,
  CapacityPlanning,
  HiringForecast,
  OrganizationalScenarioPlanning,
  SkillsGapAnalysis,
  FutureWorkforceModel,
  HumanCapitalProjection,
  HumanCapitalQueries,
  ExecutiveWorkforceBriefGenerator,
  CareerPlanComposer,
  BurnoutRiskDashboard,
  OrganizationalCapabilityIndex,
  workforceModels,
} from "@/lib/platform/intelligence/human-capital";
export type {
  CreateHumanCapitalOptions,
  HumanCapitalStack,
  HumanCapitalRequest,
  HumanCapitalResult,
  HumanCapitalQueryRequest,
  HumanCapitalQueryResult,
  ExecutiveWorkforceBrief,
  HiringPriorityDashboard,
  SuccessionReadinessSummary,
  CareerDevelopmentPlan,
  HumanCapitalDashboardResult,
  BurnoutRiskDashboardResult,
  OrganizationalCapabilityIndexResult,
} from "@/lib/platform/intelligence/human-capital";
export {
  REVENUE_INTELLIGENCE_VERSION,
  createRevenueIntelligence,
  RevenueIntelligenceEngine,
  RevenueIntelligenceService,
  RevenueEngine,
  RevenueService,
  RevenueIntelligence,
  RevenueRepository,
  RevenueDashboard,
  RevenueHealth,
  RevenueStrategyEngine,
  RevenueMixAnalysis,
  RevenueDiversification,
  RecurringRevenueAnalysis,
  RevenueRiskAnalysis,
  RevenueOptimization,
  RevenueGrowthPlanner,
  RevenueForecasting,
  RevenueScenarioPlanning,
  PricingEngine,
  DynamicPricing,
  PriceElasticity,
  CompetitivePricing,
  DiscountOptimization,
  ScholarshipPricing,
  ContractPricing,
  SubscriptionPricing,
  OfferingAnalysis,
  ProductProfitability,
  ServiceProfitability,
  MarginAnalysis,
  LifecycleAnalysis,
  ExpansionRecommendations,
  RetirementRecommendations,
  CustomerLifetimeValue,
  RetentionRevenue,
  ExpansionRevenue,
  CrossSellEngine,
  UpsellEngine,
  CustomerProfitability,
  SegmentProfitability,
  PipelineForecast,
  WinRateAnalysis,
  SalesPerformance,
  SalesCapacity,
  TerritoryOptimization,
  ConversionAnalysis,
  MarketExpansion,
  CompetitorRevenue,
  DemandForecast,
  OpportunityScoring,
  GeographicExpansion,
  IndustryBenchmarks,
  GrossMarginAnalysis,
  NetMarginAnalysis,
  ContributionMargin,
  BreakEvenAnalysis,
  UnitEconomics,
  CashGenerationAnalysis,
  RevenueSensitivity,
  PricingDashboard,
  MarginDashboard,
  CustomerValueDashboard,
  ExecutiveRevenueBriefGenerator,
  RevenueProjection,
  RevenueQueries,
  revenueModels,
} from "@/lib/platform/intelligence/revenue";
export type {
  CreateRevenueOptions,
  RevenueStack,
  RevenueRequest,
  RevenueResult,
  RevenueQueryRequest,
  RevenueQueryResult,
  ExecutiveRevenueBrief,
  RevenueDashboardResult,
  PricingDashboardResult,
  MarginDashboardResult,
  CustomerValueDashboardResult,
  RevenueHealthResult,
} from "@/lib/platform/intelligence/revenue";
export {
  FUNDING_INTELLIGENCE_VERSION,
  createFundingIntelligence,
  FundingIntelligenceEngine,
  FundingIntelligenceService,
  FundingEngine,
  FundingService,
  FundingIntelligence,
  FundingRepository,
  FundingDashboard,
  FundingHealth,
  FundingStrategyEngine,
  FundingMixOptimization,
  FundingDiversification,
  FundingRiskAnalysis,
  FundingScenarioPlanning,
  CashRunwayOptimization,
  CapitalPlanning,
  FederalFunding,
  StateFunding,
  CountyFunding,
  CityFunding,
  EducationFunding,
  HealthcareFunding,
  InfrastructureFunding,
  EconomicDevelopmentFunding,
  DisasterFunding,
  ResearchFunding,
  GrantDiscovery,
  GrantMatching,
  GrantScoring,
  GrantCalendar,
  GrantForecasting,
  GrantRequirements,
  GrantCompliance,
  GrantReporting,
  GrantRenewals,
  GrantIntelligencePipeline,
  GovernmentContracts,
  CorporateContracts,
  RFPDiscovery,
  BidScoring,
  ProposalOptimization,
  ContractForecast,
  FoundationMatching,
  MajorDonorInsights,
  CorporateGiving,
  FamilyFoundations,
  CommunityFoundations,
  CapitalCampaignPlanning,
  AngelInvestors,
  VentureCapital,
  PrivateEquity,
  StrategicInvestors,
  DebtFinancing,
  RevenueBasedFinancing,
  Crowdfunding,
  Sponsorships,
  TaxCredits,
  TaxIncentives,
  OpportunityZones,
  NewMarketsTaxCredits,
  CarbonCredits,
  LicensingRevenue,
  RoyaltyRevenue,
  GrantPipelineDashboard,
  CapitalStrategyDashboard,
  FundingDiversificationDashboard,
  FundingRiskDashboard,
  FundingCalendarComposer,
  ExecutiveFundingBriefGenerator,
  FundingProjection,
  FundingQueries,
  fundingModels,
} from "@/lib/platform/intelligence/funding";
export type {
  CreateFundingOptions,
  FundingStack,
  FundingRequest,
  FundingResult,
  FundingQueryRequest,
  FundingQueryResult,
  ExecutiveFundingBrief,
  FundingDashboardResult,
  GrantPipelineDashboardResult,
  CapitalStrategyDashboardResult,
  FundingDiversificationDashboardResult,
  FundingRiskDashboardResult,
  FundingHealthResult,
} from "@/lib/platform/intelligence/funding";
export {
  OPPORTUNITY_INTELLIGENCE_VERSION,
  createOpportunityIntelligence,
  OpportunityIntelligenceEngine,
  OpportunityIntelligenceService,
  OpportunityService,
  OpportunityIntelligence,
  OpportunityRepository,
  OpportunityDashboard,
  OpportunityHealth,
  OpportunityModels,
  OpportunityCategoryEngine,
  OpportunityAnalysisEngine,
  OpportunityRankingEngine,
  OpportunityExchange,
  OpportunityRegistry,
  OpportunityScoring as OpportunityAnalysisScoring,
  ROIAnalysis,
  ImpactAnalysis,
  RiskAnalysis,
  ConfidenceScoring,
  DependencyAnalysis,
  ResourceRequirements,
  TimeToValueAnalysis,
  StrategicAlignment,
  RevenueOpportunities,
  FundingOpportunities,
  CostReductionOpportunities,
  PricingOpportunities,
  MarketExpansionOpportunities,
  GeographicExpansionOpportunities,
  CustomerGrowthOpportunities,
  RetentionOpportunities,
  PartnershipOpportunities,
  StrategicAllianceOpportunities,
  AcquisitionOpportunities,
  MergerOpportunities,
  TechnologyOpportunities,
  AutomationOpportunities,
  VendorOptimizationOpportunities,
  ProcurementSavingsOpportunities,
  RealEstateOpportunities,
  AssetOptimizationOpportunities,
  LicensingOpportunities,
  IntellectualPropertyOpportunities,
  InnovationOpportunities,
  MissionImpactOpportunities,
  TopOpportunitiesDashboard,
  QuickWinsDashboard,
  StrategicInvestmentDashboard,
  MissionOpportunityDashboard,
  OpportunityHeatMap,
  OpportunityPipelineComposer,
  ExecutiveOpportunityBriefGenerator,
  OpportunityProjection,
  OpportunityQueries,
  opportunityModels,
} from "@/lib/platform/intelligence/opportunity";
export type {
  CreateOpportunityOptions,
  OpportunityStack,
  OpportunityRequest,
  OpportunityResult,
  OpportunityQueryRequest,
  OpportunityQueryResult,
  ExecutiveOpportunityBrief,
  OpportunityDashboardResult,
  TopOpportunitiesDashboardResult,
  QuickWinsDashboardResult,
  StrategicInvestmentDashboardResult,
  MissionOpportunityDashboardResult,
  OpportunityHealthResult,
  OpportunityExchangeRecord,
  OpportunityLensImpact,
} from "@/lib/platform/intelligence/opportunity";
export {
  IMPROVEMENT_INTELLIGENCE_VERSION,
  createOrganizationalImprovementIntelligence,
  OrganizationalImprovementEngine,
  ImprovementIntelligenceService,
  ImprovementService,
  ImprovementIntelligence,
  ImprovementRepository,
  ImprovementDashboard,
  ImprovementHealth,
  ImprovementModels,
  ImprovementSourceEngine,
  ImprovementAnalysisEngine,
  ImprovementPlanner,
  ImprovementRegistry,
  PriorityScoring,
  ImpactScoring,
  MissionAlignmentAnalysis,
  FinancialImpactAnalysis,
  RiskReductionAnalysis,
  TimeToValueAnalysis as ImprovementTimeToValueAnalysis,
  ResourceRequirementsAnalysis,
  OrganizationalCapacityAnalysis,
  DependencyResolution,
  ImprovementConfidenceAnalysis,
  QuickWinsPlanner,
  StrategicInitiativesPlanner,
  LongTermTransformationPlanner,
  WeeklyPlanComposer,
  MonthlyPlanComposer,
  QuarterlyPlanComposer,
  AnnualRoadmapComposer,
  ContinuousImprovementLoop as OrganizationalContinuousImprovementLoop,
  MissionImprovementDashboard,
  FinancialImprovementDashboard,
  PeopleImprovementDashboard,
  TodaysPrioritiesComposer,
  ImprovementHeatMap,
  DailyExecutiveBriefGenerator,
  ExecutiveImprovementBriefGenerator,
  ImprovementProjection,
  ImprovementQueries,
  improvementModels,
} from "@/lib/platform/intelligence/organizational-improvement";
export type {
  CreateImprovementOptions,
  ImprovementStack,
  ImprovementRequest,
  ImprovementResult,
  ImprovementQueryRequest,
  ImprovementQueryResult,
  DailyExecutiveBrief,
  ExecutiveImprovementBrief,
  ImprovementDashboardResult,
  MissionImprovementDashboardResult,
  FinancialImprovementDashboardResult,
  PeopleImprovementDashboardResult,
  ImprovementHealthResult,
  ImprovementRecord,
  ImprovementLensImpact,
  ContinuousImprovementLoopResult,
} from "@/lib/platform/intelligence/organizational-improvement";
export {
  BUSINESS_MODEL_INTELLIGENCE_VERSION,
  createBusinessModelIntelligence,
  BusinessModelIntelligenceEngine,
  BusinessModelIntelligenceService,
  BusinessModelService,
  BusinessModelIntelligence,
  BusinessModelRepository,
  BusinessModelDashboard,
  BusinessModelHealth,
  BusinessModelModels,
  BusinessModelRegistry,
  BusinessModelSimulator,
  BusinessModelCanvasBuilder,
  LeanCanvasBuilder,
  OrganizationDesignEngine,
  BusinessModelScenarioPlanner,
  CompetitivePositionAnalyzer,
  BusinessModelRiskAnalyzer,
  BusinessModelOpportunityAnalyzer,
  BusinessModelEvolutionPlanner,
  BusinessModelRecommendationComposer,
  ExecutiveBusinessBriefGenerator,
  BusinessModelProjection,
  BusinessModelQueries,
  businessModelModels,
} from "@/lib/platform/intelligence/business-model";
export type {
  CreateBusinessModelOptions,
  BusinessModelStack,
  BusinessModelRequest,
  BusinessModelResult,
  BusinessModelQueryRequest,
  BusinessModelQueryResult,
  ExecutiveBusinessBrief,
  BusinessModelDashboardResult,
  BusinessModelHealthResult,
  BusinessModelCanvasResult,
  LeanCanvasResult,
  BusinessModelLensImpact,
  OrganizationDesignSuite,
  BusinessModelScenarioSuite,
  BusinessModelComparisonResult,
} from "@/lib/platform/intelligence/business-model";
export {
  OPERATIONS_INTELLIGENCE_VERSION,
  createOperationsIntelligence,
  OperationsIntelligenceEngine,
  OperationsIntelligenceService,
  OperationsService,
  OperationsIntelligence,
  OperationsRepository,
  OperationsDashboard,
  OperationsHealth,
  OperationsModels,
  OperationsRegistry,
  WorkflowHealthEngine,
  ProcessMonitoringEngine,
  StaffingAnalyticsEngine,
  CapacityPlanner,
  ResourceUtilizationAnalyzer,
  AutomationOpportunityEngine,
  OperationsRiskAnalyzer,
  OperationsOpportunityAnalyzer,
  OperationsRecommendationComposer,
  ExecutiveOperationsBriefGenerator,
  OperationsProjection,
  OperationsQueries,
  operationsModels,
  WORKFLOW_HEALTH_DIMENSIONS,
  PROCESS_MONITORING_AREAS,
  AUTOMATION_OPPORTUNITY_KINDS,
  CAPACITY_PLANNING_HORIZONS,
} from "@/lib/platform/intelligence/operations";
export type {
  CreateOperationsOptions,
  OperationsStack,
  OperationsRequest,
  OperationsResult,
  OperationsQueryRequest,
  OperationsQueryResult,
  ExecutiveOperationsBrief,
  OperationsDashboardResult,
  OperationsHealthResult,
  OperationsLensImpact,
  WorkflowHealthResult,
  ProcessMonitoringSuite,
  StaffingAnalyticsResult,
  CapacityPlanResult,
  AutomationOpportunitySuite,
  ResourceUtilizationResult,
} from "@/lib/platform/intelligence/operations";
export {
  CUSTOMER_INTELLIGENCE_VERSION,
  createCustomerIntelligence,
  CustomerIntelligenceEngine,
  CustomerIntelligenceService,
  CustomerService,
  CustomerIntelligence,
  CustomerRepository,
  CustomerDashboard,
  CustomerHealth,
  CustomerModels,
  CustomerRegistry,
  JourneyMapEngine,
  EngagementEngine,
  SatisfactionEngine,
  RetentionRiskEngine,
  CommunityBelongingEngine,
  CustomerRiskAnalyzer,
  CustomerOpportunityAnalyzer,
  CustomerRecommendationComposer,
  ExecutiveCustomerBriefGenerator,
  CustomerProjection,
  CustomerQueries,
  customerModels,
  JOURNEY_STAGES,
  ENGAGEMENT_DIMENSIONS,
  SATISFACTION_SIGNALS,
  RETENTION_RISK_FACTORS,
  COMMUNITY_BELONGING_PILLARS,
} from "@/lib/platform/intelligence/customer";
export type {
  CreateCustomerOptions,
  CustomerStack,
  CustomerRequest,
  CustomerResult,
  CustomerQueryRequest,
  CustomerQueryResult,
  ExecutiveCustomerBrief,
  CustomerDashboardResult,
  CustomerHealthResult,
  CustomerLensImpact,
  JourneyMapResult,
  EngagementResult,
  SatisfactionSuite,
  RetentionWatchlistResult,
  CommunityHealthResult,
} from "@/lib/platform/intelligence/customer";
export {
  KNOWLEDGE_INTELLIGENCE_VERSION,
  createKnowledgeIntelligence,
  KnowledgeIntelligenceEngine,
  KnowledgeIntelligenceService,
  KnowledgeService,
  KnowledgeIntelligence,
  KnowledgeRepository,
  KnowledgeDashboard,
  KnowledgeHealth,
  KnowledgeModels,
  KnowledgeRegistry,
  KnowledgeCaptureEngine,
  KnowledgeGraphEngine,
  KnowledgeSearchEngine,
  KnowledgeReasoner,
  KnowledgeGapEngine,
  ExpertiseMapEngine,
  KnowledgeProvenanceEngine,
  KnowledgeQualityEngine,
  KnowledgeValidation,
  KnowledgeFreshness,
  KnowledgeCompleteness,
  KnowledgeAccuracy,
  KnowledgeConsistency,
  KnowledgeConflictDetection,
  KnowledgeRedundancyDetection,
  KnowledgeCoverageAnalysis,
  KnowledgeLifecycleManagement,
  OrganizationalMemoryEngine,
  KnowledgeEvolutionEngine,
  DecisionTraceabilityEngine,
  KnowledgeRiskAnalyzer,
  KnowledgeOpportunityAnalyzer,
  KnowledgeRecommendationComposer,
  ExecutiveKnowledgeBriefGenerator,
  KnowledgeProjection,
  KnowledgeQueries,
  knowledgeModels,
  KNOWLEDGE_TYPES,
  KNOWLEDGE_SOURCES,
  KNOWLEDGE_SOURCE_TYPES,
  KNOWLEDGE_RELATION_KINDS,
  KNOWLEDGE_GAP_CATEGORIES,
  KNOWLEDGE_QUALITY_DIMENSIONS,
  KNOWLEDGE_EVOLUTION_ACTIONS,
  KNOWLEDGE_APPROVAL_STATUSES,
  ORGANIZATIONAL_MEMORY_KINDS,
  EXPERTISE_DOMAINS,
} from "@/lib/platform/intelligence/knowledge";
export type {
  CreateKnowledgeOptions,
  KnowledgeStack,
  KnowledgeRequest,
  KnowledgeResult,
  KnowledgeQueryRequest,
  KnowledgeQueryResult,
  ExecutiveKnowledgeBrief,
  KnowledgeDashboardResult,
  KnowledgeHealthResult,
  KnowledgeLensImpact,
  KnowledgeCatalogResult,
  KnowledgeGraphResult,
  KnowledgeSearchResult,
  KnowledgeReasoningResult,
  KnowledgeGapResult,
  ExpertiseMapResult,
  KnowledgeProvenanceSuite,
  KnowledgeQualitySuite,
  OrganizationalMemorySuite,
  KnowledgeEvolutionResult,
  DecisionTraceabilityResult,
  KnowledgeRecommendationRecord,
} from "@/lib/platform/intelligence/knowledge";
export {
  DOCUMENT_INTELLIGENCE_VERSION,
  createDocumentIntelligence,
  DocumentIntelligenceEngine,
  DocumentIntelligenceService,
  DocumentService,
  DocumentIntelligence,
  DocumentRepository,
  DocumentDashboard,
  DocumentHealth,
  DocumentModels,
  DocumentRegistry,
  DocumentParser,
  DocumentClassifier,
  DocumentMetadataIntelligence,
  DocumentEntityRelationshipIntelligence,
  DocumentVersionDuplicateIntelligence,
  DocumentSummarizationClauseIntelligence,
  DocumentRiskComplianceIntelligence,
  DocumentExpirationIntelligence,
  DocumentKnowledgeContributionEngine,
  DocumentReasoner,
  DocumentRiskAnalyzer,
  DocumentOpportunityAnalyzer,
  DocumentRecommendationComposer,
  ExecutiveDocumentBriefGenerator,
  DocumentProjection,
  DocumentQueries,
  DocumentSpecializedDashboards,
  documentModels,
  DOCUMENT_TYPES,
  DOCUMENT_CAPABILITIES,
  DOCUMENT_RELATION_KINDS,
  DOCUMENT_RISK_CATEGORIES,
  DOCUMENT_COMPLIANCE_TAGS,
  DOCUMENT_ARTIFACT_STATUSES,
} from "@/lib/platform/intelligence/document";
export type {
  CreateDocumentOptions,
  DocumentStack,
  DocumentRequest,
  DocumentResult,
  DocumentQueryRequest,
  DocumentQueryResult,
  ExecutiveDocumentBrief,
  DocumentDashboardResult,
  DocumentHealthResult,
  DocumentLensImpact,
  DocumentCatalogResult,
  DocumentKnowledgeContribution,
  DocumentRecommendationRecord,
  ContractDashboardResult,
  PolicyDashboardResult,
  GrantDashboardResult,
  ComplianceDashboardResult,
} from "@/lib/platform/intelligence/document";
export {
  LEGAL_COMPLIANCE_RISK_INTELLIGENCE_VERSION,
  createLegalComplianceRiskIntelligence,
  LegalComplianceRiskIntelligenceEngine,
  LegalComplianceRiskIntelligenceService,
  LegalComplianceRiskService,
  LegalComplianceRiskIntelligence,
  LegalComplianceRiskRepository,
  LegalComplianceRiskDashboard,
  LegalComplianceRiskHealth,
  LegalComplianceRiskModels,
  LegalComplianceRiskRegistry,
  LegalComplianceRiskReasoner,
  LegalComplianceRiskKnowledgeContributionEngine,
  LegalComplianceRiskSpecializedDashboards,
  LegalComplianceRiskRiskAnalyzer,
  LegalComplianceRiskOpportunityAnalyzer,
  LegalComplianceRiskRecommendationComposer,
  CorrectiveActionPlanner,
  ExecutiveRiskBriefGenerator,
  BoardComplianceBriefGenerator,
  LegalComplianceRiskProjection,
  LegalComplianceRiskQueries,
  ContractIntelligence,
  RegulatoryIntelligence,
  ComplianceIntelligence,
  EnterpriseRiskIntelligence,
  PolicyIntelligence,
  AuditIntelligence,
  LicensePermitIntelligence,
  InsuranceIntelligence,
  LitigationIntelligence,
  VendorThirdPartyRiskIntelligence,
  CyberGovernanceIntelligence,
  legalComplianceRiskModels,
  RISK_CATEGORIES,
  COMPLIANCE_SCOPES,
  LEGAL_COMPLIANCE_RISK_CAPABILITIES,
} from "@/lib/platform/intelligence/legal-compliance-risk";
export type {
  CreateLegalComplianceRiskOptions,
  LegalComplianceRiskStack,
  LegalComplianceRiskRequest,
  LegalComplianceRiskResult,
  LegalComplianceRiskQueryRequest,
  LegalComplianceRiskQueryResult,
  ExecutiveRiskBrief,
  BoardComplianceBrief,
  LegalComplianceRiskDashboardResult,
  EnterpriseRiskDashboardResult,
  ComplianceDashboardResult as LegalComplianceRiskComplianceDashboardResult,
  ContractDashboardResult as LegalComplianceRiskContractDashboardResult,
  AuditDashboardResult,
  CorrectiveActionPlanResult,
  LegalComplianceRiskHealthResult,
  LegalComplianceRiskLens,
  LegalComplianceRiskRecommendationRecord,
  RiskCategory,
  ComplianceScope,
} from "@/lib/platform/intelligence/legal-compliance-risk";
export {
  MARKET_INTELLIGENCE_VERSION,
  createMarketIntelligence,
  MarketIntelligenceEngine,
  MarketIntelligenceService,
  MarketService,
  MarketIntelligence,
  MarketRepository,
  MarketDashboard,
  MarketHealth,
  MarketModels,
  MarketRegistry,
  MarketReasoner,
  MarketKnowledgeContributionEngine,
  MarketSpecializedDashboards,
  MarketRiskAnalyzer,
  MarketOpportunityAnalyzer,
  MarketRecommendationComposer,
  ExecutiveMarketBriefGenerator,
  MarketProjection,
  MarketQueries,
  IndustryIntelligence,
  CompetitiveIntelligence,
  MarketSizeIntelligence,
  PricingIntelligence,
  CustomerDemandIntelligence,
  DemographicIntelligence,
  GeographicExpansionIntelligence,
  EconomicTrendIntelligence,
  TechnologyTrendIntelligence,
  PartnershipIntelligence,
  MergersAcquisitionsIntelligence,
  WhiteSpaceIntelligence,
  marketModels,
  MARKET_CAPABILITIES,
  MARKET_SIGNAL_KINDS,
} from "@/lib/platform/intelligence/market";
export type {
  CreateMarketOptions,
  MarketStack,
  MarketRequest,
  MarketResult,
  MarketQueryRequest,
  MarketQueryResult,
  ExecutiveMarketBrief,
  MarketDashboardResult,
  CompetitiveDashboardResult,
  ExpansionDashboardResult,
  TrendDashboardResult,
  MarketHealthResult,
  MarketLens,
  MarketRecommendationRecord,
  MarketSignalKind,
} from "@/lib/platform/intelligence/market";
export {
  INTELLIGENCE_PLATFORM_VERSION,
  createIntelligencePlatform,
  createIntelligenceRegistry,
  createIntelligencePipeline,
  createDefaultIntelligenceModules,
  IntelligenceRegistry,
  IntelligencePipeline,
  IntelligenceCache,
  IntelligenceMetrics,
  IntelligenceTelemetry,
  IntelligenceLifecycle,
  IntelligenceScheduler,
  IntelligenceConfiguration,
  IntelligenceHealth,
  IntelligenceDiagnostics,
  IntelligenceVersioning,
  IntelligenceEvents,
  IntelligenceProvider,
} from "@/lib/platform/intelligence/infrastructure";
export type {
  CreateIntelligencePlatformOptions,
  IntelligencePlatformStack,
  IntelligenceModule,
  IntelligenceExecutionRequest,
  IntelligencePipelineResult,
  IntelligencePlatformHealth,
  IntelligenceDiagnosticsReport,
} from "@/lib/platform/intelligence/infrastructure";
