export {
  ACADEMY_SCHEDULING_REPORTS,
  ACADEMY_SCHEDULING_REPORT_IDS,
  getAcademySchedulingReport,
  listAcademySchedulingReports,
  registerAcademySchedulingReports,
  resetAcademySchedulingReportsForTests,
  registerAcademySchedulingPermissionPack,
  getAcademySchedulingPermissionPack,
  registerAcademySchedulingProgramCatalog,
  listRegisteredAcademySchedulingPrograms,
  registerAcademySchedulingCalendarCatalog,
  listRegisteredAcademySchedulingCalendars,
  registerAcademySchedulingConstraints,
  listRegisteredAcademySchedulingConstraints,
  type AcademySchedulingReportDefinition,
} from "@/packages/academy/scheduling/reports/definitions";
