import type {
  GraphEdgeDefinition,
  GraphNodeDefinition,
} from "@/lib/platform/intelligence-graph/types";

/** JAG domain graph node types — reference-only nodes backed by persisted graph edges. */
export const JAG_LEARNING_NODE_DEFINITIONS: GraphNodeDefinition[] = [
  {
    nodeType: "student",
    name: "Student",
    domain: "learning",
    providerKey: "relationship",
    entityTypes: ["student"],
    status: "active",
    sortOrder: 100,
  },
  {
    nodeType: "parent",
    name: "Parent / Guardian",
    domain: "learning",
    providerKey: "relationship",
    entityTypes: ["family", "guardian"],
    status: "active",
    sortOrder: 110,
  },
  {
    nodeType: "teacher",
    name: "Teacher",
    domain: "learning",
    providerKey: "relationship",
    entityTypes: ["employee"],
    status: "active",
    sortOrder: 120,
  },
  {
    nodeType: "staff",
    name: "Staff",
    domain: "learning",
    providerKey: "relationship",
    entityTypes: ["employee"],
    status: "active",
    sortOrder: 130,
  },
  {
    nodeType: "school",
    name: "School",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["school"],
    status: "active",
    sortOrder: 140,
  },
  {
    nodeType: "class",
    name: "Class",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["class"],
    status: "active",
    sortOrder: 150,
  },
  {
    nodeType: "learning_domain",
    name: "Learning Domain",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["learning_domain"],
    status: "active",
    sortOrder: 160,
  },
  {
    nodeType: "competency",
    name: "Competency",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["competency"],
    status: "active",
    sortOrder: 170,
  },
  {
    nodeType: "atomic_skill",
    name: "Atomic Skill",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["atomic_skill"],
    status: "active",
    sortOrder: 180,
  },
  {
    nodeType: "evidence",
    name: "Evidence",
    domain: "learning",
    providerKey: "evidence",
    entityTypes: ["evidence_record"],
    status: "active",
    sortOrder: 190,
  },
  {
    nodeType: "assessment",
    name: "Assessment",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["assessment"],
    status: "active",
    sortOrder: 200,
  },
  {
    nodeType: "accommodation",
    name: "Accommodation",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["accommodation"],
    status: "active",
    sortOrder: 210,
  },
  {
    nodeType: "rule_evaluation",
    name: "Rule Evaluation",
    domain: "learning",
    providerKey: "rules",
    entityTypes: ["rule_evaluation"],
    status: "active",
    sortOrder: 220,
  },
  {
    nodeType: "decision_record",
    name: "Decision Record",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["decision_record"],
    status: "active",
    sortOrder: 230,
  },
  {
    nodeType: "learning_journey",
    name: "Learning Journey",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["learning_journey"],
    status: "active",
    sortOrder: 240,
  },
  {
    nodeType: "schedule",
    name: "Schedule",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["schedule"],
    status: "active",
    sortOrder: 250,
  },
  {
    nodeType: "scholarship",
    name: "Scholarship",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["scholarship"],
    status: "active",
    sortOrder: 260,
  },
  {
    nodeType: "opportunity",
    name: "Opportunity",
    domain: "learning",
    providerKey: "persisted",
    entityTypes: ["opportunity"],
    status: "active",
    sortOrder: 270,
  },
];

/** JAG domain graph edge types — persisted canonical relationships. */
export const JAG_LEARNING_EDGE_DEFINITIONS: GraphEdgeDefinition[] = [
  {
    edgeType: "student.enrolled_in.journey",
    name: "Student Enrolled In Journey",
    domain: "learning",
    providerKey: "persisted",
    sourceNodeTypes: ["student", "entity"],
    targetNodeTypes: ["learning_journey"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 105,
  },
  {
    edgeType: "learning_journey.enrolled_in.domain",
    name: "Learning Journey Enrolled In Domain",
    domain: "learning",
    providerKey: "persisted",
    sourceNodeTypes: ["learning_journey"],
    targetNodeTypes: ["learning_domain"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 106,
  },
  {
    edgeType: "student.enrolled_in.class",
    name: "Student Enrolled In Class",
    domain: "learning",
    providerKey: "persisted",
    sourceNodeTypes: ["student", "entity"],
    targetNodeTypes: ["class"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 100,
  },
  {
    edgeType: "student.demonstrates.competency",
    name: "Student Demonstrates Competency",
    domain: "learning",
    providerKey: "evidence",
    sourceNodeTypes: ["student", "entity"],
    targetNodeTypes: ["competency"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 110,
  },
  {
    edgeType: "competency.supported_by.evidence",
    name: "Competency Supported By Evidence",
    domain: "learning",
    providerKey: "evidence",
    sourceNodeTypes: ["competency"],
    targetNodeTypes: ["evidence"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 120,
  },
  {
    edgeType: "teacher.teaches.class",
    name: "Teacher Teaches Class",
    domain: "learning",
    providerKey: "persisted",
    sourceNodeTypes: ["teacher", "entity"],
    targetNodeTypes: ["class"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 130,
  },
  {
    edgeType: "rule.evaluated_for.entity",
    name: "Rule Evaluated For Entity",
    domain: "learning",
    providerKey: "rules",
    sourceNodeTypes: ["rule_evaluation"],
    targetNodeTypes: ["student", "entity"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 135,
  },
  {
    edgeType: "rule.evaluated_during.decision",
    name: "Rule Evaluated During Decision",
    domain: "learning",
    providerKey: "rules",
    sourceNodeTypes: ["rule_evaluation"],
    targetNodeTypes: ["decision_record", "decision_execution"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 140,
  },
  {
    edgeType: "decision.references.evidence",
    name: "Decision References Evidence",
    domain: "learning",
    providerKey: "persisted",
    sourceNodeTypes: ["decision_record"],
    targetNodeTypes: ["evidence"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 150,
  },
  {
    edgeType: "learning_journey.contains.competency",
    name: "Learning Journey Contains Competency",
    domain: "learning",
    providerKey: "persisted",
    sourceNodeTypes: ["learning_journey"],
    targetNodeTypes: ["competency"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 160,
  },
  {
    edgeType: "assessment.measures.competency",
    name: "Assessment Measures Competency",
    domain: "learning",
    providerKey: "persisted",
    sourceNodeTypes: ["assessment"],
    targetNodeTypes: ["competency"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 170,
  },
  {
    edgeType: "atomic_skill.part_of.competency",
    name: "Atomic Skill Part Of Competency",
    domain: "learning",
    providerKey: "persisted",
    sourceNodeTypes: ["atomic_skill"],
    targetNodeTypes: ["competency"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 180,
  },
  {
    edgeType: "student.has.accommodation",
    name: "Student Has Accommodation",
    domain: "learning",
    providerKey: "persisted",
    sourceNodeTypes: ["student", "entity"],
    targetNodeTypes: ["accommodation"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 190,
  },
];
