import type {
  GraphEdgeDefinition,
  GraphNodeDefinition,
} from "@/lib/platform/intelligence-graph/types";

/**
 * Reference node type definitions — canonical graph node types backed by platform providers.
 * Domain modules register additional node types; these are platform-wide templates.
 */
export const PLATFORM_REFERENCE_NODE_DEFINITIONS: GraphNodeDefinition[] = [
  {
    nodeType: "entity",
    name: "Platform Entity",
    description: "Core platform entity node derived from shared entity types",
    domain: "platform",
    providerKey: "relationship",
    entityTypes: ["*"],
    status: "active",
    sortOrder: 10,
  },
  {
    nodeType: "activity_event",
    name: "Activity Event",
    description: "Activity Engine audit event linked to an entity",
    domain: "platform",
    providerKey: "activity",
    entityTypes: ["activity_event"],
    status: "active",
    sortOrder: 20,
  },
  {
    nodeType: "platform_event",
    name: "Platform Event",
    description: "Event Engine envelope referencing a platform entity",
    domain: "platform",
    providerKey: "event",
    entityTypes: ["platform_event"],
    status: "active",
    sortOrder: 30,
  },
  {
    nodeType: "workflow_instance",
    name: "Workflow Instance",
    description: "Workflow Engine instance bound to an entity",
    domain: "platform",
    providerKey: "workflow",
    entityTypes: ["workflow_instance"],
    status: "active",
    sortOrder: 40,
  },
  {
    nodeType: "decision_execution",
    name: "Decision Execution",
    description: "Decision Engine execution targeting an entity",
    domain: "platform",
    providerKey: "decision",
    entityTypes: ["decision_execution"],
    status: "active",
    sortOrder: 50,
  },
  {
    nodeType: "note",
    name: "Platform Note",
    description: "Notes Engine note attached to an entity",
    domain: "platform",
    providerKey: "notes",
    entityTypes: ["note"],
    status: "active",
    sortOrder: 60,
  },
  {
    nodeType: "tag",
    name: "Platform Tag",
    description: "Tag Engine tag applied to an entity",
    domain: "platform",
    providerKey: "tag",
    entityTypes: ["tag"],
    status: "active",
    sortOrder: 70,
  },
  {
    nodeType: "profile",
    name: "Platform Profile",
    description: "Platform Profile workspace for an entity kind",
    domain: "platform",
    providerKey: "profile",
    entityTypes: ["student", "employee", "family", "admissions_lead"],
    status: "active",
    sortOrder: 80,
  },
];

/**
 * Reference edge type definitions — canonical graph edge types sourced from platform providers.
 */
export const PLATFORM_REFERENCE_EDGE_DEFINITIONS: GraphEdgeDefinition[] = [
  {
    edgeType: "relationship",
    name: "Platform Relationship",
    description: "Entity-to-entity relationship from the Relationship Engine",
    domain: "platform",
    providerKey: "relationship",
    sourceNodeTypes: ["entity"],
    targetNodeTypes: ["entity"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 10,
  },
  {
    edgeType: "activity.linked_to",
    name: "Activity Linked To Entity",
    description: "Activity event linked to its subject entity",
    domain: "platform",
    providerKey: "activity",
    sourceNodeTypes: ["activity_event"],
    targetNodeTypes: ["entity"],
    direction: "directed",
    defaultWeight: 0.5,
    status: "active",
    sortOrder: 20,
  },
  {
    edgeType: "event.references",
    name: "Event References Entity",
    description: "Platform event envelope referencing an entity",
    domain: "platform",
    providerKey: "event",
    sourceNodeTypes: ["platform_event"],
    targetNodeTypes: ["entity"],
    direction: "directed",
    defaultWeight: 0.5,
    status: "active",
    sortOrder: 30,
  },
  {
    edgeType: "workflow.assigned_to",
    name: "Workflow Assigned To Entity",
    description: "Workflow instance assigned to a platform entity",
    domain: "platform",
    providerKey: "workflow",
    sourceNodeTypes: ["workflow_instance"],
    targetNodeTypes: ["entity"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 40,
  },
  {
    edgeType: "decision.targets",
    name: "Decision Targets Entity",
    description: "Decision execution targeting a platform entity",
    domain: "platform",
    providerKey: "decision",
    sourceNodeTypes: ["decision_execution"],
    targetNodeTypes: ["entity"],
    direction: "directed",
    defaultWeight: 1,
    status: "active",
    sortOrder: 50,
  },
  {
    edgeType: "note.attached_to",
    name: "Note Attached To Entity",
    description: "Note attached to its subject entity",
    domain: "platform",
    providerKey: "notes",
    sourceNodeTypes: ["note"],
    targetNodeTypes: ["entity"],
    direction: "directed",
    defaultWeight: 0.25,
    status: "active",
    sortOrder: 60,
  },
  {
    edgeType: "tag.applied_to",
    name: "Tag Applied To Entity",
    description: "Tag applied to a platform entity",
    domain: "platform",
    providerKey: "tag",
    sourceNodeTypes: ["tag"],
    targetNodeTypes: ["entity"],
    direction: "directed",
    defaultWeight: 0.25,
    status: "active",
    sortOrder: 70,
  },
  {
    edgeType: "profile.sections",
    name: "Profile Section Link",
    description: "Profile workspace section linked to its entity profile",
    domain: "platform",
    providerKey: "profile",
    sourceNodeTypes: ["profile"],
    targetNodeTypes: ["entity"],
    direction: "directed",
    defaultWeight: 0.5,
    status: "active",
    sortOrder: 80,
  },
];

/** Canonical node catalog export — alias for registry entries at build time. */
export const PLATFORM_GRAPH_NODE_CATALOG = PLATFORM_REFERENCE_NODE_DEFINITIONS;

/** Canonical edge catalog export — alias for registry entries at build time. */
export const PLATFORM_GRAPH_EDGE_CATALOG = PLATFORM_REFERENCE_EDGE_DEFINITIONS;
