import type { UlrStrand } from "@/lib/platform/ulr/types";
import { PA_DOMAIN_KEY } from "@/lib/platform/ulr/catalog/structured-literacy/shared-defaults";

/** Document 13 — all thirteen Structured Literacy strands. */
export const SL_STRANDS: UlrStrand[] = [
  {
    strandKey: "domain.structured_literacy.strand.phonological_awareness",
    domainKey: PA_DOMAIN_KEY,
    title: "Phonological Awareness",
    description: "Sound structure of spoken language — word, syllable, onset-rime (Doc 13)",
    version: "1.0.0",
    status: "published",
    sortOrder: 10,
    metadata: { documentRef: "DOCUMENT-13", populated: true },
  },
  {
    strandKey: "domain.structured_literacy.strand.phonemic_awareness",
    domainKey: PA_DOMAIN_KEY,
    title: "Phonemic Awareness",
    description: "Phoneme-level manipulation (Doc 13 · Doc 62 concept library)",
    version: "1.0.0",
    status: "published",
    sortOrder: 20,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.alphabetic_principle",
    domainKey: PA_DOMAIN_KEY,
    title: "Alphabetic Principle",
    description: "Sound-symbol correspondence foundation (Doc 13 · Doc 84)",
    version: "1.0.0",
    status: "published",
    sortOrder: 30,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.decoding",
    domainKey: PA_DOMAIN_KEY,
    title: "Decoding",
    description: "Word reading accuracy (Doc 13 · Doc 86)",
    version: "1.0.0",
    status: "published",
    sortOrder: 40,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.encoding",
    domainKey: PA_DOMAIN_KEY,
    title: "Encoding & Spelling",
    description: "Spelling and written encoding (Doc 13 · Doc 87)",
    version: "1.0.0",
    status: "published",
    sortOrder: 50,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.orthographic_mapping",
    domainKey: PA_DOMAIN_KEY,
    title: "Orthographic Mapping",
    description: "Sight word storage and orthographic mapping (Doc 13 · Doc 88)",
    version: "1.0.0",
    status: "published",
    sortOrder: 60,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.morphology",
    domainKey: PA_DOMAIN_KEY,
    title: "Morphology",
    description: "Prefixes, suffixes, roots (Doc 13 · Doc 89)",
    version: "1.0.0",
    status: "published",
    sortOrder: 70,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.fluency",
    domainKey: PA_DOMAIN_KEY,
    title: "Fluency",
    description: "Accurate, automatic, expressive reading (Doc 13 · Doc 90)",
    version: "1.0.0",
    status: "published",
    sortOrder: 80,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.vocabulary",
    domainKey: PA_DOMAIN_KEY,
    title: "Vocabulary",
    description: "Word meaning and usage (Doc 13 · Doc 91)",
    version: "1.0.0",
    status: "published",
    sortOrder: 90,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.comprehension",
    domainKey: PA_DOMAIN_KEY,
    title: "Comprehension",
    description: "Text understanding (Doc 13 · Doc 93)",
    version: "1.0.0",
    status: "published",
    sortOrder: 100,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.writing_connections",
    domainKey: PA_DOMAIN_KEY,
    title: "Writing Connections",
    description: "Literacy writing integration (Doc 13 · Doc 94)",
    version: "1.0.0",
    status: "published",
    sortOrder: 110,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.wrs_progression",
    domainKey: PA_DOMAIN_KEY,
    title: "WRS Step Progression",
    description: "Wilson Step band framework mapping — category only (Doc 13 §5)",
    version: "1.0.0",
    status: "published",
    sortOrder: 120,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
  {
    strandKey: "domain.structured_literacy.strand.og_principles",
    domainKey: PA_DOMAIN_KEY,
    title: "Orton-Gillingham Principles",
    description: "Multisensory structured literacy fidelity principles (Doc 13 §6)",
    version: "1.0.0",
    status: "published",
    sortOrder: 130,
    metadata: { documentRef: "DOCUMENT-13", populated: false },
  },
];
