import type { WorkspaceLayout } from "@/lib/platform/intelligence/executive-command-center/types";

export const founderLayout: WorkspaceLayout = {
  role: "founder",
  label: "Founder",
  description: "Strategic health, initiatives, and long-horizon foresight first.",
  widgetOrder: [
    "health",
    "executive_narratives",
    "ecosystem_health",
    "shared_opportunities",
    "portfolio_health",
    "recommended_scenario",
    "organization_network",
    "cross_organization_risks",
    "federated_portfolio",
    "geographic_coverage",
    "highest_impact_opportunities",
    "priority_matrix",
    "active_simulations",
    "active_initiatives",
    "portfolio_changes",
    "copilot",
    "decisions",
    "scenario_comparison",
    "capacity_utilization",
    "constraint_alerts",
    "at_risk_initiatives",
    "forecasts",
    "budget_allocation",
    "cross_initiative_risks",
    "budget_variance",
    "risks",
    "upcoming_milestones",
    "plans",
    "opportunities",
    "completed_initiatives",
    "memory",
    "signals",
    "approvals",
    "briefing",
  ],
};
