import type { WorkflowDefinition } from "@/lib/platform/workflow/types";

/**
 * Reference workflow definitions demonstrating the data-driven model.
 * These are domain-agnostic templates — consuming modules register their own.
 */
export const PLATFORM_REFERENCE_WORKFLOW_DEFINITIONS: WorkflowDefinition[] = [
  {
    workflowKey: "ref_hr_onboarding",
    name: "HR Onboarding",
    description: "Employee onboarding from offer acceptance through first-day readiness",
    domain: "hr",
    version: 1,
    status: "active",
    entityType: "employee_onboarding",
    initialStateKey: "offer_accepted",
    sortOrder: 10,
    tags: ["hr", "onboarding"],
    states: [
      { key: "offer_accepted", label: "Offer Accepted", stateType: "initial", sortOrder: 10 },
      { key: "paperwork_pending", label: "Paperwork Pending", stateType: "intermediate", sortOrder: 20 },
      { key: "background_check", label: "Background Check", stateType: "intermediate", sortOrder: 30 },
      { key: "approval_pending", label: "HR Approval", stateType: "approval_pending", sortOrder: 40 },
      { key: "ready_for_start", label: "Ready for Start", stateType: "terminal", sortOrder: 50 },
    ],
    transitions: [
      {
        key: "start_paperwork",
        label: "Start Paperwork",
        fromStateKey: "offer_accepted",
        toStateKey: "paperwork_pending",
        sortOrder: 10,
        triggerKeys: ["manual_start"],
        actions: [{ key: "notify_hr", actionType: "send_notification", sortOrder: 10 }],
      },
      {
        key: "submit_background",
        label: "Submit Background Check",
        fromStateKey: "paperwork_pending",
        toStateKey: "background_check",
        sortOrder: 20,
        conditions: [{ key: "paperwork_complete", field: "paperworkComplete", operator: "equals", value: true }],
      },
      {
        key: "request_hr_approval",
        label: "Request HR Approval",
        fromStateKey: "background_check",
        toStateKey: "approval_pending",
        sortOrder: 30,
        approvalGate: {
          key: "hr_director_approval",
          label: "HR Director Approval",
          approverRoles: ["hr_director"],
          approverCount: 1,
        },
      },
      {
        key: "complete_onboarding",
        label: "Complete Onboarding",
        fromStateKey: "approval_pending",
        toStateKey: "ready_for_start",
        sortOrder: 40,
        triggerKeys: ["approval_decided"],
        conditions: [{ key: "approved", field: "approvalStatus", operator: "equals", value: "approved" }],
        actions: [{ key: "welcome_task", actionType: "create_task", sortOrder: 10 }],
      },
    ],
    triggers: [
      { key: "manual_start", label: "Manual Start", triggerType: "manual" },
      { key: "approval_decided", label: "Approval Decided", triggerType: "approval_decided" },
    ],
  },
  {
    workflowKey: "ref_student_support_ticket",
    name: "Student Support Ticket",
    description: "Student support case from intake through resolution",
    domain: "sis",
    version: 1,
    status: "active",
    entityType: "support_ticket",
    initialStateKey: "submitted",
    sortOrder: 20,
    tags: ["support", "sis"],
    states: [
      { key: "submitted", label: "Submitted", stateType: "initial", sortOrder: 10 },
      { key: "triaged", label: "Triaged", stateType: "intermediate", sortOrder: 20 },
      { key: "in_progress", label: "In Progress", stateType: "intermediate", sortOrder: 30 },
      { key: "escalated", label: "Escalated", stateType: "intermediate", sortOrder: 40 },
      { key: "resolved", label: "Resolved", stateType: "terminal", sortOrder: 50 },
    ],
    transitions: [
      {
        key: "triage",
        label: "Triage",
        fromStateKey: "submitted",
        toStateKey: "triaged",
        sortOrder: 10,
        triggerKeys: ["ticket_submitted"],
        actions: [{ key: "assign_task", actionType: "create_task", sortOrder: 10 }],
      },
      {
        key: "begin_work",
        label: "Begin Work",
        fromStateKey: "triaged",
        toStateKey: "in_progress",
        sortOrder: 20,
        triggerKeys: ["manual"],
      },
      {
        key: "escalate_ticket",
        label: "Escalate",
        fromStateKey: "in_progress",
        toStateKey: "escalated",
        sortOrder: 30,
        escalation: {
          key: "support_escalation",
          escalateAfterMinutes: 1440,
          escalateToRoles: ["support_lead"],
          actions: [{ key: "notify_lead", actionType: "send_notification", sortOrder: 10 }],
        },
      },
      {
        key: "resolve",
        label: "Resolve",
        fromStateKey: "in_progress",
        toStateKey: "resolved",
        sortOrder: 40,
        triggerKeys: ["manual"],
        actions: [{ key: "close_audit", actionType: "record_audit", sortOrder: 10 }],
      },
    ],
    triggers: [
      { key: "ticket_submitted", label: "Ticket Submitted", triggerType: "event", eventKey: "support.ticket_submitted" },
      { key: "manual", label: "Manual", triggerType: "manual" },
    ],
  },
  {
    workflowKey: "ref_scholarship_approval",
    name: "Scholarship Approval",
    description: "Multi-step scholarship award approval workflow",
    domain: "scholarships",
    version: 1,
    status: "active",
    entityType: "scholarship_application",
    initialStateKey: "submitted",
    sortOrder: 30,
    tags: ["scholarships", "approval"],
    states: [
      { key: "submitted", label: "Submitted", stateType: "initial", sortOrder: 10 },
      { key: "committee_review", label: "Committee Review", stateType: "approval_pending", sortOrder: 20 },
      { key: "executive_review", label: "Executive Review", stateType: "approval_pending", sortOrder: 30 },
      { key: "awarded", label: "Awarded", stateType: "terminal", sortOrder: 40 },
      { key: "denied", label: "Denied", stateType: "terminal", sortOrder: 50 },
    ],
    transitions: [
      {
        key: "to_committee",
        label: "Send to Committee",
        fromStateKey: "submitted",
        toStateKey: "committee_review",
        sortOrder: 10,
        approvalGate: {
          key: "committee_gate",
          label: "Scholarship Committee",
          approverRoles: ["scholarship_committee"],
          approverCount: 2,
        },
      },
      {
        key: "to_executive",
        label: "Executive Review",
        fromStateKey: "committee_review",
        toStateKey: "executive_review",
        sortOrder: 20,
        conditions: [{ key: "committee_approved", field: "approvalStatus", operator: "equals", value: "approved" }],
        approvalGate: {
          key: "executive_gate",
          label: "Executive Approval",
          approverRoles: ["executive"],
          approverCount: 1,
        },
      },
      {
        key: "award",
        label: "Award Scholarship",
        fromStateKey: "executive_review",
        toStateKey: "awarded",
        sortOrder: 30,
        conditions: [{ key: "executive_approved", field: "approvalStatus", operator: "equals", value: "approved" }],
      },
      {
        key: "deny",
        label: "Deny Application",
        fromStateKey: "committee_review",
        toStateKey: "denied",
        sortOrder: 40,
        conditions: [{ key: "committee_denied", field: "approvalStatus", operator: "equals", value: "rejected" }],
      },
    ],
    triggers: [
      { key: "manual", label: "Manual", triggerType: "manual" },
      { key: "approval_decided", label: "Approval Decided", triggerType: "approval_decided" },
    ],
  },
  {
    workflowKey: "ref_incident_report",
    name: "Incident Report",
    description: "Incident intake, investigation, and closure",
    domain: "compliance",
    version: 1,
    status: "active",
    entityType: "incident_report",
    initialStateKey: "reported",
    sortOrder: 40,
    tags: ["compliance", "incident", "discipline"],
    states: [
      { key: "reported", label: "Reported", stateType: "initial", sortOrder: 10 },
      { key: "investigating", label: "Investigating", stateType: "intermediate", sortOrder: 20 },
      {
        key: "review",
        label: "Compliance Review",
        stateType: "approval_pending",
        sortOrder: 30,
        deadline: { key: "review_deadline", offsetMinutes: 4320, onMissActions: [{ key: "escalate", actionType: "escalate", sortOrder: 10 }] },
      },
      { key: "closed", label: "Closed", stateType: "terminal", sortOrder: 40 },
    ],
    transitions: [
      {
        key: "begin_investigation",
        label: "Begin Investigation",
        fromStateKey: "reported",
        toStateKey: "investigating",
        sortOrder: 10,
        actions: [{ key: "audit_open", actionType: "record_audit", sortOrder: 10 }],
      },
      {
        key: "submit_review",
        label: "Submit for Review",
        fromStateKey: "investigating",
        toStateKey: "review",
        sortOrder: 20,
        approvalGate: {
          key: "compliance_officer",
          label: "Compliance Officer Sign-off",
          approverRoles: ["compliance_officer"],
        },
      },
      {
        key: "close_incident",
        label: "Close Incident",
        fromStateKey: "review",
        toStateKey: "closed",
        sortOrder: 30,
        conditions: [{ key: "approved", field: "approvalStatus", operator: "equals", value: "approved" }],
      },
    ],
    triggers: [{ key: "manual", label: "Manual", triggerType: "manual" }],
  },
  {
    workflowKey: "ref_board_approval",
    name: "Board Approval",
    description: "Board-level approval for policy and budget items",
    domain: "executive",
    version: 1,
    status: "active",
    entityType: "board_item",
    initialStateKey: "draft",
    sortOrder: 50,
    tags: ["board", "approval", "governance"],
    states: [
      { key: "draft", label: "Draft", stateType: "initial", sortOrder: 10 },
      { key: "pending_board", label: "Pending Board Vote", stateType: "approval_pending", sortOrder: 20 },
      { key: "approved", label: "Approved", stateType: "terminal", sortOrder: 30 },
      { key: "rejected", label: "Rejected", stateType: "terminal", sortOrder: 40 },
    ],
    transitions: [
      {
        key: "submit_to_board",
        label: "Submit to Board",
        fromStateKey: "draft",
        toStateKey: "pending_board",
        sortOrder: 10,
        approvalGate: {
          key: "board_quorum",
          label: "Board Quorum Approval",
          approverRoles: ["board_member"],
          approverCount: 3,
          deadline: { key: "meeting_deadline", offsetMinutes: 10080 },
        },
        notifications: [
          { key: "notify_board", channel: "email", templateKey: "board_agenda_item", recipientRoles: ["board_member"] },
        ],
      },
      {
        key: "board_approve",
        label: "Board Approved",
        fromStateKey: "pending_board",
        toStateKey: "approved",
        sortOrder: 20,
        triggerKeys: ["approval_decided"],
        conditions: [{ key: "approved", field: "approvalStatus", operator: "equals", value: "approved" }],
      },
      {
        key: "board_reject",
        label: "Board Rejected",
        fromStateKey: "pending_board",
        toStateKey: "rejected",
        sortOrder: 30,
        triggerKeys: ["approval_decided"],
        conditions: [{ key: "rejected", field: "approvalStatus", operator: "equals", value: "rejected" }],
      },
    ],
    triggers: [
      { key: "manual", label: "Manual", triggerType: "manual" },
      { key: "approval_decided", label: "Approval Decided", triggerType: "approval_decided" },
    ],
  },
];
