/**
 * RC-5 — capture Playwright storageState per staging persona via UI login.
 * Skips quietly when RC5_* credentials are absent (E-001 remains open).
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { test as setup, expect } from "@playwright/test";
import { ROLE_ACCEPTANCE, type RoleId } from "../../scripts/acceptance/roles";
import {
  RC5_ROLES,
  resolvePersonasFromEnv,
  storageStatePath,
} from "../../scripts/rc5/personas";

const AUTH_DIR = "playwright/.auth";

function writeSkipMarker(role: string, reason: string) {
  mkdirSync(AUTH_DIR, { recursive: true });
  writeFileSync(
    `${AUTH_DIR}/${role}.skip.json`,
    JSON.stringify({ skipped: true, reason, at: new Date().toISOString() })
  );
}

const personas = resolvePersonasFromEnv();
const byRole = new Map(personas.map((p) => [p.role, p]));

setup("ensure auth directory", async () => {
  mkdirSync(AUTH_DIR, { recursive: true });
  writeFileSync(
    `${AUTH_DIR}/README.md`,
    "# Playwright auth states\n\nGenerated by `tests/acceptance/auth.setup.ts`. Do not commit JSON sessions.\n"
  );
  writeFileSync(
    `${AUTH_DIR}/STATUS.json`,
    JSON.stringify(
      {
        configured: personas.length > 0,
        rolesConfigured: personas.map((p) => p.role),
        reason:
          personas.length === 0
            ? "No RC5_<ROLE>_EMAIL/PASSWORD env vars — E-001 authenticated journeys skipped"
            : "Personas resolved from environment",
        at: new Date().toISOString(),
      },
      null,
      2
    )
  );
});

for (const role of RC5_ROLES) {
  const creds = byRole.get(role);
  const home = ROLE_ACCEPTANCE.find((r) => r.id === role)?.home ?? "/dashboard";

  setup(`${role} storageState`, async ({ page }) => {
    if (!creds) {
      writeSkipMarker(role, "No RC5 credentials in environment");
    }
    setup.skip(!creds, "No RC5 credentials");

    await page.goto("/login");
    await page.getByLabel("Email address").fill(creds!.email);
    await page.getByLabel("Password").fill(creds!.password);
    await page.getByRole("button", { name: /sign in/i }).click();

    await page.waitForURL(
      (url) =>
        !url.pathname.startsWith("/login") ||
        url.pathname.includes("mfa") ||
        url.pathname.includes("reset"),
      { timeout: 30_000 }
    );

    const href = page.url();
    if (href.includes("mfa-required") || href.includes("reset-required")) {
      writeSkipMarker(
        role,
        `Blocked by ${href.includes("mfa") ? "MFA" : "password reset"} gate`
      );
      setup.skip(true, "MFA or password-reset gate");
    }

    expect(page.url()).not.toMatch(/\/login(\?|$)/);
    await page.goto(home, { waitUntil: "domcontentloaded" }).catch(() => undefined);

    const out = storageStatePath(role as RoleId);
    mkdirSync(dirname(out), { recursive: true });
    await page.context().storageState({ path: out });
  });
}
