import type { FormDefinition, FormFieldDefinition } from "@/lib/platform/forms";

function fieldsFrom(
  defs: Array<Omit<FormFieldDefinition, "metadata"> & { metadata?: Record<string, unknown> }>
): FormFieldDefinition[] {
  return defs.map((f) => ({ ...f, metadata: f.metadata ?? {} }));
}

function form(input: {
  id: string;
  title: string;
  entityType: string;
  fieldDefs: FormFieldDefinition[];
  submitPermission: string;
  viewPermission: string;
  startWorkflow?: string | null;
}): FormDefinition {
  return {
    id: input.id,
    applicationId: "academyos",
    entityType: input.entityType,
    version: "1.1.0",
    title: input.title,
    description: `${input.title} (AcademyOS)`,
    sections: [
      {
        key: "main",
        title: "Main",
        fields: input.fieldDefs.map((f) => f.key),
      },
    ],
    fields: input.fieldDefs,
    workflow: input.startWorkflow
      ? {
          startOnSubmit: input.startWorkflow,
          recordTimeline: true,
          createDecision: false,
          attachDocuments: false,
        }
      : null,
    permissions: [
      { action: "view", permission: input.viewPermission },
      { action: "submit", permission: input.submitPermission },
      { action: "edit", permission: input.submitPermission },
    ],
    metadata: { application: "academyos", phase: "domain-completion" },
  };
}

const nameFields = fieldsFrom([
  { key: "displayName", type: "text", label: "Name", validation: { required: true } },
]);

const statusField = {
  key: "status",
  type: "select" as const,
  label: "Status",
  validation: { required: true },
  defaultValue: "active",
};

/** Complete AcademyOS forms catalog — definitions only (no UI). */
export const ACADEMYOS_FORMS: FormDefinition[] = [
  form({
    id: "academyos.student.create",
    title: "Student",
    entityType: "Student",
    viewPermission: "academyos.students.read",
    submitPermission: "academyos.students.create",
    startWorkflow: "academyos.admissions",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Full name", validation: { required: true } },
      { key: "firstName", type: "text", label: "First name", validation: { required: true } },
      { key: "lastName", type: "text", label: "Last name", validation: { required: true } },
      { key: "dateOfBirth", type: "date", label: "Date of birth" },
      { key: "email", type: "email", label: "Email" },
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "familyId", type: "entity_reference", label: "Family", entityType: "Family" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.guardian.create",
    title: "Guardian",
    entityType: "Guardian",
    viewPermission: "academyos.guardians.read",
    submitPermission: "academyos.guardians.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Full name", validation: { required: true } },
      { key: "email", type: "email", label: "Email", validation: { required: true } },
      { key: "phone", type: "phone", label: "Phone" },
      { key: "familyId", type: "entity_reference", label: "Family", entityType: "Family" },
      { key: "relationship", type: "select", label: "Relationship", validation: { required: true } },
    ]),
  }),
  form({
    id: "academyos.emergency-contact.create",
    title: "Emergency Contact",
    entityType: "EmergencyContact",
    viewPermission: "academyos.students.read",
    submitPermission: "academyos.students.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Full name", validation: { required: true } },
      { key: "phone", type: "phone", label: "Phone" },
      { key: "email", type: "email", label: "Email" },
      {
        key: "studentId",
        type: "entity_reference",
        label: "Student",
        entityType: "Student",
        validation: { required: true },
      },
      { key: "relationship", type: "select", label: "Relationship", validation: { required: true } },
      { key: "priority", type: "boolean", label: "Primary contact" },
    ]),
  }),
  form({
    id: "academyos.teacher.create",
    title: "Teacher",
    entityType: "Teacher",
    viewPermission: "academyos.staff.read",
    submitPermission: "academyos.staff.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Full name", validation: { required: true } },
      { key: "email", type: "email", label: "Email", validation: { required: true } },
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "employeeId", type: "entity_reference", label: "Employee", entityType: "Employee" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.employee.create",
    title: "Employee",
    entityType: "Employee",
    viewPermission: "academyos.hr.read",
    submitPermission: "academyos.hr.create",
    startWorkflow: "academyos.hiring",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Full name", validation: { required: true } },
      { key: "email", type: "email", label: "Email", validation: { required: true } },
      { key: "jobTitle", type: "select", label: "Job title" },
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "hireDate", type: "date", label: "Hire date" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.school.create",
    title: "School",
    entityType: "School",
    viewPermission: "academyos.schools.read",
    submitPermission: "academyos.schools.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "School name", validation: { required: true } },
      { key: "code", type: "text", label: "School code", validation: { required: true } },
      {
        key: "organizationId",
        type: "entity_reference",
        label: "Organization",
        entityType: "Organization",
        validation: { required: true },
      },
      statusField,
    ]),
  }),
  form({
    id: "academyos.program.create",
    title: "Program",
    entityType: "Program",
    viewPermission: "academyos.programs.read",
    submitPermission: "academyos.programs.create",
    fieldDefs: fieldsFrom([
      ...nameFields,
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "code", type: "text", label: "Code" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.course.create",
    title: "Course",
    entityType: "Course",
    viewPermission: "academyos.learning.read",
    submitPermission: "academyos.learning.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Course name", validation: { required: true } },
      { key: "code", type: "text", label: "Course code", validation: { required: true } },
      { key: "programId", type: "entity_reference", label: "Program", entityType: "Program" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.section.create",
    title: "Section",
    entityType: "Section",
    viewPermission: "academyos.learning.read",
    submitPermission: "academyos.learning.create",
    fieldDefs: fieldsFrom([
      ...nameFields,
      {
        key: "courseId",
        type: "entity_reference",
        label: "Course",
        entityType: "Course",
        validation: { required: true },
      },
      { key: "termId", type: "entity_reference", label: "Term", entityType: "Term" },
      { key: "teacherId", type: "entity_reference", label: "Teacher", entityType: "Teacher" },
      { key: "classroomId", type: "entity_reference", label: "Classroom", entityType: "Classroom" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.class.create",
    title: "Class",
    entityType: "Class",
    viewPermission: "academyos.learning.read",
    submitPermission: "academyos.learning.create",
    fieldDefs: fieldsFrom([
      ...nameFields,
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "programId", type: "entity_reference", label: "Program", entityType: "Program" },
      { key: "teacherId", type: "entity_reference", label: "Teacher", entityType: "Teacher" },
      { key: "sectionId", type: "entity_reference", label: "Section", entityType: "Section" },
      { key: "term", type: "select", label: "Term" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.enrollment.create",
    title: "Enrollment",
    entityType: "Enrollment",
    viewPermission: "academyos.enrollment.read",
    submitPermission: "academyos.enrollment.create",
    startWorkflow: "academyos.enrollment",
    fieldDefs: fieldsFrom([
      {
        key: "studentId",
        type: "entity_reference",
        label: "Student",
        entityType: "Student",
        validation: { required: true },
      },
      { key: "sectionId", type: "entity_reference", label: "Section", entityType: "Section" },
      { key: "classId", type: "entity_reference", label: "Class", entityType: "Class" },
      { key: "programId", type: "entity_reference", label: "Program", entityType: "Program" },
      { key: "startDate", type: "date", label: "Start date", validation: { required: true } },
      { key: "status", type: "select", label: "Status", validation: { required: true }, defaultValue: "pending" },
    ]),
  }),
  form({
    id: "academyos.attendance.create",
    title: "Attendance Record",
    entityType: "AttendanceRecord",
    viewPermission: "academyos.attendance.read",
    submitPermission: "academyos.attendance.create",
    fieldDefs: fieldsFrom([
      {
        key: "studentId",
        type: "entity_reference",
        label: "Student",
        entityType: "Student",
        validation: { required: true },
      },
      { key: "sectionId", type: "entity_reference", label: "Section", entityType: "Section" },
      { key: "classId", type: "entity_reference", label: "Class", entityType: "Class" },
      { key: "attendanceDate", type: "date", label: "Date", validation: { required: true } },
      {
        key: "attendanceCodeId",
        type: "entity_reference",
        label: "Code",
        entityType: "AttendanceCode",
      },
      { key: "status", type: "select", label: "Status", validation: { required: true } },
      { key: "notes", type: "text", label: "Notes" },
    ]),
  }),
  form({
    id: "academyos.assessment.create",
    title: "Assessment",
    entityType: "Assessment",
    viewPermission: "academyos.assessments.read",
    submitPermission: "academyos.assessments.create",
    fieldDefs: fieldsFrom([
      ...nameFields,
      { key: "studentId", type: "entity_reference", label: "Student", entityType: "Student" },
      { key: "sectionId", type: "entity_reference", label: "Section", entityType: "Section" },
      { key: "administeredOn", type: "date", label: "Date" },
      { key: "score", type: "number", label: "Score" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.inquiry.create",
    title: "Inquiry",
    entityType: "Inquiry",
    viewPermission: "academyos.admissions.read",
    submitPermission: "academyos.admissions.create",
    startWorkflow: "academyos.admissions",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Inquirer name", validation: { required: true } },
      { key: "email", type: "email", label: "Email", validation: { required: true } },
      { key: "phone", type: "phone", label: "Phone" },
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "source", type: "select", label: "Source" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.application.create",
    title: "Application",
    entityType: "Application",
    viewPermission: "academyos.admissions.read",
    submitPermission: "academyos.admissions.create",
    startWorkflow: "academyos.admissions",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Applicant name", validation: { required: true } },
      { key: "inquiryId", type: "entity_reference", label: "Inquiry", entityType: "Inquiry" },
      { key: "studentId", type: "entity_reference", label: "Student", entityType: "Student" },
      {
        key: "schoolId",
        type: "entity_reference",
        label: "School",
        entityType: "School",
        validation: { required: true },
      },
      { key: "submittedOn", type: "date", label: "Submitted on" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.behavior-incident.create",
    title: "Behavior Incident",
    entityType: "BehaviorIncident",
    viewPermission: "academyos.behavior.read",
    submitPermission: "academyos.behavior.create",
    startWorkflow: "academyos.behavior",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Incident title", validation: { required: true } },
      {
        key: "studentId",
        type: "entity_reference",
        label: "Student",
        entityType: "Student",
        validation: { required: true },
      },
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "occurredOn", type: "date", label: "Occurred on", validation: { required: true } },
      { key: "severity", type: "select", label: "Severity", validation: { required: true } },
      { key: "description", type: "rich_text", label: "Description" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.iep.create",
    title: "IEP",
    entityType: "IEP",
    viewPermission: "academyos.compliance.read",
    submitPermission: "academyos.compliance.create",
    fieldDefs: fieldsFrom([
      {
        key: "studentId",
        type: "entity_reference",
        label: "Student",
        entityType: "Student",
        validation: { required: true },
      },
      { key: "effectiveOn", type: "date", label: "Effective on", validation: { required: true } },
      { key: "reviewOn", type: "date", label: "Review on" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.plan504.create",
    title: "504 Plan",
    entityType: "Plan504",
    viewPermission: "academyos.compliance.read",
    submitPermission: "academyos.compliance.create",
    fieldDefs: fieldsFrom([
      {
        key: "studentId",
        type: "entity_reference",
        label: "Student",
        entityType: "Student",
        validation: { required: true },
      },
      { key: "effectiveOn", type: "date", label: "Effective on", validation: { required: true } },
      { key: "reviewOn", type: "date", label: "Review on" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.medical-record.create",
    title: "Medical Record",
    entityType: "MedicalRecord",
    viewPermission: "academyos.medical.read",
    submitPermission: "academyos.medical.create",
    fieldDefs: fieldsFrom([
      {
        key: "studentId",
        type: "entity_reference",
        label: "Student",
        entityType: "Student",
        validation: { required: true },
      },
      ...nameFields,
      { key: "recordType", type: "select", label: "Type", validation: { required: true } },
      { key: "recordedOn", type: "date", label: "Recorded on" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.medication-authorization.create",
    title: "Medication Authorization",
    entityType: "MedicationAuthorization",
    viewPermission: "academyos.medical.read",
    submitPermission: "academyos.medical.create",
    fieldDefs: fieldsFrom([
      {
        key: "studentId",
        type: "entity_reference",
        label: "Student",
        entityType: "Student",
        validation: { required: true },
      },
      { key: "medicationName", type: "text", label: "Medication", validation: { required: true } },
      { key: "startDate", type: "date", label: "Start", validation: { required: true } },
      { key: "endDate", type: "date", label: "End" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.transportation-route.create",
    title: "Transportation Route",
    entityType: "TransportationRoute",
    viewPermission: "academyos.operations.read",
    submitPermission: "academyos.operations.create",
    fieldDefs: fieldsFrom([
      ...nameFields,
      {
        key: "schoolId",
        type: "entity_reference",
        label: "School",
        entityType: "School",
        validation: { required: true },
      },
      { key: "code", type: "text", label: "Route code" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.scholarship.create",
    title: "Scholarship",
    entityType: "Scholarship",
    viewPermission: "academyos.scholarships.read",
    submitPermission: "academyos.scholarships.create",
    startWorkflow: "academyos.scholarship",
    fieldDefs: fieldsFrom([
      ...nameFields,
      {
        key: "studentId",
        type: "entity_reference",
        label: "Student",
        entityType: "Student",
        validation: { required: true },
      },
      {
        key: "awardAmount",
        type: "currency",
        label: "Award amount",
        validation: { required: true, min: 0 },
      },
      { key: "status", type: "select", label: "Status", validation: { required: true }, defaultValue: "pending" },
      { key: "awardedOn", type: "date", label: "Awarded on" },
    ]),
  }),
  form({
    id: "academyos.invoice.create",
    title: "Invoice",
    entityType: "Invoice",
    viewPermission: "academyos.finance.read",
    submitPermission: "academyos.finance.create",
    startWorkflow: "academyos.finance",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Invoice number", validation: { required: true } },
      { key: "studentId", type: "entity_reference", label: "Student", entityType: "Student" },
      { key: "familyId", type: "entity_reference", label: "Family", entityType: "Family" },
      { key: "amount", type: "currency", label: "Amount", validation: { required: true, min: 0 } },
      { key: "dueDate", type: "date", label: "Due date" },
      { key: "status", type: "select", label: "Status", validation: { required: true }, defaultValue: "open" },
    ]),
  }),
  form({
    id: "academyos.payment.create",
    title: "Payment",
    entityType: "Payment",
    viewPermission: "academyos.finance.read",
    submitPermission: "academyos.finance.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Payment reference", validation: { required: true } },
      { key: "invoiceId", type: "entity_reference", label: "Invoice", entityType: "Invoice" },
      { key: "amount", type: "currency", label: "Amount", validation: { required: true, min: 0 } },
      { key: "paidOn", type: "date", label: "Paid on", validation: { required: true } },
      { key: "method", type: "select", label: "Method" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.payroll-batch.create",
    title: "Payroll Batch",
    entityType: "PayrollBatch",
    viewPermission: "academyos.hr.read",
    submitPermission: "academyos.hr.create",
    startWorkflow: "academyos.payroll-approval",
    fieldDefs: fieldsFrom([
      ...nameFields,
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "periodStart", type: "date", label: "Period start", validation: { required: true } },
      { key: "periodEnd", type: "date", label: "Period end", validation: { required: true } },
      { key: "totalAmount", type: "currency", label: "Total" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.calendar-event.create",
    title: "Calendar Event",
    entityType: "CalendarEvent",
    viewPermission: "academyos.operations.read",
    submitPermission: "academyos.operations.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Event title", validation: { required: true } },
      { key: "startDate", type: "date", label: "Start", validation: { required: true } },
      { key: "endDate", type: "date", label: "End" },
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "eventType", type: "select", label: "Type", validation: { required: true } },
    ]),
  }),
  form({
    id: "academyos.announcement.create",
    title: "Announcement",
    entityType: "Announcement",
    viewPermission: "academyos.communications.read",
    submitPermission: "academyos.communications.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Title", validation: { required: true } },
      { key: "body", type: "rich_text", label: "Body" },
      { key: "schoolId", type: "entity_reference", label: "School", entityType: "School" },
      { key: "audience", type: "select", label: "Audience", validation: { required: true } },
      statusField,
      { key: "publishOn", type: "date", label: "Publish on" },
    ]),
  }),
  form({
    id: "academyos.document.create",
    title: "Document",
    entityType: "Document",
    viewPermission: "academyos.documents.read",
    submitPermission: "academyos.documents.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Document title", validation: { required: true } },
      { key: "documentType", type: "select", label: "Type", validation: { required: true } },
      { key: "studentId", type: "entity_reference", label: "Student", entityType: "Student" },
      { key: "employeeId", type: "entity_reference", label: "Employee", entityType: "Employee" },
      statusField,
    ]),
  }),
  form({
    id: "academyos.message.create",
    title: "Message",
    entityType: "Message",
    viewPermission: "academyos.communications.read",
    submitPermission: "academyos.communications.create",
    fieldDefs: fieldsFrom([
      { key: "displayName", type: "text", label: "Subject", validation: { required: true } },
      { key: "body", type: "rich_text", label: "Body" },
      { key: "studentId", type: "entity_reference", label: "Student", entityType: "Student" },
      { key: "familyId", type: "entity_reference", label: "Family", entityType: "Family" },
      { key: "channel", type: "select", label: "Channel", validation: { required: true } },
      statusField,
    ]),
  }),
];
