/**
 * API contract inventory — Stage 6.
 * Catalog only. Do not register these until implementation sprints.
 */

export type AcademyApiCatalogEntry = {
  id: string;
  method: "GET" | "POST" | "PATCH" | "DELETE";
  path: string;
  entityType: string;
  schemaId: string;
  permission: string;
  summary: string;
  status: "registered" | "planned";
  domain: string;
};

export const ACADEMYOS_API_CATALOG: AcademyApiCatalogEntry[] = [
  // Registered foundation
  {
    id: "academyos.students.list",
    method: "GET",
    path: "/api/v1/academyos/students",
    entityType: "Student",
    schemaId: "academyos.student",
    permission: "academyos.students.read",
    summary: "List students",
    status: "registered",
    domain: "students",
  },
  {
    id: "academyos.students.create",
    method: "POST",
    path: "/api/v1/academyos/students",
    entityType: "Student",
    schemaId: "academyos.student",
    permission: "academyos.students.create",
    summary: "Create student",
    status: "registered",
    domain: "students",
  },
  {
    id: "academyos.schools.list",
    method: "GET",
    path: "/api/v1/academyos/schools",
    entityType: "School",
    schemaId: "academyos.school",
    permission: "academyos.schools.read",
    summary: "List schools",
    status: "registered",
    domain: "administration",
  },
  {
    id: "academyos.enrollment.create",
    method: "POST",
    path: "/api/v1/academyos/enrollments",
    entityType: "Enrollment",
    schemaId: "academyos.enrollment",
    permission: "academyos.enrollment.create",
    summary: "Create enrollment",
    status: "registered",
    domain: "enrollment",
  },
  {
    id: "academyos.attendance.create",
    method: "POST",
    path: "/api/v1/academyos/attendance",
    entityType: "AttendanceRecord",
    schemaId: "academyos.attendance-record",
    permission: "academyos.attendance.create",
    summary: "Record attendance",
    status: "registered",
    domain: "attendance",
  },
  {
    id: "academyos.employees.list",
    method: "GET",
    path: "/api/v1/academyos/employees",
    entityType: "Employee",
    schemaId: "academyos.employee",
    permission: "academyos.hr.read",
    summary: "List employees",
    status: "registered",
    domain: "hr",
  },
  {
    id: "academyos.invoices.create",
    method: "POST",
    path: "/api/v1/academyos/invoices",
    entityType: "Invoice",
    schemaId: "academyos.invoice",
    permission: "academyos.finance.create",
    summary: "Create invoice",
    status: "registered",
    domain: "finance",
  },
  {
    id: "academyos.scholarships.create",
    method: "POST",
    path: "/api/v1/academyos/scholarships",
    entityType: "Scholarship",
    schemaId: "academyos.scholarship",
    permission: "academyos.scholarships.create",
    summary: "Create scholarship",
    status: "registered",
    domain: "scholarships",
  },

  // Planned domain contracts (not registered yet)
  {
    id: "academyos.inquiries.create",
    method: "POST",
    path: "/api/v1/academyos/inquiries",
    entityType: "Inquiry",
    schemaId: "academyos.inquiry",
    permission: "academyos.admissions.create",
    summary: "Create admissions inquiry",
    status: "planned",
    domain: "admissions",
  },
  {
    id: "academyos.applications.create",
    method: "POST",
    path: "/api/v1/academyos/applications",
    entityType: "Application",
    schemaId: "academyos.application",
    permission: "academyos.admissions.create",
    summary: "Create application",
    status: "planned",
    domain: "admissions",
  },
  {
    id: "academyos.guardians.list",
    method: "GET",
    path: "/api/v1/academyos/guardians",
    entityType: "Guardian",
    schemaId: "academyos.guardian",
    permission: "academyos.guardians.read",
    summary: "List guardians",
    status: "planned",
    domain: "families",
  },
  {
    id: "academyos.sections.list",
    method: "GET",
    path: "/api/v1/academyos/sections",
    entityType: "Section",
    schemaId: "academyos.section",
    permission: "academyos.learning.read",
    summary: "List sections",
    status: "planned",
    domain: "academics",
  },
  {
    id: "academyos.assessments.create",
    method: "POST",
    path: "/api/v1/academyos/assessments",
    entityType: "Assessment",
    schemaId: "academyos.assessment",
    permission: "academyos.assessments.create",
    summary: "Create assessment",
    status: "planned",
    domain: "academics",
  },
  {
    id: "academyos.behavior-incidents.create",
    method: "POST",
    path: "/api/v1/academyos/behavior-incidents",
    entityType: "BehaviorIncident",
    schemaId: "academyos.behavior-incident",
    permission: "academyos.behavior.create",
    summary: "Create behavior incident",
    status: "planned",
    domain: "behavior",
  },
  {
    id: "academyos.payments.create",
    method: "POST",
    path: "/api/v1/academyos/payments",
    entityType: "Payment",
    schemaId: "academyos.payment",
    permission: "academyos.finance.create",
    summary: "Record payment",
    status: "planned",
    domain: "finance",
  },
  {
    id: "academyos.payroll-batches.create",
    method: "POST",
    path: "/api/v1/academyos/payroll-batches",
    entityType: "PayrollBatch",
    schemaId: "academyos.payroll-batch",
    permission: "academyos.hr.create",
    summary: "Create payroll batch",
    status: "planned",
    domain: "hr",
  },
  {
    id: "academyos.ieps.list",
    method: "GET",
    path: "/api/v1/academyos/ieps",
    entityType: "IEP",
    schemaId: "academyos.iep",
    permission: "academyos.compliance.read",
    summary: "List IEPs",
    status: "planned",
    domain: "compliance",
  },
  {
    id: "academyos.medical-records.create",
    method: "POST",
    path: "/api/v1/academyos/medical-records",
    entityType: "MedicalRecord",
    schemaId: "academyos.medical-record",
    permission: "academyos.medical.create",
    summary: "Create medical record",
    status: "planned",
    domain: "medical",
  },
  {
    id: "academyos.transportation-routes.list",
    method: "GET",
    path: "/api/v1/academyos/transportation-routes",
    entityType: "TransportationRoute",
    schemaId: "academyos.transportation-route",
    permission: "academyos.operations.read",
    summary: "List transportation routes",
    status: "planned",
    domain: "transportation",
  },
  {
    id: "academyos.messages.create",
    method: "POST",
    path: "/api/v1/academyos/messages",
    entityType: "Message",
    schemaId: "academyos.message",
    permission: "academyos.communications.create",
    summary: "Send message",
    status: "planned",
    domain: "communication",
  },
  {
    id: "academyos.announcements.create",
    method: "POST",
    path: "/api/v1/academyos/announcements",
    entityType: "Announcement",
    schemaId: "academyos.announcement",
    permission: "academyos.communications.create",
    summary: "Create announcement",
    status: "planned",
    domain: "communication",
  },
  {
    id: "academyos.transcripts.get",
    method: "GET",
    path: "/api/v1/academyos/transcripts/{id}",
    entityType: "Transcript",
    schemaId: "academyos.transcript",
    permission: "academyos.learning.read",
    summary: "Get transcript",
    status: "planned",
    domain: "academics",
  },
];

export function listAcademyApiCatalog(status?: "registered" | "planned"): AcademyApiCatalogEntry[] {
  const all = [...ACADEMYOS_API_CATALOG];
  return status ? all.filter((e) => e.status === status) : all;
}
