/**
 * Release artifact package — canonical release record from evidence.
 */

import { createPerEngine } from "../per/engine";
import { createProductRegistryService } from "../products/registry";
import { computeProductQualityScore } from "../quality/scorer";
import { buildTestingWorkspace } from "../testing/workspace";
import type { ReleaseStatus, StudioProductId, StudioRelease } from "../types";
import { getRelease, listReleases } from "../store";
import { evaluateReleaseGates } from "./gates";

export type ReleaseArtifactPackage = {
  readonly id: string;
  readonly productId: string;
  readonly version: string;
  readonly stage: ReleaseStatus;
  readonly generatedAt: string;
  readonly releaseNotes: string;
  readonly migrationSummary: readonly string[];
  readonly perSummary: readonly {
    readonly id: string;
    readonly status: string;
    readonly description: string;
  }[];
  readonly knownIssues: readonly string[];
  readonly compatibilityMatrix: Readonly<Record<string, string>>;
  readonly testSummary: {
    readonly passRate: number;
    readonly suites: number;
    readonly failures: number;
  };
  readonly qualityReport: {
    readonly overall: number;
    readonly components: readonly { key: string; score: number }[];
  };
  readonly gateSummary: {
    readonly passed: boolean;
    readonly blockers: readonly string[];
  };
  readonly canonical: true;
};

export function generateReleaseArtifacts(input: {
  productId: StudioProductId | string;
  releaseId?: string;
  root?: string;
}): ReleaseArtifactPackage | { error: string } {
  const product = createProductRegistryService().get(
    input.productId as StudioProductId
  );
  if (!product) return { error: "Unknown product." };

  const release: StudioRelease | null = input.releaseId
    ? getRelease(input.releaseId)
    : listReleases(input.productId)[0] ?? null;

  const root = input.root ?? process.cwd();
  const stage = release?.status ?? product.releaseStatus;
  const quality = computeProductQualityScore({
    productId: input.productId,
    root,
  });
  const testing = buildTestingWorkspace(root);
  const gates = evaluateReleaseGates({
    productId: input.productId,
    targetStage: stage,
    root,
  });
  const pers = createPerEngine()
    .list()
    .filter(
      (p) =>
        p.originatingPack === input.productId ||
        p.packsMentioning.includes(input.productId)
    );

  const knownIssues = [
    ...gates.blockers,
    ...pers
      .filter((p) => p.status === "Open" || p.status === "Accepted")
      .slice(0, 10)
      .map((p) => `${p.id}: ${p.description}`),
  ];

  return {
    id: `artifact:${input.productId}:${release?.version ?? product.version}`,
    productId: input.productId,
    version: release?.version ?? product.version,
    stage,
    generatedAt: new Date().toISOString(),
    releaseNotes:
      release?.releaseNotes ||
      `${product.name} ${product.version} — generated by JAG Studio.`,
    migrationSummary: Object.freeze([
      ...(release?.migrationHistory ?? []),
      ...(release?.upgradePath ?? []).map((s) => `upgrade→${s}`),
    ]),
    perSummary: Object.freeze(
      pers.slice(0, 30).map((p) => ({
        id: p.id,
        status: p.status,
        description: p.description,
      }))
    ),
    knownIssues: Object.freeze(knownIssues),
    compatibilityMatrix: Object.freeze({
      ...(release?.compatibilityMatrix ?? {
        platform: "1.x",
        sdk: "1.x",
      }),
    }),
    testSummary: {
      passRate: testing.overallPassRate,
      suites: testing.suites.length,
      failures: testing.totalFailures,
    },
    qualityReport: {
      overall: quality.overall,
      components: Object.freeze(
        quality.components.map((c) => ({ key: c.key, score: c.rawScore }))
      ),
    },
    gateSummary: {
      passed: gates.passed,
      blockers: gates.blockers,
    },
    canonical: true,
  };
}

export function createReleaseArtifactService() {
  return {
    generate: generateReleaseArtifacts,
  };
}
