export {
  ACADEMY_ADMISSIONS_COMMUNICATION_DEFINITION_IDS,
  ACADEMY_ADMISSIONS_COMMUNICATION_DEFINITIONS,
  ACADEMY_ADMISSIONS_COMMUNICATION_IDS,
  ACADEMY_ADMISSIONS_COMMUNICATION_TEMPLATE_ID_LIST,
  ACADEMY_ADMISSIONS_COMMUNICATION_TEMPLATES,
  ACADEMY_ADMISSIONS_TEMPLATE_IDS,
} from "@/packages/academy/communications/admissions/definitions";
