/** Alternative funding intelligence suite. */
import type * as C from "@/lib/platform/intelligence/funding/contracts";
import { buildLenses, clamp, priorityFromScore } from "@/lib/platform/intelligence/funding/models";
import type * as T from "@/lib/platform/intelligence/funding/types";
type Id = (prefix: string) => string;
const lens = buildLenses({ availableFunding: "Alternative mechanisms unlock incremental capital and revenue.", diversification: "Smaller independent channels broaden the funding mix.", fundingRisk: "Execution, qualification, market, and regulatory risks are controlled.", sustainability: "Repeatable mechanisms can become durable funding streams.", missionImpact: "Community participation and impact assets reinforce mission reach." });
function base(input: C.BaselineInput, id: Id, prefix: string, name: string, share: number): T.FundingRecordBase { const score = clamp(input.baseline.organizationHealthScore * 0.35 + input.baseline.financialScore * 0.3 + input.baseline.proposalCapacity * 0.2 + 10); const amount = Math.round(input.baseline.annualFundingNeed * share); return { id: id(prefix), name, amount, score, priority: priorityFromScore(100 - score), eligibility: ["school", "nonprofit", "for_profit"], lenses: lens, narrative: `${name} could add $${amount.toLocaleString()} to the funding plan at ${Math.round(score)}% readiness.` }; }
class Base { constructor(protected readonly createId: Id = (p) => `${p}-${Date.now()}`) {} }
export class Crowdfunding extends Base implements C.Crowdfunding { analyze(input: C.BaselineInput): T.CrowdfundingRecord[] { const b = base(input, this.createId, "crowd", "Community learning campaign", 0.025); return [{ ...b, platform: "Mission crowdfunding platform", backerGoal: Math.max(250, Math.round(b.amount / 200)) }]; } }
export class Sponsorships extends Base implements C.Sponsorships { analyze(input: C.BaselineInput): T.SponsorshipRecord[] { return [{ ...base(input, this.createId, "sponsor", "Learning program sponsorship", 0.04), sponsorCategory: "Regional employers", benefits: ["Brand visibility", "Talent pipeline", "Impact reporting"] }]; } }
export class TaxCredits extends Base implements C.TaxCredits { analyze(input: C.BaselineInput): T.TaxCreditRecord[] { return [{ ...base(input, this.createId, "tax-credit", "Education investment tax credit", 0.03), jurisdiction: "Applicable state", creditRate: 0.3 }]; } }
export class TaxIncentives extends Base implements C.TaxIncentives { analyze(input: C.BaselineInput): T.TaxIncentiveRecord[] { return [{ ...base(input, this.createId, "tax-incentive", "Workforce development incentive", 0.025), jurisdiction: "Applicable locality", incentiveType: "Training reimbursement" }]; } }
export class OpportunityZones extends Base implements C.OpportunityZones { analyze(input: C.BaselineInput): T.OpportunityZoneRecord[] { return [{ ...base(input, this.createId, "oz", "Opportunity zone learning hub", 0.12), zone: "Qualified service-area tract", investmentTermYears: 10 }]; } }
export class NewMarketsTaxCredits extends Base implements C.NewMarketsTaxCredits { analyze(input: C.BaselineInput): T.NewMarketsTaxCreditRecord[] { return [{ ...base(input, this.createId, "nmtc", "Community education facility NMTC", 0.18), allocationRound: `${input.now.getUTCFullYear()} allocation`, creditPct: 0.39 }]; } }
export class CarbonCredits extends Base implements C.CarbonCredits { analyze(input: C.BaselineInput): T.CarbonCreditRecord[] { const b = base(input, this.createId, "carbon", "Campus efficiency carbon credits", 0.008); return [{ ...b, tonnes: Math.max(100, Math.round(b.amount / 22)), pricePerTonne: 22 }]; } }
export class LicensingRevenue extends Base implements C.LicensingRevenue { analyze(input: C.BaselineInput): T.LicensingRevenueRecord[] { return [{ ...base(input, this.createId, "license", "Curriculum content licensing", 0.045), asset: "Instructional content and educator tools", royaltyRate: 0.12 }]; } }
export class RoyaltyRevenue extends Base implements C.RoyaltyRevenue { analyze(input: C.BaselineInput): T.RoyaltyRevenueRecord[] { return [{ ...base(input, this.createId, "royalty", "Learning methodology royalty", 0.03), asset: "Validated learning methodology", royaltyRate: 0.08 }]; } }
