/** Contract and procurement intelligence suite. */
import type * as C from "@/lib/platform/intelligence/funding/contracts";
import { buildLenses, clamp, clamp01, priorityFromScore, statusFromScore } from "@/lib/platform/intelligence/funding/models";
import type * as T from "@/lib/platform/intelligence/funding/types";
type Id = (prefix: string) => string;
const lens = buildLenses({ availableFunding: "Contract awards create earned, often multi-year funding.", diversification: "Procurement revenue balances grants and philanthropy.", fundingRisk: "Bid cost, performance, and payment risks require gates.", sustainability: "Renewable contracts improve predictable cash flow.", missionImpact: "Mission-aligned services scale through institutional buyers." });
function base(input: C.BaselineInput, id: Id, prefix: string, name: string, share: number): T.FundingRecordBase { const score = clamp(input.baseline.proposalCapacity * 0.5 + input.baseline.complianceReadiness * 0.35 + 10); const amount = Math.round(input.baseline.annualFundingNeed * share); return { id: id(prefix), name, amount, score, priority: priorityFromScore(100 - score), deadline: new Date(input.now.getTime() + 75 * 86_400_000).toISOString(), eligibility: ["school", "nonprofit", "for_profit"], lenses: lens, narrative: `${name} represents a $${amount.toLocaleString()} procurement opportunity with ${Math.round(score)}% readiness.` }; }
class Base { constructor(protected readonly createId: Id = (p) => `${p}-${Date.now()}`) {} }
export class GovernmentContracts extends Base implements C.GovernmentContracts { analyze(input: C.BaselineInput): T.GovernmentContractRecord[] { return [{ ...base(input, this.createId, "gov-contract", "Student support services contract", 0.16), agency: "State education agency", contractVehicle: "Competitive services IDIQ" }]; } }
export class CorporateContracts extends Base implements C.CorporateContracts { analyze(input: C.BaselineInput): T.CorporateContractRecord[] { return [{ ...base(input, this.createId, "corp-contract", "Employer learning partnership", 0.11), corporation: "Regional employer consortium", serviceCategory: "Talent development" }]; } }
export class RFPDiscovery extends Base implements C.RFPDiscovery { discover(input: C.BaselineInput): T.RfpOpportunityRecord[] { return [{ ...base(input, this.createId, "rfp", "Community education services RFP", 0.13), issuer: "Regional public authority", rfpNumber: `RFP-${input.now.getUTCFullYear()}-034` }]; } }
export class BidScoring extends Base implements C.BidScoring { score({ baseline, opportunities }: Parameters<C.BidScoring["score"]>[0]): T.BidScoreRecord[] { return opportunities.map((o) => ({ ...o, id: this.createId("bid"), opportunityId: o.id, winProbability: clamp01(baseline.grantWinRate + o.score / 300), narrative: `${o.name} has a ${Math.round(clamp01(baseline.grantWinRate + o.score / 300) * 100)}% estimated win probability.` })); } }
export class ProposalOptimization extends Base implements C.ProposalOptimization { optimize({ baseline, bids }: Parameters<C.ProposalOptimization["optimize"]>[0]): T.ProposalOptimizationRecord[] { return bids.map((b) => ({ ...b, id: this.createId("proposal-opt"), opportunityId: b.opportunityId, actions: ["Map evaluation criteria", "Quantify outcomes", "Validate price-to-win", "Complete compliance review"], score: clamp((b.score + baseline.proposalCapacity) / 2), narrative: `${b.name} should prioritize evaluation mapping and quantified outcomes before submission.` })); } }
export class ContractForecast implements C.ContractForecast { forecast({ baseline, contracts }: Parameters<C.ContractForecast["forecast"]>[0]): T.ContractForecastResult { const totalPipeline = contracts.reduce((s, c) => s + c.amount, 0); const probability = clamp01(0.18 + baseline.proposalCapacity / 200); const weightedPipeline = totalPipeline * probability; return { totalPipeline, weightedPipeline, expectedAwards: Math.round(weightedPipeline), records: contracts, lenses: lens, narrative: `Contract pipeline is $${totalPipeline.toLocaleString()} with $${Math.round(weightedPipeline).toLocaleString()} weighted awards and ${statusFromScore(baseline.proposalCapacity)} capacity.` }; } }
