/** Funding scores, health, dashboards, aggregators, calendar, and brief. */
import type * as C from "@/lib/platform/intelligence/funding/contracts";
import { buildConfidence, buildLenses, clamp, clamp01, priorityFromRisk, priorityFromScore, scoreNarrative, statusFromScore } from "@/lib/platform/intelligence/funding/models";
import type * as T from "@/lib/platform/intelligence/funding/types";
type Id = (prefix: string) => string;
const lenses = buildLenses({ availableFunding: "Priorities maximize risk-adjusted available funding.", diversification: "Portfolio balance is measured across independent sources.", fundingRisk: "Concentration, timing, compliance, and runway are quantified.", sustainability: "Renewable capital and adequate runway protect continuity.", missionImpact: "Capital choices are evaluated against mission outcomes." });
function score(key: string, label: string, value: number, risk = false): T.FundingScore { const bounded = clamp(value); const statusValue = risk ? 100 - bounded : bounded; return { key, label, value: bounded, status: statusFromScore(statusValue), band: risk ? priorityFromRisk(bounded / 100) : priorityFromScore(bounded), narrative: scoreNarrative(label, bounded, statusFromScore(statusValue)) }; }
export class FundingIntelligence implements C.FundingIntelligence {
  composeScores({ baseline, diversification, risks, topOpportunities }: Parameters<C.FundingIntelligence["composeScores"]>[0]) {
    const coverage = clamp((baseline.securedFunding + baseline.pipelineFunding * baseline.grantWinRate) / Math.max(1, baseline.annualFundingNeed) * 100);
    const healthScore = score("funding-health", "Funding health", coverage * 0.3 + diversification.index * 25 + clamp(baseline.cashRunwayMonths / 18 * 100) * 0.2 + baseline.complianceReadiness * 0.15 + baseline.proposalCapacity * 0.1);
    const opportunityScore = score("funding-opportunity", "Funding opportunity", clamp(topOpportunities.reduce((s, o) => s + o.score, 0) / Math.max(1, topOpportunities.length) * 0.65 + Math.min(35, topOpportunities.length * 3)));
    const riskValue = clamp(risks.reduce((s, r) => s + r.score, 0) / Math.max(1, risks.length));
    return { healthScore, opportunityScore, riskScore: score("funding-risk", "Funding risk", riskValue, true) };
  }
}
export class FundingHealth implements C.FundingHealth { assess({ baseline, scores, diversification }: Parameters<C.FundingHealth["assess"]>[0]): T.FundingHealthResult { const coverage = clamp((baseline.securedFunding + baseline.pipelineFunding * baseline.grantWinRate) / baseline.annualFundingNeed * 100); const dimensions = { coverage, diversification: diversification.index * 100, runway: clamp(baseline.cashRunwayMonths / 18 * 100), compliance: baseline.complianceReadiness, capacity: baseline.proposalCapacity }; return { overallScore: scores.healthScore.value, status: scores.healthScore.status, dimensions, lenses, narrative: `Funding health is ${scores.healthScore.status}; coverage is ${Math.round(coverage)}% and runway is ${baseline.cashRunwayMonths} months.` }; } }
export class FundingDashboard implements C.FundingDashboard { compose({ baseline, scores, now }: Parameters<C.FundingDashboard["compose"]>[0]): T.FundingDashboardResult { const gap = Math.max(0, baseline.annualFundingNeed - baseline.securedFunding); return { generatedAt: now.toISOString(), healthScore: scores.healthScore.value, opportunityScore: scores.opportunityScore.value, riskScore: scores.riskScore.value, fundingGap: gap, status: scores.healthScore.status, headline: `${scores.healthScore.status} funding position with a $${gap.toLocaleString()} unsecured need`, narrative: `Funding health is ${Math.round(scores.healthScore.value)} with opportunity at ${Math.round(scores.opportunityScore.value)} and risk at ${Math.round(scores.riskScore.value)}.` }; } }
export class GrantPipelineDashboard implements C.GrantPipelineDashboard { build({ pipeline, baseline, now }: Parameters<C.GrantPipelineDashboard["build"]>[0]): T.GrantPipelineDashboardResult { const s = statusFromScore(clamp(pipeline.weightedPipeline / Math.max(1, baseline.annualFundingNeed - baseline.securedFunding) * 100)); return { generatedAt: now.toISOString(), opportunityCount: pipeline.opportunities.length, totalPipeline: pipeline.totalPipeline, weightedPipeline: pipeline.weightedPipeline, winRate: baseline.grantWinRate, status: s, narrative: pipeline.narrative }; } }
export class CapitalStrategyDashboard implements C.CapitalStrategyDashboard { build({ capitalPlan, runway, now }: Parameters<C.CapitalStrategyDashboard["build"]>[0]): T.CapitalStrategyDashboardResult { return { generatedAt: now.toISOString(), capitalNeed: capitalPlan.capitalNeed, secured: capitalPlan.secured, gap: capitalPlan.gap, runwayMonths: runway.months, status: runway.status, narrative: `${capitalPlan.narrative} ${runway.narrative}` }; } }
export class FundingDiversificationDashboard implements C.FundingDiversificationDashboard { build({ diversification, now }: Parameters<C.FundingDiversificationDashboard["build"]>[0]): T.FundingDiversificationDashboardResult { return { generatedAt: now.toISOString(), index: diversification.index, concentrationRisk: diversification.concentrationRisk, sourceCount: diversification.mix.filter((m) => m.amount > 0).length, status: diversification.status, narrative: diversification.narrative }; } }
export class FundingRiskDashboard implements C.FundingRiskDashboard { build({ risks, riskScore, now }: Parameters<C.FundingRiskDashboard["build"]>[0]): T.FundingRiskDashboardResult { return { generatedAt: now.toISOString(), riskScore: riskScore.value, criticalRisks: risks.filter((r) => r.band === "critical" || r.band === "high").length, risks, status: riskScore.status, narrative: `${risks.length} funding risks are active; ${risks.filter((r) => r.band === "critical" || r.band === "high").length} require executive attention.` }; } }
export class FundingCalendarComposer implements C.FundingCalendarComposer { compose({ events, now }: Parameters<C.FundingCalendarComposer["compose"]>[0]): T.FundingCalendarResult { const sorted = [...events].sort((a, b) => a.date.localeCompare(b.date)); return { generatedAt: now.toISOString(), events: sorted, nextDeadline: sorted.find((e) => e.date >= now.toISOString())?.date ?? null, narrative: `${sorted.length} grant milestones are scheduled; the next deadline is ${sorted[0]?.date ?? "not yet established"}.` }; } }
export class ExecutiveFundingBriefGenerator implements C.ExecutiveFundingBriefGenerator {
  constructor(private readonly createId: Id = (p) => `${p}-${Date.now()}`) {}
  generate({ request, baseline, scores, topOpportunities, risks, confidence, now }: Parameters<C.ExecutiveFundingBriefGenerator["generate"]>[0]): T.ExecutiveFundingBrief { const gap = Math.max(0, baseline.annualFundingNeed - baseline.securedFunding); return { id: this.createId("fund-brief"), title: "Executive Funding Brief", generatedAt: now.toISOString(), periodLabel: request.periodLabel ?? now.toLocaleString("en-US", { month: "long", year: "numeric" }), headline: `${scores.healthScore.status} funding posture: close a $${gap.toLocaleString()} gap through ${topOpportunities.length} priority opportunities`, fundingSummary: `$${baseline.securedFunding.toLocaleString()} of $${baseline.annualFundingNeed.toLocaleString()} is secured.`, opportunitySummary: `${topOpportunities.length} cross-channel opportunities have been ranked.`, riskSummary: `${risks.filter((r) => r.band === "critical" || r.band === "high").length} elevated risks need action.`, sustainabilitySummary: `Runway is ${baseline.cashRunwayMonths} months and diversification is ${Math.round(baseline.diversificationIndex * 100)}%.`, missionSummary: "Priorities favor non-dilutive and mission-aligned capital before control-sensitive sources.", decisionsNeeded: ["Approve source mix targets", "Authorize top proposal pursuits", "Set runway trigger thresholds"], watchItems: risks.slice(0, 3).map((r) => r.title), confidence }; }
}
export class TopOpportunityAggregator implements C.TopOpportunityAggregator {
  aggregate(input: Parameters<C.TopOpportunityAggregator["aggregate"]>[0]): T.TopOpportunityRecord[] {
    const groups: Array<[T.FundingSourceKind, T.FundingRecordBase[]]> = [["government", input.government], ["grant", input.grants], ["contract", input.contracts], ["philanthropy", input.philanthropy], ["investment", input.investment], ["alternative", input.alternative]];
    return groups.flatMap(([source, records]) => records.map((r) => ({ ...r, source, sourceId: r.id }))).sort((a, b) => (b.score * 0.6 + b.amount / 100_000) - (a.score * 0.6 + a.amount / 100_000)).slice(0, 12);
  }
}
export class ProposalPriorityAggregator implements C.ProposalPriorityAggregator {
  aggregate({ grants, bids }: Parameters<C.ProposalPriorityAggregator["aggregate"]>[0]): T.ProposalPriorityRecord[] { const grantRows = grants.map((g) => ({ ...g, source: "grant" as const, sourceId: g.opportunityId, effort: g.effortScore, probability: g.probability })); const bidRows = bids.map((b) => ({ ...b, source: "contract" as const, sourceId: b.opportunityId, effort: clamp(100 - b.score), probability: b.winProbability })); return [...grantRows, ...bidRows].sort((a, b) => b.probability * b.amount - a.probability * a.amount); }
}
export function defaultFundingConfidence(baseline: T.FundingBaseline, hasDna: boolean, hasOios: boolean): T.FundingConfidenceScore { return buildConfidence([{ key: "baseline", label: "Financial baseline", contribution: baseline.annualFundingNeed > 0 ? 0.78 : 0.3 }, { key: "dna", label: "Organizational DNA", contribution: hasDna ? 0.9 : 0.4 }, { key: "oios", label: "OIOS health", contribution: hasOios ? 0.88 : 0.45 }, { key: "pipeline", label: "Pipeline evidence", contribution: clamp01(baseline.pipelineFunding / Math.max(1, baseline.annualFundingNeed)) }]); }
