/** Funding mix, diversification, risk, runway, scenario, and capital strategy. */
import type * as C from "@/lib/platform/intelligence/funding/contracts";
import { buildLenses, clamp, clamp01, priorityFromRisk, priorityFromScore, statusFromScore } from "@/lib/platform/intelligence/funding/models";
import type * as T from "@/lib/platform/intelligence/funding/types";
type Id = (prefix: string) => string;
const lenses = buildLenses({ availableFunding: "The mix targets enough capital to close the annual gap.", diversification: "No single source should dominate the portfolio.", fundingRisk: "Concentration, runway, restrictions, and execution are actively managed.", sustainability: "Recurring and renewable sources support durable operations.", missionImpact: "Funding choices preserve mission control and outcome commitments." });
const shares = (b: T.FundingBaseline): Array<[T.FundingSourceKind, number]> => [["government", b.governmentShare], ["grant", Math.max(0.05, b.restrictedShare * 0.35)], ["contract", b.contractShare], ["philanthropy", b.philanthropyShare], ["investment", b.investmentShare], ["alternative", b.alternativeShare]];
function mix(b: T.FundingBaseline, id: Id): T.FundingMixRecord[] {
  const raw = shares(b); const total = raw.reduce((s, x) => s + x[1], 0);
  return raw.map(([source, share]) => { const normalized = share / Math.max(0.01, total); const target = source === "alternative" ? 0.1 : 0.18; return { id: id(`mix-${source}`), source, amount: Math.round(b.annualFundingNeed * normalized), sharePct: normalized, targetSharePct: target, priority: priorityFromScore(clamp(100 - Math.abs(normalized - target) * 200)), lenses, narrative: `${source} represents ${Math.round(normalized * 100)}% of the modeled funding mix.` }; });
}
export class FundingMixOptimization implements C.FundingMixOptimization {
  constructor(private readonly createId: Id = (p) => `${p}-${Date.now()}`) {}
  optimize({ baseline }: C.BaselineInput): T.FundingMixOptimizationResult { const current = mix(baseline, this.createId); const recommended = current.map((x) => ({ ...x, id: this.createId(`target-${x.source}`), sharePct: x.targetSharePct, amount: Math.round(baseline.annualFundingNeed * x.targetSharePct), narrative: `Target ${x.source} at ${Math.round(x.targetSharePct * 100)}% to improve portfolio balance.` })); return { current, recommended, expectedRiskReduction: clamp(baseline.concentrationRisk * 35, 4, 28), expectedFundingIncrease: Math.round(Math.max(0, baseline.annualFundingNeed - baseline.securedFunding) * 0.25), lenses, narrative: "Rebalancing toward contracts, grants, and alternative sources reduces concentration while preserving mission control." }; }
}
export class DiversificationAnalysis implements C.FundingDiversification { analyze({ baseline, mix: records }: Parameters<C.FundingDiversification["analyze"]>[0]): T.FundingDiversificationResult { const maxShare = Math.max(...records.map((r) => r.sharePct)); const index = clamp01((baseline.diversificationIndex + (1 - maxShare)) / 2); return { index, status: statusFromScore(index * 100), mix: records, concentrationRisk: clamp01(1 - index), recommendations: ["Cap any single source near 30%", "Build at least three renewable funding channels", "Increase unrestricted and contract funding"], lenses, narrative: `Funding diversification is ${statusFromScore(index * 100)} at ${Math.round(index * 100)}%; largest-source concentration is ${Math.round(maxShare * 100)}%.` }; } }
export { DiversificationAnalysis as FundingDiversification };
export class FundingRiskAnalysis implements C.FundingRiskAnalysis {
  constructor(private readonly createId: Id = (p) => `${p}-${Date.now()}`) {}
  analyze({ baseline, diversification }: Parameters<C.FundingRiskAnalysis["analyze"]>[0]): T.FundingRiskRecord[] { const risks: Array<[string, number, string[]]> = [["Funding concentration", diversification.concentrationRisk, ["Rebalance source targets", "Set concentration limits"]], ["Cash runway", clamp01((12 - baseline.cashRunwayMonths) / 12), ["Stage spending", "Secure bridge capital"]], ["Restricted funding", baseline.restrictedShare, ["Recover indirect costs", "Grow unrestricted sources"]], ["Proposal capacity", clamp01(1 - baseline.proposalCapacity / 100), ["Create bid calendar", "Add proposal capacity"]]]; return risks.map(([title, score, mitigations]) => ({ id: this.createId("fund-risk"), title, score: score * 100, band: priorityFromRisk(score), drivers: [title, "Baseline signal"], mitigations, lenses, narrative: `${title} risk is ${Math.round(score * 100)} and requires ${mitigations[0].toLowerCase()}.` })); }
}
export class FundingScenarioPlanning implements C.FundingScenarioPlanning {
  constructor(private readonly createId: Id = (p) => `${p}-${Date.now()}`) {}
  plan({ baseline }: Parameters<C.FundingScenarioPlanning["plan"]>[0]): T.FundingScenarioPlan[] { return [{ id: this.createId("scenario"), name: "Base plan", fundingDelta: 0, runwayDeltaMonths: 0, risk: "medium", actions: ["Execute prioritized pipeline", "Review monthly"], lenses, narrative: "Base plan converts the weighted pipeline while maintaining monthly controls." }, { id: this.createId("scenario"), name: "Downside protection", fundingDelta: -Math.round(baseline.pipelineFunding * 0.3), runwayDeltaMonths: -3, risk: "high", actions: ["Trigger expense gates", "Activate bridge sources"], lenses, narrative: "Downside plan protects mission delivery if awards slip by one quarter." }, { id: this.createId("scenario"), name: "Accelerated growth", fundingDelta: Math.round(baseline.pipelineFunding * 0.35), runwayDeltaMonths: 5, risk: "low", actions: ["Advance highest-fit proposals", "Stage growth capital"], lenses, narrative: "Accelerated plan funds priority growth milestones without excessive concentration." }]; }
}
export class CashRunwayOptimization implements C.CashRunwayOptimization { analyze({ baseline }: C.BaselineInput): T.CashRunwayResult { const monthlyBurn = Math.round(Math.max(1, baseline.annualFundingNeed - baseline.securedFunding) / 12); const gap = Math.max(0, baseline.annualFundingNeed - baseline.securedFunding - baseline.pipelineFunding * baseline.grantWinRate); return { months: baseline.cashRunwayMonths, monthlyBurn, fundingGap: Math.round(gap), status: statusFromScore(clamp(baseline.cashRunwayMonths / 18 * 100)), lenses, narrative: `Cash runway is ${baseline.cashRunwayMonths} months; the risk-adjusted funding gap is $${Math.round(gap).toLocaleString()}.` }; } }
export class CapitalPlanning implements C.CapitalPlanning { plan({ baseline, mix: records }: Parameters<C.CapitalPlanning["plan"]>[0]): T.CapitalPlanResult { const gap = Math.max(0, baseline.annualFundingNeed - baseline.securedFunding); return { capitalNeed: baseline.annualFundingNeed, secured: baseline.securedFunding, gap, milestones: ["Close near-term operating gap", "Fund delivery capacity", "Build 12–18 month reserve"], sources: records, lenses, narrative: `Capital plan requires $${baseline.annualFundingNeed.toLocaleString()}, with $${baseline.securedFunding.toLocaleString()} secured and a $${gap.toLocaleString()} gap.` }; } }
export class FundingStrategyEngine implements C.FundingStrategyEngine {
  private readonly optimization: FundingMixOptimization; private readonly diversification = new DiversificationAnalysis(); private readonly risk: FundingRiskAnalysis; private readonly scenarios: FundingScenarioPlanning; private readonly runway = new CashRunwayOptimization(); private readonly capital = new CapitalPlanning();
  constructor({ createId = (p: string) => `${p}-${Date.now()}` }: { createId?: Id } = {}) { this.optimization = new FundingMixOptimization(createId); this.risk = new FundingRiskAnalysis(createId); this.scenarios = new FundingScenarioPlanning(createId); }
  run(input: C.BaselineInput) { const mixOptimization = this.optimization.optimize(input); const mixRecords = mixOptimization.current; const diversification = this.diversification.analyze({ ...input, mix: mixRecords }); const risks = this.risk.analyze({ ...input, diversification }); return { mix: mixRecords, mixOptimization, diversification, risks, scenarios: this.scenarios.plan({ ...input, risks }), runway: this.runway.analyze(input), capitalPlan: this.capital.plan({ ...input, mix: mixRecords }) }; }
}
