/** Investment and financing intelligence suite. */
import type * as C from "@/lib/platform/intelligence/funding/contracts";
import { buildLenses, clamp, priorityFromScore } from "@/lib/platform/intelligence/funding/models";
import type * as T from "@/lib/platform/intelligence/funding/types";
type Id = (prefix: string) => string;
const lens = buildLenses({ availableFunding: "Investment capital accelerates scalable growth.", diversification: "Equity and debt add capital beyond grants and contracts.", fundingRisk: "Dilution, repayment, control, and return expectations are surfaced.", sustainability: "Capital is matched to milestones and repayment capacity.", missionImpact: "Mission protections remain explicit in financing terms." });
function base(input: C.BaselineInput, id: Id, prefix: string, name: string, share: number): T.FundingRecordBase { const score = clamp(input.baseline.financialScore * 0.5 + input.baseline.revenueHealthProxy * 0.35 + 8); const amount = Math.round(input.baseline.annualFundingNeed * share); return { id: id(prefix), name, amount, score, priority: priorityFromScore(100 - score), eligibility: ["for_profit", "startup", "school"], lenses: lens, narrative: `${name} capacity is approximately $${amount.toLocaleString()} at a ${Math.round(score)} financing-readiness score.` }; }
class Base { constructor(protected readonly createId: Id = (p) => `${p}-${Date.now()}`) {} }
export class AngelInvestors extends Base implements C.AngelInvestors { analyze(input: C.BaselineInput): T.AngelInvestorRecord[] { const b = base(input, this.createId, "angel", "Education impact angel network", 0.08); return [{ ...b, sectorFit: clamp(b.score + 8), checkSize: b.amount }]; } }
export class VentureCapital extends Base implements C.VentureCapital { analyze(input: C.BaselineInput): T.VentureCapitalRecord[] { return [{ ...base(input, this.createId, "vc", "Education technology growth fund", 0.25), stage: "Seed to Series A", thesisFit: clamp(input.baseline.revenueHealthProxy + 5) }]; } }
export class PrivateEquity extends Base implements C.PrivateEquity { analyze(input: C.BaselineInput): T.PrivateEquityRecord[] { return [{ ...base(input, this.createId, "pe", "Education services growth partner", 0.35), strategy: "Growth equity", controlPreference: false }]; } }
export class StrategicInvestors extends Base implements C.StrategicInvestors { analyze(input: C.BaselineInput): T.StrategicInvestorRecord[] { return [{ ...base(input, this.createId, "strategic", "Learning platform strategic partner", 0.16), strategicValue: "Distribution, technology, and employer access" }]; } }
export class DebtFinancing extends Base implements C.DebtFinancing { analyze(input: C.BaselineInput): T.DebtFinancingRecord[] { return [{ ...base(input, this.createId, "debt", "Mission-aligned working capital facility", 0.12), interestRate: 0.072 + (100 - input.baseline.financialScore) / 1000, termMonths: 36 }]; } }
export class RevenueBasedFinancing extends Base implements C.RevenueBasedFinancing { analyze(input: C.BaselineInput): T.RevenueBasedFinancingRecord[] { const b = base(input, this.createId, "rbf", "Revenue-based growth facility", 0.1); return [{ ...b, revenueSharePct: 0.06, repaymentCap: Math.round(b.amount * 1.45) }]; } }
