/** Philanthropic funding intelligence suite. */
import type * as C from "@/lib/platform/intelligence/funding/contracts";
import { buildLenses, clamp, priorityFromScore } from "@/lib/platform/intelligence/funding/models";
import type * as T from "@/lib/platform/intelligence/funding/types";
type Id = (prefix: string) => string;
const lens = buildLenses({ availableFunding: "Relationship-led giving expands flexible capital.", diversification: "Donor and foundation channels reduce single-funder exposure.", fundingRisk: "Cultivation, restriction, and donor concentration are monitored.", sustainability: "Stewardship and renewal design improve lifetime value.", missionImpact: "Giving is tied to visible learner and community outcomes." });
function base(input: C.BaselineInput, id: Id, prefix: string, name: string, share: number): T.FundingRecordBase { const score = clamp(input.baseline.organizationHealthScore * 0.45 + input.baseline.proposalCapacity * 0.35 + 15); const amount = Math.round(input.baseline.annualFundingNeed * share); return { id: id(prefix), name, amount, score, priority: priorityFromScore(100 - score), eligibility: ["nonprofit", "school", "foundation"], lenses: lens, narrative: `${name} could provide $${amount.toLocaleString()} with ${Math.round(score)}% relationship readiness.` }; }
class Base { constructor(protected readonly createId: Id = (p) => `${p}-${Date.now()}`) {} }
export class FoundationMatching extends Base implements C.FoundationMatching { analyze(input: C.BaselineInput): T.FoundationMatchRecord[] { return [{ ...base(input, this.createId, "foundation", "Learning Equity Foundation", 0.12), foundationType: "private", missionFit: clamp(input.baseline.organizationHealthScore + 8) }]; } }
export class MajorDonorInsights extends Base implements C.MajorDonorInsights { analyze(input: C.BaselineInput): T.MajorDonorInsightRecord[] { return [{ ...base(input, this.createId, "donor", "Leadership donor cohort", 0.07), segment: "Major donors", engagementScore: clamp(input.baseline.proposalCapacity + 6) }]; } }
export class CorporateGiving extends Base implements C.CorporateGiving { analyze(input: C.BaselineInput): T.CorporateGivingRecord[] { return [{ ...base(input, this.createId, "corporate-giving", "Regional employer education fund", 0.06), corporation: "Employer coalition", givingProgram: "Education and workforce" }]; } }
export class FamilyFoundations extends Base implements C.FamilyFoundations { analyze(input: C.BaselineInput): T.FamilyFoundationRecord[] { return [{ ...base(input, this.createId, "family-foundation", "Family legacy education fund", 0.05), family: "Regional philanthropic family", relationshipStrength: clamp(input.baseline.organizationHealthScore - 5) }]; } }
export class CommunityFoundations extends Base implements C.CommunityFoundations { analyze(input: C.BaselineInput): T.CommunityFoundationRecord[] { return [{ ...base(input, this.createId, "community-foundation", "Community opportunity fund", 0.05), geography: "Service region", communityFit: clamp(input.baseline.organizationHealthScore + 10) }]; } }
export class CapitalCampaignPlanning extends Base implements C.CapitalCampaignPlanning { plan(input: C.BaselineInput): T.CapitalCampaignPlan[] { const goal = Math.round(Math.max(0, input.baseline.annualFundingNeed - input.baseline.securedFunding) * 1.4); return [{ ...base(input, this.createId, "campaign", "Mission growth capital campaign", goal / input.baseline.annualFundingNeed), amount: goal, goal, durationMonths: 24, phases: ["Readiness", "Quiet phase", "Public phase", "Stewardship"], narrative: `A 24-month campaign targets $${goal.toLocaleString()} using readiness, quiet, public, and stewardship phases.` }]; } }
