/**
 * Board & Governance Intelligence — shared types / GovernanceModels DTOs (Sprint 029).
 *
 * Governance layer that converts Executive Intelligence into board-ready reporting,
 * strategic oversight, compliance monitoring, and governance workflows.
 */

import type { ExecutiveDecisionResult } from "@/lib/platform/intelligence/executive-decision/types";
import type {
  Graph,
  GraphAnalysisResult,
  GraphBuildInput,
  GraphScope,
} from "@/lib/platform/intelligence/executive-graph/types";
import type { PredictionResult } from "@/lib/platform/intelligence/predictive-intelligence/types";

/** Semantic version of the Board & Governance Intelligence pack. */
export const BOARD_GOVERNANCE_INTELLIGENCE_VERSION = "0.1.0";

/** Opaque metadata — never use `any`. */
export type GovernanceMetadata = Record<string, unknown>;

/** Re-export graph scope for governance records. */
export type { GraphScope };

/** Packet / report kinds generated by Board Intelligence. */
export const BOARD_PACKET_KINDS = [
  "monthly_board_packet",
  "quarterly_strategic_review",
  "executive_kpi_summary",
  "financial_summary",
  "risk_heat_map",
  "strategic_initiative_status",
  "governance_dashboard",
  "mission_scorecard",
  "compliance_summary",
  "executive_briefing",
] as const;
export type BoardPacketKind = (typeof BOARD_PACKET_KINDS)[number];

/** Governance confidence bands. */
export const GOVERNANCE_CONFIDENCE_LEVELS = [
  "high",
  "medium",
  "low",
  "unknown",
] as const;
export type GovernanceConfidenceLevel =
  (typeof GOVERNANCE_CONFIDENCE_LEVELS)[number];

/** Priority / severity bands used across board artifacts. */
export const GOVERNANCE_PRIORITY_BANDS = [
  "critical",
  "high",
  "medium",
  "low",
  "monitor",
] as const;
export type GovernancePriorityBand = (typeof GOVERNANCE_PRIORITY_BANDS)[number];

/** Lifecycle statuses for governance artifacts. */
export const GOVERNANCE_ARTIFACT_STATUSES = [
  "draft",
  "generated",
  "reviewed",
  "distributed",
  "archived",
  "superseded",
] as const;
export type GovernanceArtifactStatus =
  (typeof GOVERNANCE_ARTIFACT_STATUSES)[number];

/** Committee types for board oversight. */
export const GOVERNANCE_COMMITTEE_KINDS = [
  "full_board",
  "finance",
  "academic",
  "governance",
  "audit",
  "advancement",
  "executive",
  "risk",
] as const;
export type GovernanceCommitteeKind =
  (typeof GOVERNANCE_COMMITTEE_KINDS)[number];

/** Strategic initiative statuses. */
export const STRATEGIC_INITIATIVE_STATUSES = [
  "planned",
  "active",
  "at_risk",
  "blocked",
  "completed",
  "deferred",
] as const;
export type StrategicInitiativeStatus =
  (typeof STRATEGIC_INITIATIVE_STATUSES)[number];

/** Risk register statuses. */
export const RISK_REGISTER_STATUSES = [
  "open",
  "mitigating",
  "monitoring",
  "accepted",
  "closed",
] as const;
export type RiskRegisterStatus = (typeof RISK_REGISTER_STATUSES)[number];

/** Compliance monitor statuses. */
export const COMPLIANCE_STATUSES = [
  "compliant",
  "at_risk",
  "non_compliant",
  "unknown",
] as const;
export type ComplianceStatus = (typeof COMPLIANCE_STATUSES)[number];

/** Resolution tracker statuses. */
export const RESOLUTION_STATUSES = [
  "proposed",
  "adopted",
  "in_progress",
  "completed",
  "deferred",
  "rescinded",
] as const;
export type ResolutionStatus = (typeof RESOLUTION_STATUSES)[number];

/** Calendar event kinds. */
export const GOVERNANCE_CALENDAR_EVENT_KINDS = [
  "board_meeting",
  "committee_meeting",
  "packet_deadline",
  "compliance_deadline",
  "strategic_review",
  "resolution_follow_up",
] as const;
export type GovernanceCalendarEventKind =
  (typeof GOVERNANCE_CALENDAR_EVENT_KINDS)[number];

/** Calibrated governance confidence. */
export interface GovernanceConfidenceScore {
  value: number;
  level: GovernanceConfidenceLevel;
  factors: Array<{ key: string; label: string; contribution: number }>;
}

/** Board KPI row for scorecards / dashboards. */
export interface BoardKpi {
  id: string;
  key: string;
  label: string;
  domain: string;
  value: number;
  target: number | null;
  priorValue: number | null;
  unit: string | null;
  trend: "up" | "down" | "flat";
  status: GovernancePriorityBand;
  narrative: string;
}

/** Executive scorecard section. */
export interface ExecutiveScorecard {
  id: string;
  title: string;
  ownerRole: string;
  periodLabel: string;
  overallScore: number;
  status: GovernancePriorityBand;
  kpis: BoardKpi[];
  highlights: string[];
  concerns: string[];
  recommendations: string[];
}

/** Risk register entry. */
export interface RiskRegisterEntry {
  id: string;
  title: string;
  category: string;
  likelihood: number;
  impact: number;
  score: number;
  heat: GovernancePriorityBand;
  status: RiskRegisterStatus;
  owner: string;
  mitigation: string;
  residualRisk: number;
  relatedDomains: string[];
  narrative: string;
}

/** Compliance monitor item. */
export interface ComplianceItem {
  id: string;
  area: string;
  requirement: string;
  status: ComplianceStatus;
  score: number;
  dueAt: string | null;
  owner: string;
  findings: string[];
  actions: string[];
  narrative: string;
}

/** Strategic initiative tracked for board oversight. */
export interface StrategicInitiative {
  id: string;
  title: string;
  description: string;
  owner: string;
  status: StrategicInitiativeStatus;
  progressPct: number;
  targetDate: string | null;
  priority: GovernancePriorityBand;
  budgetImpact: number | null;
  kpiKeys: string[];
  blockers: string[];
  nextMilestone: string | null;
  narrative: string;
}

/** Board resolution / action item. */
export interface BoardResolution {
  id: string;
  title: string;
  description: string;
  status: ResolutionStatus;
  adoptedAt: string | null;
  dueAt: string | null;
  owner: string;
  committee: GovernanceCommitteeKind;
  relatedInitiativeIds: string[];
  progressPct: number;
  narrative: string;
}

/** Committee report section. */
export interface CommitteeReport {
  id: string;
  committee: GovernanceCommitteeKind;
  title: string;
  periodLabel: string;
  summary: string;
  decisionsNeeded: string[];
  risks: string[];
  kpiHighlights: BoardKpi[];
  recommendations: string[];
  confidence: GovernanceConfidenceScore;
}

/** Governance calendar event. */
export interface GovernanceCalendarEvent {
  id: string;
  kind: GovernanceCalendarEventKind;
  title: string;
  scheduledAt: string;
  committee: GovernanceCommitteeKind | null;
  relatedArtifactIds: string[];
  narrative: string;
}

/** Risk heat map cell. */
export interface RiskHeatMapCell {
  likelihoodBand: "low" | "medium" | "high";
  impactBand: "low" | "medium" | "high";
  count: number;
  riskIds: string[];
}

/** Board packet section. */
export interface BoardPacketSection {
  id: string;
  kind: BoardPacketKind | "custom";
  title: string;
  summary: string;
  highlights: string[];
  metrics: Record<string, number | string | null>;
  priority: GovernancePriorityBand;
}

/** Full board packet artifact. */
export interface BoardPacket {
  id: string;
  kind: BoardPacketKind;
  title: string;
  periodLabel: string;
  generatedAt: string;
  status: GovernanceArtifactStatus;
  scope: GraphScope;
  sections: BoardPacketSection[];
  kpis: BoardKpi[];
  risks: RiskRegisterEntry[];
  initiatives: StrategicInitiative[];
  compliance: ComplianceItem[];
  resolutions: BoardResolution[];
  committees: CommitteeReport[];
  scorecards: ExecutiveScorecard[];
  calendar: GovernanceCalendarEvent[];
  confidence: GovernanceConfidenceScore;
  summary: string;
  recommendations: string[];
  metadata?: GovernanceMetadata;
}

/** Executive brief (short-form board / leadership briefing). */
export interface ExecutiveBrief {
  id: string;
  title: string;
  generatedAt: string;
  periodLabel: string;
  headline: string;
  situation: string;
  financialSummary: string;
  missionSummary: string;
  riskSummary: string;
  initiativeSummary: string;
  decisionsNeeded: string[];
  watchItems: string[];
  confidence: GovernanceConfidenceScore;
}

/** Governance dashboard projection. */
export interface GovernanceDashboardView {
  generatedAt: string;
  headline: string;
  overallGovernanceScore: number;
  status: GovernancePriorityBand;
  missionScore: number;
  complianceScore: number;
  riskScore: number;
  initiativeHealth: number;
  openResolutions: number;
  criticalRisks: number;
  upcomingEvents: GovernanceCalendarEvent[];
  topKpis: BoardKpi[];
  alerts: string[];
}

/** Board KPI dashboard projection. */
export interface BoardKpiDashboardView {
  generatedAt: string;
  periodLabel: string;
  overallScore: number;
  kpis: BoardKpi[];
  byDomain: Array<{ domain: string; averageScore: number; count: number }>;
  trendingUp: string[];
  trendingDown: string[];
}

/** Governance projection (UI / packet flatten). */
export interface GovernanceProjectionResult {
  generatedAt: string;
  headline: string;
  packetKinds: BoardPacketKind[];
  dashboard: GovernanceDashboardView;
  kpiDashboard: BoardKpiDashboardView;
  brief: ExecutiveBrief;
  heatMap: RiskHeatMapCell[];
  metrics: {
    packetCount: number;
    riskCount: number;
    initiativeCount: number;
    complianceCount: number;
    resolutionCount: number;
    committeeCount: number;
  };
  overallConfidence: GovernanceConfidenceScore;
}

/** Board query request. */
export interface BoardQueryRequest {
  question: string;
  focus?:
    | "packet"
    | "risk"
    | "compliance"
    | "initiative"
    | "resolution"
    | "kpi"
    | "calendar"
    | "brief"
    | "general";
  maxResults?: number;
  committee?: GovernanceCommitteeKind;
  packetKind?: BoardPacketKind;
}

/** Board query answer. */
export interface BoardQueryResult {
  question: string;
  focus: NonNullable<BoardQueryRequest["focus"]>;
  answer: string;
  references: string[];
  confidence: GovernanceConfidenceScore;
}

/** Baseline signals used when upstream modules are sparse. */
export interface GovernanceBaseline {
  enrollment: number;
  revenue: number;
  cashFlow: number;
  expense: number;
  organizationHealthScore: number;
  financialHealthScore: number;
  founderHealthScore: number;
  missionScore: number;
  complianceScore: number;
  riskScore: number;
  executiveKpi: number;
  initiativeProgress: number;
  openResolutions: number;
}

/** History / audit record. */
export interface GovernanceHistoryRecord {
  id: string;
  requestId: string;
  generatedAt: string;
  status: GovernanceArtifactStatus;
  packetIds: string[];
  summary: string;
  scope: GraphScope;
  confidence: GovernanceConfidenceScore;
}

/** Primary governance generation request. */
export interface GovernanceRequest {
  requestId: string;
  question?: string;
  periodLabel?: string;
  packetKinds?: BoardPacketKind[];
  scope?: GraphScope;
  graph?: Graph;
  analysis?: GraphAnalysisResult;
  graphInput?: GraphBuildInput;
  decisionResult?: ExecutiveDecisionResult;
  predictionResult?: PredictionResult;
  baselineOverrides?: Partial<GovernanceBaseline>;
  initiatives?: StrategicInitiative[];
  resolutions?: BoardResolution[];
  complianceItems?: ComplianceItem[];
  risks?: RiskRegisterEntry[];
  calendarEvents?: GovernanceCalendarEvent[];
  maxRisks?: number;
  maxInitiatives?: number;
  metadata?: GovernanceMetadata;
}

/** Full governance generation result. */
export interface GovernanceResult {
  requestId: string;
  version: string;
  generatedAt: string;
  periodLabel: string;
  scope: GraphScope;
  packets: BoardPacket[];
  brief: ExecutiveBrief;
  dashboard: GovernanceDashboardView;
  kpiDashboard: BoardKpiDashboardView;
  heatMap: RiskHeatMapCell[];
  scorecards: ExecutiveScorecard[];
  risks: RiskRegisterEntry[];
  initiatives: StrategicInitiative[];
  compliance: ComplianceItem[];
  resolutions: BoardResolution[];
  committees: CommitteeReport[];
  calendar: GovernanceCalendarEvent[];
  projection: GovernanceProjectionResult;
  confidence: GovernanceConfidenceScore;
  historyRecord: GovernanceHistoryRecord;
  recommendations: string[];
}
