import type { JagCapabilityBinding, JagHierarchyNodeDefinition } from "@/lib/platform/hierarchy/types";

/** Published JAG Hierarchy reference catalog — organizational backbone for all modules. */
export const JAG_HIERARCHY_REFERENCE_NODES: JagHierarchyNodeDefinition[] = [
  // Foundation
  {
    nodeKey: "jag.vision.2035",
    kind: "vision",
    title: "The JAG 2035 Vision",
    description: "Transform education through precision learning infrastructure.",
    version: "1.0.0",
    status: "published",
    sortOrder: 10,
  },
  {
    nodeKey: "jag.mission.enterprise",
    kind: "mission",
    title: "Enterprise Mission",
    description: "Deliver governed, evidence-based learning at scale for every learner.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.vision.2035",
    sortOrder: 20,
  },
  {
    nodeKey: "jag.core_values.excellence",
    kind: "core_values",
    title: "Excellence",
    description: "Pursue mastery in instruction, operations, and learner outcomes.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.mission.enterprise",
    sortOrder: 30,
  },
  {
    nodeKey: "jag.core_values.integrity",
    kind: "core_values",
    title: "Integrity",
    description: "Govern every action with auditable standards and transparent evidence.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.mission.enterprise",
    sortOrder: 31,
  },
  {
    nodeKey: "jag.core_values.innovation",
    kind: "core_values",
    title: "Innovation",
    description: "Continuously improve through research, intelligence, and measured experimentation.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.mission.enterprise",
    sortOrder: 32,
  },
  {
    nodeKey: "jag.jag_way.structured_literacy",
    kind: "jag_way",
    title: "The JAG Way — Structured Literacy",
    description: "Wilson-aligned structured literacy as the instructional backbone.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.mission.enterprise",
    sortOrder: 40,
    platformRefs: { ulrDomainKey: "domain.structured_literacy" },
  },
  // Governance chain — instruction
  {
    nodeKey: "jag.standard.instructional_excellence",
    kind: "standard",
    title: "Instructional Excellence Standard",
    description: "Governs daily instructional delivery and session quality.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.jag_way.structured_literacy",
    sortOrder: 50,
  },
  {
    nodeKey: "jag.standard.student_success",
    kind: "standard",
    title: "Student Success Standard",
    description: "Governs holistic learner progress monitoring and intervention.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.jag_way.structured_literacy",
    sortOrder: 51,
  },
  {
    nodeKey: "jag.standard.instructional_delivery",
    kind: "standard",
    title: "Instructional Delivery Standard",
    description: "Governs scheduling, placement, and conflict resolution for instructional delivery.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.jag_way.structured_literacy",
    sortOrder: 52,
  },
  {
    nodeKey: "jag.protocol.session_delivery",
    kind: "protocol",
    title: "Session Delivery Protocol",
    description: "Protocol for conducting instructional sessions with readiness checks.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.standard.instructional_excellence",
    sortOrder: 60,
  },
  {
    nodeKey: "jag.protocol.evidence_collection",
    kind: "protocol",
    title: "Evidence Collection Protocol",
    description: "Protocol for capturing and validating learning evidence.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.standard.student_success",
    sortOrder: 61,
  },
  {
    nodeKey: "jag.process.daily_instruction",
    kind: "process",
    title: "Daily Instruction Process",
    description: "End-to-end daily instructional workflow from schedule to documentation.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.protocol.session_delivery",
    sortOrder: 70,
  },
  {
    nodeKey: "jag.process.progress_monitoring",
    kind: "process",
    title: "Progress Monitoring Process",
    description: "Process for recording and reviewing learner progress evidence.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.protocol.evidence_collection",
    sortOrder: 71,
  },
  {
    nodeKey: "jag.procedure.conduct_session",
    kind: "procedure",
    title: "Conduct Instructional Session",
    description: "Executable procedure for delivering a scheduled instructional session.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.process.daily_instruction",
    sortOrder: 80,
    platformRefs: {
      eventType: "platform.workflow.transitioned",
      workflowKey: "ref_student_support_ticket",
    },
  },
  {
    nodeKey: "jag.procedure.record_progress",
    kind: "procedure",
    title: "Record Academic Progress",
    description: "Executable procedure for logging competency progress evidence.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.process.progress_monitoring",
    sortOrder: 81,
    platformRefs: { ulrCompetencyKey: "AW-SL-PA-001-v1.0.0" },
  },
  // Layer reference nodes
  {
    nodeKey: "jag.rule.student_placement",
    kind: "rule",
    title: "Student Placement Rules",
    description: "Rules governing learner placement decisions.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.procedure.record_progress",
    sortOrder: 90,
    platformRefs: { ruleSetKey: "ref_student_placement" },
  },
  {
    nodeKey: "jag.rule.structured_literacy_placement",
    kind: "rule",
    title: "Structured Literacy Placement Rules",
    description: "Rules governing SL tier and competency placement.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.procedure.record_progress",
    sortOrder: 91,
    platformRefs: { ruleSetKey: "ref_structured_literacy_placement" },
  },
  {
    nodeKey: "jag.parameter.session_duration_minutes",
    kind: "parameter",
    title: "Session Duration (minutes)",
    description: "Configurable session block length.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.procedure.conduct_session",
    sortOrder: 100,
    metadata: { defaultValue: 45, min: 15, max: 120 },
  },
  {
    nodeKey: "jag.parameter.mastery_threshold",
    kind: "parameter",
    title: "Mastery Threshold",
    description: "Minimum mastery level required for competency advance.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.procedure.record_progress",
    sortOrder: 101,
    metadata: { defaultValue: 3, min: 1, max: 4 },
  },
  {
    nodeKey: "jag.template.session_plan",
    kind: "template",
    title: "Session Plan Template",
    description: "Standard template for daily session planning.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.procedure.conduct_session",
    sortOrder: 110,
  },
  {
    nodeKey: "jag.playbook.structured_literacy_block",
    kind: "playbook",
    title: "Structured Literacy Block Playbook",
    description: "Step-by-step playbook for SL instructional blocks.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.procedure.conduct_session",
    sortOrder: 120,
    platformRefs: { knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide"] },
  },
  {
    nodeKey: "jag.evidence.observation_record",
    kind: "evidence",
    title: "Observation Evidence",
    description: "Classroom or virtual session observation artifacts.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.protocol.evidence_collection",
    sortOrder: 130,
    platformRefs: { evidenceTypeKey: "observation" },
  },
  {
    nodeKey: "jag.evidence.assessment_result",
    kind: "evidence",
    title: "Assessment Result Evidence",
    description: "Formal assessment and probe results.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.protocol.evidence_collection",
    sortOrder: 131,
    platformRefs: { evidenceTypeKey: "assessment" },
  },
  {
    nodeKey: "jag.knowledge.sl_teacher_guide",
    kind: "knowledge",
    title: "Structured Literacy Teacher Guide",
    description: "Reference knowledge asset for SL instructional delivery.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.playbook.structured_literacy_block",
    sortOrder: 140,
  },
  {
    nodeKey: "jag.intelligence.recommendation_engine",
    kind: "intelligence",
    title: "Recommendation Intelligence",
    description: "Decision and rules-driven recommendation services.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.procedure.record_progress",
    sortOrder: 150,
    platformRefs: {
      decisionTypeKey: "ref_platform_risk_signal",
      intelligenceServiceKeys: ["intelligence.recommendations", "intelligence.graph"],
    },
  },
  {
    nodeKey: "jag.automation.compliance_reminder",
    kind: "automation",
    title: "Compliance Reminder Automation",
    description: "Automated compliance deadline reminders.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.process.daily_instruction",
    sortOrder: 160,
  },
  {
    nodeKey: "jag.execution.workflow_runner",
    kind: "execution",
    title: "Workflow Execution Engine",
    description: "Platform workflow execution runtime.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.process.daily_instruction",
    sortOrder: 170,
    platformRefs: { workflowKey: "ref_hr_onboarding" },
  },
  {
    nodeKey: "jag.outcome.mastery_advancement",
    kind: "outcome",
    title: "Mastery Advancement Outcome",
    description: "Learner advances to next competency upon mastery confirmation.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.procedure.record_progress",
    sortOrder: 180,
  },
  {
    nodeKey: "jag.research.learning_science",
    kind: "research",
    title: "Learning Science Research",
    description: "Evidence-based research informing standards and protocols.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.jag_way.structured_literacy",
    sortOrder: 190,
  },
  {
    nodeKey: "jag.innovation.ai_coaching",
    kind: "innovation",
    title: "AI Coaching Innovation",
    description: "Experimental AI-assisted coaching capabilities.",
    version: "1.0.0",
    status: "published",
    parentKey: "jag.research.learning_science",
    sortOrder: 200,
  },
];

export const JAG_CAPABILITY_BINDINGS: JagCapabilityBinding[] = [
  {
    capabilityKey: "cap.teacher.session_delivery",
    title: "Teacher Session Delivery",
    description: "Deliver a scheduled instructional session in Teacher Workspace.",
    status: "published",
    standardKey: "jag.standard.instructional_excellence",
    protocolKey: "jag.protocol.session_delivery",
    processKey: "jag.process.daily_instruction",
    procedureKey: "jag.procedure.conduct_session",
    ruleSetKeys: ["ref_platform_access_gate"],
    requiredPermissions: ["teacher.view"],
    parameterKeys: ["jag.parameter.session_duration_minutes"],
    evidenceTypeKeys: ["jag.evidence.observation_record"],
    knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide", "jag.playbook.structured_literacy_block"],
    intelligenceServiceKeys: ["intelligence.graph"],
    workflowKey: "ref_student_support_ticket",
    eventType: "platform.workflow.transitioned",
    sortOrder: 10,
  },
  {
    capabilityKey: "cap.teacher.progress_recording",
    title: "Teacher Progress Recording",
    description: "Record learner academic progress with evidence validation.",
    status: "published",
    standardKey: "jag.standard.student_success",
    protocolKey: "jag.protocol.evidence_collection",
    processKey: "jag.process.progress_monitoring",
    procedureKey: "jag.procedure.record_progress",
    ruleSetKeys: ["ref_student_placement", "ref_structured_literacy_placement"],
    requiredPermissions: ["teacher.view"],
    parameterKeys: ["jag.parameter.mastery_threshold"],
    evidenceTypeKeys: ["jag.evidence.observation_record", "jag.evidence.assessment_result"],
    knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide"],
    intelligenceServiceKeys: ["intelligence.recommendations", "intelligence.graph"],
    decisionTypeKey: "ref_platform_risk_signal",
    sortOrder: 20,
  },
  {
    capabilityKey: "cap.paj.evidence_intake",
    title: "PAJ Evidence Intake",
    description: "Hierarchy context for Personal Learning Journey evidence processing.",
    status: "published",
    standardKey: "jag.standard.student_success",
    protocolKey: "jag.protocol.evidence_collection",
    processKey: "jag.process.progress_monitoring",
    procedureKey: "jag.procedure.record_progress",
    ruleSetKeys: ["ref_structured_literacy_placement"],
    requiredPermissions: ["teacher.view"],
    parameterKeys: ["jag.parameter.mastery_threshold"],
    evidenceTypeKeys: ["jag.evidence.assessment_result"],
    knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide"],
    intelligenceServiceKeys: ["intelligence.recommendations"],
    sortOrder: 30,
  },
  {
    capabilityKey: "cap.platform.workflow_execution",
    title: "Platform Workflow Execution",
    description: "Execute a registered platform workflow under hierarchy governance.",
    status: "published",
    standardKey: "jag.standard.instructional_excellence",
    protocolKey: "jag.protocol.session_delivery",
    processKey: "jag.process.daily_instruction",
    procedureKey: "jag.procedure.conduct_session",
    ruleSetKeys: ["ref_platform_access_gate"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: [],
    intelligenceServiceKeys: ["intelligence.graph"],
    workflowKey: "ref_hr_onboarding",
    sortOrder: 40,
  },
  {
    capabilityKey: "cap.admissions.case_review",
    title: "Admissions Case Review",
    description: "Review and advance admissions cases through the enrollment funnel.",
    status: "published",
    standardKey: "jag.standard.student_success",
    protocolKey: "jag.protocol.evidence_collection",
    processKey: "jag.process.progress_monitoring",
    procedureKey: "jag.procedure.record_progress",
    ruleSetKeys: ["ref_platform_access_gate"],
    requiredPermissions: ["admissions.view"],
    parameterKeys: [],
    evidenceTypeKeys: ["jag.evidence.assessment_result"],
    knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide"],
    intelligenceServiceKeys: ["intelligence.recommendations", "intelligence.graph"],
    workflowKey: "ref_hr_onboarding",
    sortOrder: 50,
  },
  {
    capabilityKey: "cap.admissions.enrollment_handoff",
    title: "Admissions Enrollment Handoff",
    description: "Complete enrollment packet and hand off accepted students to SIS.",
    status: "published",
    standardKey: "jag.standard.student_success",
    protocolKey: "jag.protocol.evidence_collection",
    processKey: "jag.process.progress_monitoring",
    procedureKey: "jag.procedure.record_progress",
    ruleSetKeys: ["ref_platform_access_gate", "ref_student_placement"],
    requiredPermissions: ["admissions.accept"],
    parameterKeys: [],
    evidenceTypeKeys: ["jag.evidence.assessment_result"],
    knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide"],
    intelligenceServiceKeys: ["intelligence.graph"],
    sortOrder: 51,
  },
  {
    capabilityKey: "cap.students.record_management",
    title: "Student Record Management",
    description: "Maintain complete and compliant student information records.",
    status: "published",
    standardKey: "jag.standard.student_success",
    protocolKey: "jag.protocol.evidence_collection",
    processKey: "jag.process.progress_monitoring",
    procedureKey: "jag.procedure.record_progress",
    ruleSetKeys: ["ref_platform_access_gate"],
    requiredPermissions: ["students.view"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide"],
    intelligenceServiceKeys: ["intelligence.graph"],
    sortOrder: 52,
  },
  {
    capabilityKey: "cap.students.enrollment_management",
    title: "Student Enrollment Management",
    description: "Process pending enrollments and validate SIS readiness.",
    status: "published",
    standardKey: "jag.standard.student_success",
    protocolKey: "jag.protocol.evidence_collection",
    processKey: "jag.process.progress_monitoring",
    procedureKey: "jag.procedure.record_progress",
    ruleSetKeys: ["ref_student_placement"],
    requiredPermissions: ["students.edit"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide"],
    intelligenceServiceKeys: ["intelligence.recommendations"],
    sortOrder: 53,
  },
  {
    capabilityKey: "cap.scheduling.intelligence",
    title: "Scheduling Intelligence",
    description: "Run capacity analysis, recommendations, and executive scheduling analytics.",
    status: "published",
    standardKey: "jag.standard.instructional_delivery",
    protocolKey: "jag.protocol.evidence_collection",
    processKey: "jag.process.progress_monitoring",
    procedureKey: "jag.procedure.record_progress",
    ruleSetKeys: ["ref_scheduling_block", "ref_teacher_availability"],
    requiredPermissions: ["scheduling.executive"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide"],
    intelligenceServiceKeys: ["intelligence.recommendations"],
    sortOrder: 54,
  },
  {
    capabilityKey: "cap.scheduling.placement",
    title: "Student Placement",
    description: "PAJ and Wilson-informed section placement with JAG capacity rules.",
    status: "published",
    standardKey: "jag.standard.instructional_delivery",
    protocolKey: "jag.protocol.evidence_collection",
    processKey: "jag.process.progress_monitoring",
    procedureKey: "jag.procedure.record_progress",
    ruleSetKeys: ["ref_structured_literacy_placement", "ref_student_placement"],
    requiredPermissions: ["scheduling.manage"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: ["jag.knowledge.sl_teacher_guide"],
    intelligenceServiceKeys: ["intelligence.graph"],
    sortOrder: 55,
  },
  {
    capabilityKey: "cap.scheduling.conflict_resolution",
    title: "Conflict Resolution",
    description: "Resolve scheduling conflicts, emergency coverage, and teacher availability issues.",
    status: "published",
    standardKey: "jag.standard.instructional_delivery",
    protocolKey: "jag.protocol.evidence_collection",
    processKey: "jag.process.progress_monitoring",
    procedureKey: "jag.procedure.record_progress",
    ruleSetKeys: ["ref_teacher_assignment", "ref_teacher_availability"],
    requiredPermissions: ["scheduling.manage"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: [],
    intelligenceServiceKeys: ["intelligence.recommendations"],
    sortOrder: 56,
  },
  {
    capabilityKey: "cap.finance.billing_operations",
    title: "Finance Billing Operations",
    description: "Manage invoices, collections, and billing account operations.",
    status: "published",
    standardKey: "jag.standard.instructional_excellence",
    protocolKey: "jag.protocol.session_delivery",
    processKey: "jag.process.daily_instruction",
    procedureKey: "jag.procedure.conduct_session",
    ruleSetKeys: ["ref_platform_access_gate"],
    requiredPermissions: ["finance.view"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: [],
    intelligenceServiceKeys: ["intelligence.graph"],
    sortOrder: 54,
  },
  {
    capabilityKey: "cap.finance.executive_reporting",
    title: "Finance Executive Reporting",
    description: "Executive financial intelligence and forecasting consumption.",
    status: "published",
    standardKey: "jag.standard.instructional_excellence",
    protocolKey: "jag.protocol.session_delivery",
    processKey: "jag.process.daily_instruction",
    procedureKey: "jag.procedure.conduct_session",
    ruleSetKeys: ["ref_platform_access_gate"],
    requiredPermissions: ["finance.executive", "fi.executive"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: [],
    intelligenceServiceKeys: ["intelligence.recommendations"],
    sortOrder: 55,
  },
  {
    capabilityKey: "cap.hr.workforce_operations",
    title: "HR Workforce Operations",
    description: "Recruiting, compliance, onboarding, and workforce management.",
    status: "published",
    standardKey: "jag.standard.instructional_excellence",
    protocolKey: "jag.protocol.session_delivery",
    processKey: "jag.process.daily_instruction",
    procedureKey: "jag.procedure.conduct_session",
    ruleSetKeys: ["ref_platform_access_gate"],
    requiredPermissions: ["hr.view"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: [],
    intelligenceServiceKeys: ["intelligence.graph"],
    workflowKey: "ref_hr_onboarding",
    sortOrder: 56,
  },
  {
    capabilityKey: "cap.executive.intelligence",
    title: "Executive Intelligence",
    description: "Strategic insights, risk signals, and board-ready intelligence.",
    status: "published",
    standardKey: "jag.standard.instructional_excellence",
    protocolKey: "jag.protocol.session_delivery",
    processKey: "jag.process.daily_instruction",
    procedureKey: "jag.procedure.conduct_session",
    ruleSetKeys: ["ref_platform_access_gate"],
    requiredPermissions: ["executive.intelligence"],
    parameterKeys: [],
    evidenceTypeKeys: [],
    knowledgeAssetKeys: [],
    intelligenceServiceKeys: ["intelligence.recommendations", "intelligence.graph"],
    decisionTypeKey: "ref_platform_risk_signal",
    sortOrder: 57,
  },
];
