import { f, perms, schema } from "@/applications/academyos/schemas/_helpers";
import type { PlatformSchema } from "@/lib/platform/schema";

export const FINANCE_COMMS_SCHEMAS: PlatformSchema[] = [
  schema({
    entityType: "Scholarship",
    label: "Scholarship",
    fields: [
      f.text("displayName", "Scholarship name", true),
      f.ref("studentId", "Student", "Student", true),
      f.currency("awardAmount", "Award amount", true),
      f.select("status", "Status", true),
      f.date("awardedOn", "Awarded on"),
    ],
    permissions: perms("scholarships", ["read", "create", "update", "approve", "export"]),
    forms: [{ formId: "academyos.scholarship.create", role: "create" }],
    workflows: [{ workflowId: "academyos.scholarship", role: "primary" }],
  }),
  schema({
    entityType: "Invoice",
    label: "Invoice",
    fields: [
      f.text("displayName", "Invoice number", true),
      f.ref("studentId", "Student", "Student"),
      f.ref("familyId", "Family", "Family"),
      f.currency("amount", "Amount", true),
      f.date("dueDate", "Due date"),
      f.select("status", "Status", true),
    ],
    permissions: perms("finance", ["read", "create", "update", "approve", "export"]),
    forms: [{ formId: "academyos.invoice.create", role: "create" }],
    workflows: [{ workflowId: "academyos.finance", role: "primary" }],
    intelligence: {
      forecastableFields: ["amount"],
      reportableFields: ["amount", "status", "dueDate"],
    },
  }),
  schema({
    entityType: "Payment",
    label: "Payment",
    fields: [
      f.text("displayName", "Payment reference", true),
      f.ref("invoiceId", "Invoice", "Invoice"),
      f.currency("amount", "Amount", true),
      f.date("paidOn", "Paid on", true),
      f.select("method", "Method"),
      f.select("status", "Status", true),
    ],
    permissions: perms("finance", ["read", "create", "update", "export"]),
    forms: [{ formId: "academyos.payment.create", role: "create" }],
  }),
  schema({
    entityType: "LedgerEntry",
    label: "Ledger Entry",
    fields: [
      f.text("displayName", "Entry label", true),
      f.ref("invoiceId", "Invoice", "Invoice"),
      f.ref("paymentId", "Payment", "Payment"),
      f.currency("amount", "Amount", true),
      f.select("entryType", "Type", true),
      f.date("postedOn", "Posted on", true),
    ],
    permissions: perms("finance", ["read", "update", "export"]),
  }),
  schema({
    entityType: "PayrollBatch",
    label: "Payroll Batch",
    fields: [
      f.text("displayName", "Batch name", true),
      f.ref("schoolId", "School", "School"),
      f.date("periodStart", "Period start", true),
      f.date("periodEnd", "Period end", true),
      f.currency("totalAmount", "Total"),
      f.select("status", "Status", true),
    ],
    permissions: perms("hr", ["read", "create", "update", "approve", "export"]),
    forms: [{ formId: "academyos.payroll-batch.create", role: "create" }],
    workflows: [{ workflowId: "academyos.payroll-approval", role: "primary" }],
  }),
  schema({
    entityType: "CalendarEvent",
    label: "Calendar Event",
    fields: [
      f.text("displayName", "Event title", true),
      f.date("startDate", "Start", true),
      f.date("endDate", "End"),
      f.ref("schoolId", "School", "School"),
      f.select("eventType", "Type", true),
    ],
    permissions: perms("operations", ["read", "create", "update"]),
    forms: [{ formId: "academyos.calendar-event.create", role: "create" }],
  }),
  schema({
    entityType: "Announcement",
    label: "Announcement",
    fields: [
      f.text("displayName", "Title", true),
      f.rich("body", "Body"),
      f.ref("schoolId", "School", "School"),
      f.select("audience", "Audience", true),
      f.select("status", "Status", true),
      f.date("publishOn", "Publish on"),
    ],
    permissions: perms("communications", ["read", "create", "update", "approve"]),
    forms: [{ formId: "academyos.announcement.create", role: "create" }],
  }),
  schema({
    entityType: "Document",
    label: "Document",
    fields: [
      f.text("displayName", "Document title", true),
      f.select("documentType", "Type", true),
      f.ref("studentId", "Student", "Student"),
      f.ref("employeeId", "Employee", "Employee"),
      f.select("status", "Status", true),
    ],
    permissions: perms("documents", ["read", "create", "update", "export"]),
    forms: [{ formId: "academyos.document.create", role: "create" }],
  }),
  schema({
    entityType: "Message",
    label: "Message",
    fields: [
      f.text("displayName", "Subject", true),
      f.rich("body", "Body"),
      f.ref("studentId", "Student", "Student"),
      f.ref("familyId", "Family", "Family"),
      f.select("channel", "Channel", true),
      f.select("status", "Status", true),
    ],
    permissions: perms("communications", ["read", "create", "update"]),
    forms: [{ formId: "academyos.message.create", role: "create" }],
  }),
];
