import { f, perms, schema } from "@/applications/academyos/schemas/_helpers";
import type { PlatformSchema } from "@/lib/platform/schema";

export const SERVICES_SCHEMAS: PlatformSchema[] = [
  schema({
    entityType: "Inquiry",
    label: "Inquiry",
    fields: [
      f.text("displayName", "Inquirer name", true),
      f.email("email", "Email", true),
      f.phone("phone", "Phone"),
      f.ref("schoolId", "School", "School"),
      f.select("source", "Source"),
      f.select("status", "Status", true),
    ],
    permissions: perms("admissions", ["read", "create", "update", "export"]),
    forms: [{ formId: "academyos.inquiry.create", role: "create" }],
    workflows: [{ workflowId: "academyos.admissions", role: "primary" }],
  }),
  schema({
    entityType: "Application",
    label: "Application",
    fields: [
      f.text("displayName", "Applicant name", true),
      f.ref("inquiryId", "Inquiry", "Inquiry"),
      f.ref("studentId", "Student", "Student"),
      f.ref("schoolId", "School", "School", true),
      f.date("submittedOn", "Submitted on"),
      f.select("status", "Status", true),
    ],
    permissions: perms("admissions", ["read", "create", "update", "approve", "export"]),
    forms: [{ formId: "academyos.application.create", role: "create" }],
    workflows: [{ workflowId: "academyos.admissions", role: "primary" }],
  }),
  schema({
    entityType: "BehaviorIncident",
    label: "Behavior Incident",
    fields: [
      f.text("displayName", "Incident title", true),
      f.ref("studentId", "Student", "Student", true),
      f.ref("schoolId", "School", "School"),
      f.date("occurredOn", "Occurred on", true),
      f.select("severity", "Severity", true),
      f.rich("description", "Description"),
      f.select("status", "Status", true),
    ],
    permissions: perms("behavior", ["read", "create", "update", "approve", "export"]),
    forms: [{ formId: "academyos.behavior-incident.create", role: "create" }],
    workflows: [{ workflowId: "academyos.behavior", role: "primary" }],
  }),
  schema({
    entityType: "Intervention",
    label: "Intervention",
    fields: [
      f.text("displayName", "Intervention name", true),
      f.ref("studentId", "Student", "Student", true),
      f.ref("incidentId", "Incident", "BehaviorIncident"),
      f.select("tier", "Tier"),
      f.select("status", "Status", true),
      f.date("startDate", "Start"),
      f.date("endDate", "End"),
    ],
    permissions: perms("behavior", ["read", "create", "update"]),
  }),
  schema({
    entityType: "IEP",
    label: "IEP",
    fields: [
      f.ref("studentId", "Student", "Student", true),
      f.date("effectiveOn", "Effective on", true),
      f.date("reviewOn", "Review on"),
      f.select("status", "Status", true),
    ],
    permissions: perms("compliance", ["read", "create", "update", "approve", "export"]),
    forms: [{ formId: "academyos.iep.create", role: "create" }],
  }),
  schema({
    entityType: "Plan504",
    label: "504 Plan",
    fields: [
      f.ref("studentId", "Student", "Student", true),
      f.date("effectiveOn", "Effective on", true),
      f.date("reviewOn", "Review on"),
      f.select("status", "Status", true),
    ],
    permissions: perms("compliance", ["read", "create", "update", "approve", "export"]),
    forms: [{ formId: "academyos.plan504.create", role: "create" }],
  }),
  schema({
    entityType: "Accommodation",
    label: "Accommodation",
    fields: [
      f.text("displayName", "Accommodation", true),
      f.ref("studentId", "Student", "Student", true),
      f.ref("iepId", "IEP", "IEP"),
      f.ref("plan504Id", "504 Plan", "Plan504"),
      f.select("status", "Status", true),
    ],
    permissions: perms("compliance", ["read", "create", "update"]),
  }),
  schema({
    entityType: "MedicalRecord",
    label: "Medical Record",
    fields: [
      f.ref("studentId", "Student", "Student", true),
      f.text("displayName", "Record title", true),
      f.select("recordType", "Type", true),
      f.date("recordedOn", "Recorded on"),
      f.select("status", "Status", true),
    ],
    permissions: perms("medical", ["read", "create", "update", "export"]),
    forms: [{ formId: "academyos.medical-record.create", role: "create" }],
  }),
  schema({
    entityType: "MedicationAuthorization",
    label: "Medication Authorization",
    fields: [
      f.ref("studentId", "Student", "Student", true),
      f.text("medicationName", "Medication", true),
      f.date("startDate", "Start", true),
      f.date("endDate", "End"),
      f.select("status", "Status", true),
    ],
    permissions: perms("medical", ["read", "create", "update", "approve"]),
    forms: [{ formId: "academyos.medication-authorization.create", role: "create" }],
  }),
  schema({
    entityType: "TransportationRoute",
    label: "Transportation Route",
    fields: [
      f.text("displayName", "Route name", true),
      f.ref("schoolId", "School", "School", true),
      f.text("code", "Route code"),
      f.select("status", "Status", true),
    ],
    permissions: perms("operations", ["read", "create", "update"]),
    forms: [{ formId: "academyos.transportation-route.create", role: "create" }],
  }),
];
