export {
  DocumentRegistry,
  assertDocumentRegistered,
  getDocumentCategory,
  getDocumentDefinition,
  getDocumentTemplate,
  listDocumentCategories,
  listDocumentDefinitions,
  listDocumentTemplates,
  registerDocument,
  registerDocumentCategory,
  registerDocumentTemplate,
  resetDocumentRegistryForTests,
  validateDocumentRegistryDependencies,
} from "@/jag/documents/registry/document-registry";
