/**
 * AcademyOS™ Industry Pack — public entry point.
 */

export {
  ACADEMYOS_EXTENSION_MANIFEST,
  ACADEMYOS_MODULES,
  ACADEMYOS_PACK_DESCRIPTOR,
  ACADEMYOS_PACK_ID,
  ACADEMYOS_PACK_VERSION,
  ACADEMYOS_TWIN_ENTITY_LABELS,
  type AcademyOsIndustryPackDescriptor,
} from "./manifest";
export {
  installAcademyOsIndustryPack,
  getAcademyOsInstallRecord,
  type AcademyOsInstallResult,
} from "./install";
export { resetAcademyOsStoreForTests } from "./store";
export { ACADEMYOS_TWIN_MAPPINGS, twinExternalKey } from "./twin/mappings";
export {
  projectAcademyEntityToTwin,
  linkAcademyEnrollment,
} from "./twin/project";
export {
  EDUCATION_CONNECTOR_CATALOG,
  createEducationConnectors,
  resetEducationConnectorStateForTests,
} from "./connectors/catalog";
export { buildEducationExecutiveDashboard } from "./intelligence/education-dashboard";
export type { EducationExecutiveDashboard } from "./intelligence/education-dashboard";
export { createAcademyOsInsightProvider } from "./intelligence/insight-provider";
export {
  createAdmissionsService,
  createAttendanceService,
  createBillingService,
  createClassroomsService,
  createCoursesService,
  createEnrollmentService,
  createGradingService,
  createGuardiansService,
  createIepService,
  createReportingService,
  createSchedulingService,
  createScholarshipsService,
  createSchoolsService,
  createStaffService,
  createStudentsService,
  createTranscriptsService,
} from "./domain/services";
export {
  ADMISSIONS_STAGES,
  DOCUMENT_REQUIREMENT_TYPES,
  ENROLLMENT_WIZARD_SECTIONS,
  buildAdmissionsDashboard,
  buildAdmissionsSummary,
  createAdmissionsReportingService,
  createAdmissionsScholarshipService,
  createApplicantsService,
  createDocumentsService,
  createEnrollmentWizardService,
  createParentPortalService,
  findDuplicateApplicants,
  listAdmissionsAudit,
  listAdmissionsNotifications,
  listAdmissionsTimeline,
  resetAdmissionsStoreForTests,
  type AcademyApplicant,
  type AdmissionsDashboardMetrics,
  type AdmissionsReportKind,
  type AdmissionsStage,
  type AdmissionsSummary,
} from "./admissions";
export {
  ATTENDANCE_STATUSES,
  CLASS_ASSIGNMENT_KINDS,
  STUDENT_LIFECYCLE_STATUSES,
  SUPPORT_PLAN_KINDS,
  buildStudentSuccessSummary,
  createClassEnrollmentService,
  createFamiliesService,
  createSisAttendanceService,
  createSisParentPortalService,
  createSisReportingService,
  createSisStudentsService,
  createSupportPlansService,
  listClassAssignments,
  listFamilies,
  listSisAttendance,
  listStudentAudit,
  listStudentTimeline,
  listStudents as listSisStudents,
  listSupportPlans,
  resetSisStoreForTests,
  type ClassAssignment,
  type ClassAssignmentKind,
  type FamilyMember,
  type FamilyRelationshipKind,
  type SisReportKind,
  type SisStudent,
  type StudentLifecycleStatus,
  type StudentSuccessSummary,
  type SupportPlan,
  type SupportPlanKind,
} from "./sis";
export {
  CALENDAR_KINDS,
  CLASS_STATUSES,
  STUDENT_SCHEDULE_KINDS,
  academyVirtualEndTime,
  buildAcademicOperationsSummary,
  createAcademicCalendarService,
  createAcademicOpsParentPortalService,
  createAcademicOpsReportingService,
  createClassesService,
  createClassroomNotesService,
  createSessionsService,
  createStudentSchedulingService,
  createTeacherWorkspaceService,
  createTeachersService,
  listAoClasses,
  listAoEnrollments,
  listAoSessions,
  listAoTeachers,
  listCalendars,
  listWaitlist,
  resetAcademicOpsStoreForTests,
  validateVirtualSlot,
  type AcademicCalendar,
  type AcademicOperationsSummary,
  type AcademicOpsReportKind,
  type AoClass,
  type AoTeacher,
  type CalendarKind,
  type ClassStatus,
  type ClassroomNoteKind,
  type InstructionalSession,
  type LessonStatus,
  type SessionStatus,
  type StudentClassEnrollment,
  type TeacherWorkspaceView,
} from "./academic-ops";
export type { SisAttendanceStatus } from "./sis/types";
export {
  DEFAULT_BILLING_CONFIG,
  buildFinancialOperationsSummary,
  createFamilyAccountsService,
  createFinanceBillingService,
  createFinanceParentPortalService,
  createFinanceQuickBooksService,
  createFinanceReportingService,
  createFinanceScholarshipService,
  createPaymentsService,
  createTuitionService,
  getBillingConfig,
  listFamilyAccounts,
  listFinanceInvoices,
  listFinancePayments,
  listScholarshipAwards,
  listTuitionPlans,
  mergeBillingConfig,
  resetFinanceStoreForTests,
  type FamilyFinancialAccount,
  type FinanceBillingConfig,
  type FinanceInvoice,
  type FinancePayment,
  type FinanceReportKind,
  type FinancialOperationsSummary,
  type InvoiceCategory,
  type InvoiceStatus,
  type PaymentMethodKind,
  type ScholarshipAward,
  type TuitionFrequency,
  type TuitionPlan,
} from "./finance";
export {
  ASSESSMENT_KINDS,
  DEFAULT_MASTERY_SCALE,
  MASTERY_LEVELS,
  buildLearningProgressSummary,
  createAssessmentService,
  createCurriculumService,
  createGradebookService,
  createInterventionService,
  createLearningParentPortalService,
  createLearningProfileService,
  createLearningReportingService,
  createMasteryService,
  createProgressService,
  getMasteryScale,
  listCurricula,
  listLearningAssessments,
  listLearningInterventions,
  listMastery,
  resetLearningStoreForTests,
  type AssessmentKind,
  type AssessmentRecord,
  type Curriculum,
  type CurriculumStatus,
  type Intervention,
  type InterventionKind,
  type InterventionStatus,
  type LearningProgressSummary,
  type LearningReportKind,
  type MasteryLevel,
  type MasteryRecord,
  type MasteryScaleConfig,
  type StudentLearningProfile,
} from "./learning";
export {
  DEFAULT_COMPENSATION_CONFIG,
  DEFAULT_POSITION_TITLES,
  DEFAULT_TIMEKEEPING_CONFIG,
  EMPLOYMENT_TYPES,
  buildWorkforceSummary,
  calculateVirtualSessionPay,
  createAssignmentService,
  createCertificationService,
  createContractService,
  createEmployeePortalService,
  createEmployeeService,
  createPayrollPreparationService,
  createPerformanceService,
  createPositionService,
  createSubstituteService,
  createTimekeepingService,
  createWorkforceReportingService,
  listAssignments,
  listEmployees,
  listPositions,
  listTimesheets,
  resetWorkforceStoreForTests,
  type AssignmentKind,
  type CompensationProgramKey,
  type Employee,
  type EmployeeStatus,
  type EmploymentType,
  type PayrollPreparation,
  type Position,
  type Timesheet,
  type WorkforceReportKind,
  type WorkforceSummary,
} from "./workforce";
export {
  DEFAULT_CHANNEL_ROUTING,
  DOMAIN_EVENT_CATALOG,
  COMMUNICATION_CHANNELS,
  WORKFLOW_RECIPES,
  buildCommunicationsSummary,
  createAnnouncementService,
  createCommunicationCenterService,
  createCommunicationsEmployeePortalService,
  createCommunicationsParentPortalService,
  createCommunicationsReportingService,
  createMessagingService,
  createNotificationEngine,
  createNotificationService,
  createReminderService,
  createTemplateService,
  createWorkflowService,
  renderTemplate,
  resetCommunicationsStoreForTests,
  routeAcademyOsDomainEvent,
  type Announcement,
  type CommunicationChannel,
  type CommunicationDomain,
  type CommunicationsReportKind,
  type CommunicationsSummary,
  type Message,
  type Notification,
  type TemplateStatus,
  type WorkflowInstance,
  type WorkflowRecipe,
} from "./communications";
export {
  ALL_VALIDATION_SCENARIOS,
  buildReleaseReadinessDashboard,
  getLastValidationDashboard,
  listScenarioCatalog,
  listValidationRuns,
  resetValidationStoreForTests,
  runAcademyOsValidation,
  type ReleaseReadinessDashboard,
  type ValidationRunOptions,
  type ValidationScenarioId,
  type ValidationScenarioResult,
} from "./validation";
export {
  ALL_HARDENING_SUITES,
  buildRc2HardeningSummary,
  getLastHardeningDashboard,
  listHardeningCatalog,
  resetHardeningStoreForTests,
  runAcademyOsHardening,
  type GateStatus,
  type HardeningRunOptions,
  type HardeningSuiteId,
  type Rc2HardeningSummary,
  type Rc2ReleaseReadinessDashboard,
} from "./hardening";
export {
  buildHealthReport,
  buildOperationsDashboard,
  collectMonitoringMetrics,
  createOperationsService,
  getLastOperationsDashboard,
  getOperationsDashboard,
  buildRc3StudioArtifacts,
  resetOperationsStoreForTests,
  runDiagnostics,
  seedDemoOrganization,
  validateBackupRecovery,
  validateConfiguration,
  validateDeployment,
  validateUpgrade,
  type AcademyOsRc3StudioArtifacts,
  type BackupValidationReport,
  type ConfigurationReport,
  type DemoOrganizationSeed,
  type DeploymentReport,
  type DiagnosticsReport,
  type HealthReport,
  type MonitoringReport,
  type OperationsDashboard,
  type OperationsRunOptions,
  type UpgradeReport,
} from "./operations";
