import type { ActivityClassification, ActivityVisibility } from "@/lib/platform/activity/types";

export interface ActivityEventDefinition {
  moduleKey: string;
  classification: ActivityClassification;
  visibility: ActivityVisibility;
  label: string;
}

/** Canonical activity event catalog — modules must register types here. */
export const ACTIVITY_EVENT_CATALOG: Record<string, ActivityEventDefinition> = {
  "student.created": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Student Created",
  },
  "student.updated": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Student Updated",
  },
  "student.archived": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Student Archived",
  },
  "student.restored": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Student Restored",
  },
  "student.deleted": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Student Permanently Deleted",
  },
  "family.created": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Family Created",
  },
  "family.updated": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Family Updated",
  },
  "family.archived": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Family Archived",
  },
  "family.restored": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Family Restored",
  },
  "family.deleted": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Family Permanently Deleted",
  },
  "family.merged": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Families Merged",
  },
  "family.split": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Family Split",
  },
  "guardian.created": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Guardian Added",
  },
  "guardian.added": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Guardian Added",
  },
  "guardian.updated": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Guardian Updated",
  },
  "student.moved": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Student Moved to Family",
  },
  "enrollment.changed": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Enrollment Changed",
  },
  "enrollment.created": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Enrollment Created",
  },
  "attendance.recorded": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Attendance Recorded",
  },
  "behavior.recorded": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Behavior Recorded",
  },
  "document.uploaded": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Document Uploaded",
  },
  "document.created": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Document Created",
  },
  "document.updated": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Document Updated",
  },
  "document.versioned": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Document Versioned",
  },
  "document.archived": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Document Archived",
  },
  "document.restored": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Document Restored",
  },
  "document.deleted": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Document Deleted",
  },
  "signature.requested": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Signature Requested",
  },
  "scholarship.awarded": {
    moduleKey: "scholarships",
    classification: "operational",
    visibility: "staff",
    label: "Scholarship Awarded",
  },
  "invoice.paid": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Invoice Paid",
  },
  "invoice.created": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Invoice Created",
  },
  "invoice.sent": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Invoice Sent",
  },
  "invoice.overdue": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Invoice Overdue",
  },
  "invoice.payment_recorded": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Payment Recorded",
  },
  "invoice.refunded": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Refund Processed",
  },
  "invoice.write_off": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Invoice Write-Off",
  },
  "payment.received": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Payment Received",
  },
  "payment.failed": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Payment Failed",
  },
  "finance.account.created": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Family Financial Account Created",
  },
  "scholarship.applied": {
    moduleKey: "scholarships",
    classification: "operational",
    visibility: "staff",
    label: "Scholarship Applied",
  },
  "discount.applied": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Discount Applied",
  },
  "refund.created": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Refund Requested",
  },
  "refund.completed": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Refund Completed",
  },
  "billing.invoice_created": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Billing Invoice Created",
  },
  "billing.payment_received": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Billing Payment Received",
  },
  "billing.overdue": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Billing Overdue",
  },
  "billing.overdue_balance": {
    moduleKey: "finance",
    classification: "operational",
    visibility: "staff",
    label: "Billing Overdue Balance",
  },
  "payroll.approved": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Payroll Approved",
  },
  "identity.permission_changed": {
    moduleKey: "identity",
    classification: "audit",
    visibility: "internal",
    label: "Role Permission Changed",
  },
  "identity.org_scope_assigned": {
    moduleKey: "identity",
    classification: "audit",
    visibility: "internal",
    label: "User Org Scope Assigned",
  },
  "identity.role_created": {
    moduleKey: "identity",
    classification: "audit",
    visibility: "internal",
    label: "Custom Role Created",
  },
  "identity.impersonation_started": {
    moduleKey: "identity",
    classification: "audit",
    visibility: "internal",
    label: "Impersonation Started",
  },
  "identity.impersonation_ended": {
    moduleKey: "identity",
    classification: "audit",
    visibility: "internal",
    label: "Impersonation Ended",
  },
  "communication.created": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Created",
  },
  "communication.sent": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Sent",
  },
  "communication.failed": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Failed",
  },
  "communication.read": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Read",
  },
  "communication.archived": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Archived",
  },
  "communication.updated": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Updated",
  },
  "communication.restored": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Restored",
  },
  "communication.deleted": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Deleted",
  },
  "communication.duplicated": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Duplicated",
  },
  "template.created": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Template Created",
  },
  "template.updated": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Template Updated",
  },
  "template.archived": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Template Archived",
  },
  "template.restored": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Template Restored",
  },
  "template.duplicated": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Communication Template Duplicated",
  },
  "template.used": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Template Used",
  },
  "announcement.created": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Announcement Created",
  },
  "announcement.updated": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Announcement Updated",
  },
  "announcement.archived": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Announcement Archived",
  },
  "announcement.duplicated": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Announcement Duplicated",
  },
  "announcement.published": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Announcement Published",
  },
  "meeting.logged": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Meeting Logged",
  },
  "phonecall.logged": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Phone Call Logged",
  },
  "workflow.created": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Created",
  },
  "workflow.updated": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Updated",
  },
  "workflow.enabled": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Enabled",
  },
  "workflow.disabled": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Disabled",
  },
  "workflow.archived": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Archived",
  },
  "workflow.restored": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Restored",
  },
  "workflow.deleted": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Deleted",
  },
  "workflow.duplicated": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Duplicated",
  },
  "workflow.executed": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Executed",
  },
  "workflow.failed": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Failed",
  },
  "workflow.completed": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Workflow Completed",
  },
  "employee.deactivated": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Employee Deactivated",
  },
  "employee.restored": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Employee Restored",
  },
  "employee.created": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Employee Created",
  },
  "employee.updated": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Employee Updated",
  },
  "employee.hired": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Employee Hired",
  },
  "employee.promoted": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Employee Promoted",
  },
  "employee.assigned": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Employee Assigned",
  },
  "employee.certification.expiring": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Certification Expiring",
  },
  "employee.review.completed": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Performance Review Completed",
  },
  "employee.leave.approved": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Leave Approved",
  },
  "employee.terminated": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Employee Terminated",
  },
  "employee.onboarding.completed": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Onboarding Completed",
  },
  "employee.offer.extended": {
    moduleKey: "hr",
    classification: "operational",
    visibility: "staff",
    label: "Offer Extended",
  },
  "student.duplicated": {
    moduleKey: "students",
    classification: "operational",
    visibility: "staff",
    label: "Student Duplicated",
  },
  "family.duplicated": {
    moduleKey: "families",
    classification: "operational",
    visibility: "staff",
    label: "Family Duplicated",
  },
  "calendar.created": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Calendar Event Created",
  },
  "calendar.updated": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Calendar Event Updated",
  },
  "calendar.cancelled": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Calendar Event Cancelled",
  },
  "meeting.scheduled": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Meeting Scheduled",
  },
  "class.scheduled": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Class Scheduled",
  },
  "room.reserved": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Room / Resource Reserved",
  },
  "resource.conflict": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Resource Conflict Detected",
  },
  "note.created": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Note Created",
  },
  "note.updated": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Note Updated",
  },
  "note.deleted": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Note Deleted",
  },
  "note.pinned": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Note Pinned",
  },
  "note.unpinned": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Note Unpinned",
  },
  "tag.created": {
    moduleKey: "platform",
    classification: "system",
    visibility: "internal",
    label: "Tag Created",
  },
  "tag.applied": {
    moduleKey: "platform",
    classification: "system",
    visibility: "internal",
    label: "Tag Applied",
  },
  "tag.removed": {
    moduleKey: "platform",
    classification: "system",
    visibility: "internal",
    label: "Tag Removed",
  },
  "relationship.created": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Relationship Created",
  },
  "relationship.updated": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Relationship Updated",
  },
  "relationship.ended": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Relationship Ended",
  },
  // Legacy timeline event types (writeTimelineEvent dual-write path)
  "workflow": {
    moduleKey: "platform",
    classification: "system",
    visibility: "staff",
    label: "Workflow Event",
  },
  "status_change": {
    moduleKey: "sis",
    classification: "operational",
    visibility: "staff",
    label: "Status Change",
  },
  "playbook_started": {
    moduleKey: "work",
    classification: "operational",
    visibility: "staff",
    label: "Playbook Started",
  },
  "task_completed": {
    moduleKey: "work",
    classification: "operational",
    visibility: "staff",
    label: "Task Completed",
  },
  "obligation_completed": {
    moduleKey: "compliance",
    classification: "operational",
    visibility: "staff",
    label: "Obligation Completed",
  },
  "email": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Email",
  },
  "sms": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "SMS",
  },
  "portal_message": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Portal Message",
  },
  "phone_call": {
    moduleKey: "platform",
    classification: "communication",
    visibility: "staff",
    label: "Phone Call",
  },
  "task": {
    moduleKey: "work",
    classification: "operational",
    visibility: "staff",
    label: "Task",
  },
  "document": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Document",
  },
  "approval": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Approval",
  },
  "note": {
    moduleKey: "platform",
    classification: "operational",
    visibility: "staff",
    label: "Note",
  },
  "system": {
    moduleKey: "platform",
    classification: "system",
    visibility: "internal",
    label: "System Event",
  },
  "admissions.inquiry_created": {
    moduleKey: "admissions",
    classification: "operational",
    visibility: "staff",
    label: "Inquiry Created",
  },
  "admissions.stage_changed": {
    moduleKey: "admissions",
    classification: "operational",
    visibility: "staff",
    label: "Pipeline Stage Changed",
  },
  "admissions.decision_recorded": {
    moduleKey: "admissions",
    classification: "operational",
    visibility: "staff",
    label: "Decision Recorded",
  },
  "admissions.enrollment_completed": {
    moduleKey: "admissions",
    classification: "operational",
    visibility: "staff",
    label: "Enrollment Completed",
  },
  "executive.kpi_snapshot_written": {
    moduleKey: "executive",
    classification: "system",
    visibility: "internal",
    label: "Executive KPI Snapshot Written",
  },
  "founder.insight.created": {
    moduleKey: "founder",
    classification: "operational",
    visibility: "internal",
    label: "Founder Insight Created",
  },
  "founder.recommendation.created": {
    moduleKey: "founder",
    classification: "operational",
    visibility: "internal",
    label: "Founder Recommendation Created",
  },
  "founder.decision.approved": {
    moduleKey: "founder",
    classification: "audit",
    visibility: "internal",
    label: "Founder Decision Approved",
  },
  "founder.decision.dismissed": {
    moduleKey: "founder",
    classification: "audit",
    visibility: "internal",
    label: "Founder Decision Dismissed",
  },
  "founder.decision.delegated": {
    moduleKey: "founder",
    classification: "audit",
    visibility: "internal",
    label: "Founder Decision Delegated",
  },
  "founder.decision.scheduled": {
    moduleKey: "founder",
    classification: "audit",
    visibility: "internal",
    label: "Founder Decision Scheduled",
  },
  "founder.decision.resolved": {
    moduleKey: "founder",
    classification: "audit",
    visibility: "internal",
    label: "Founder Decision Resolved",
  },
  "founder.brief.generated": {
    moduleKey: "founder",
    classification: "operational",
    visibility: "internal",
    label: "Founder Brief Generated",
  },
  "founder.health.scored": {
    moduleKey: "founder",
    classification: "operational",
    visibility: "internal",
    label: "Founder Health Scored",
  },
  "jag.pipeline.completed": {
    moduleKey: "jag",
    classification: "system",
    visibility: "internal",
    label: "JAG Pipeline Completed",
  },
  "jag.insight.created": {
    moduleKey: "jag",
    classification: "operational",
    visibility: "internal",
    label: "JAG Insight Created",
  },
  "jag.insight.resolved": {
    moduleKey: "jag",
    classification: "operational",
    visibility: "internal",
    label: "JAG Insight Resolved",
  },
  "jag.anomaly.detected": {
    moduleKey: "jag",
    classification: "operational",
    visibility: "internal",
    label: "JAG Anomaly Detected",
  },
  "jag.feedback.recorded": {
    moduleKey: "jag",
    classification: "audit",
    visibility: "internal",
    label: "JAG Feedback Recorded",
  },
  "jag.context.updated": {
    moduleKey: "jag",
    classification: "system",
    visibility: "internal",
    label: "JAG Context Updated",
  },
};

export function getActivityEventDefinition(eventType: string): ActivityEventDefinition | undefined {
  return ACTIVITY_EVENT_CATALOG[eventType];
}

export function isKnownActivityEventType(eventType: string): boolean {
  return eventType in ACTIVITY_EVENT_CATALOG;
}
