/**
 * Canonical Phase 1 Interest Form definition (mirrors current Express Interest fields).
 */

import type { InterestFormDefinition } from "@/lib/admissions/interest-form/types";
import { INTEREST_FORM_SCHEMA_VERSION } from "@/lib/admissions/interest-form/types";

export const INITIAL_INTEREST_FORM_DEFINITION: InterestFormDefinition = {
  schemaVersion: INTEREST_FORM_SCHEMA_VERSION,
  title: "Express Interest",
  sections: [
    {
      key: "student",
      title: "Student Information",
      description: "Tell us about the student you would like to enroll.",
      order: 0,
      questionKeys: [
        "first_name",
        "last_name",
        "preferred_name",
        "date_of_birth",
        "current_grade",
        "applying_for_grade",
      ],
    },
    {
      key: "program_school",
      title: "Program & School",
      order: 1,
      questionKeys: [
        "school_id",
        "program",
        "funding_sources",
        "referral_source",
        "learning_concerns",
      ],
    },
    {
      key: "guardian",
      title: "Parent / Guardian Contact",
      description:
        "Use the email you will sign in with to access your admissions portal.",
      order: 2,
      questionKeys: [
        "guardian_first_name",
        "guardian_last_name",
        "guardian_email",
        "guardian_phone",
        "preferred_contact_method",
      ],
    },
  ],
  questions: [
    {
      key: "first_name",
      type: "text",
      label: "First Name",
      required: true,
      order: 0,
      systemBinding: "lead.first_name",
    },
    {
      key: "last_name",
      type: "text",
      label: "Last Name",
      required: true,
      order: 1,
      systemBinding: "lead.last_name",
    },
    {
      key: "preferred_name",
      type: "text",
      label: "Preferred Name",
      required: false,
      order: 2,
      systemBinding: "lead.preferred_name",
    },
    {
      key: "date_of_birth",
      type: "date",
      label: "Date of Birth",
      required: false,
      order: 3,
      systemBinding: "lead.date_of_birth",
    },
    {
      key: "current_grade",
      type: "select",
      label: "Current Grade",
      required: false,
      order: 4,
      systemBinding: "lead.current_grade",
      optionSource: "grades",
    },
    {
      key: "applying_for_grade",
      type: "select",
      label: "Applying For Grade",
      required: false,
      order: 5,
      systemBinding: "lead.applying_for_grade",
      optionSource: "grades",
    },
    {
      key: "school_id",
      type: "school_selector",
      label: "School",
      required: true,
      order: 6,
      systemBinding: "lead.school_id",
    },
    {
      key: "program",
      type: "program_selector",
      label: "Program",
      required: false,
      order: 7,
      systemBinding: "lead.program",
    },
    {
      key: "funding_sources",
      type: "multiselect",
      label: "Funding sources",
      required: false,
      order: 8,
      systemBinding: "lead.funding_sources",
      optionSource: "funding_sources",
    },
    {
      key: "referral_source",
      type: "text",
      label: "Referral source",
      required: false,
      order: 9,
      systemBinding: "lead.referral_source",
      placeholder: "How did you hear about us?",
    },
    {
      key: "learning_concerns",
      type: "rich_text",
      label: "Learning concerns",
      required: false,
      order: 10,
      systemBinding: null,
      placeholder: "Optional — learning, social, or support needs",
    },
    {
      key: "guardian_first_name",
      type: "text",
      label: "First Name",
      required: false,
      order: 11,
      systemBinding: "lead.guardian_first_name",
    },
    {
      key: "guardian_last_name",
      type: "text",
      label: "Last Name",
      required: false,
      order: 12,
      systemBinding: "lead.guardian_last_name",
    },
    {
      key: "guardian_email",
      type: "email",
      label: "Email",
      required: true,
      order: 13,
      systemBinding: "lead.guardian_email",
    },
    {
      key: "guardian_phone",
      type: "phone",
      label: "Phone",
      required: false,
      order: 14,
      systemBinding: "lead.guardian_phone",
    },
    {
      key: "preferred_contact_method",
      type: "select",
      label: "Preferred contact method",
      required: false,
      order: 15,
      systemBinding: null,
      options: [
        { value: "email", label: "Email" },
        { value: "phone", label: "Phone" },
        { value: "text", label: "Text" },
      ],
      defaultValue: "email",
    },
  ],
};
