/**
 * Scaffold file templates for a new Capability Pack.
 */

import type { ScaffoldResult } from "@/jag/sdk/public-types";

function slugify(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function scaffoldCapabilityPack(name: string): ScaffoldResult {
  const slug = slugify(name);
  const packId = `${slug}.core`;
  const label = name.trim() || slug;
  const constBase = slug.replace(/-/g, "_");

  const packTs = `/**
 * ${packId} — generated by JAG SDK scaffold.
 * Definitions only. Authorization and engines remain JAG Platform.
 */

import {
  buildCapabilityPack,
  validateCapabilityPack,
} from "@/jag/sdk";

export const ${constBase}_PACK_ID = "${packId}" as const;
export const ${constBase}_PACK_VERSION = "1.0.0" as const;

export function build${constBase.replace(/^\w/, (c) => c.toUpperCase())}CorePack() {
  return buildCapabilityPack({
    id: ${constBase}_PACK_ID,
    label: "${label}",
    version: ${constBase}_PACK_VERSION,
    description: "SDK-scaffolded capability pack for ${label}.",
    modules: ["${slug}"],
    status: "draft",
    dependencies: [],
    tags: ["${slug}", "sdk-scaffold"],
  });
}

export function assert${constBase.replace(/^\w/, (c) => c.toUpperCase())}PackValid() {
  return validateCapabilityPack(build${constBase.replace(/^\w/, (c) => c.toUpperCase())}CorePack());
}
`;

  const readme = `# ${label} Capability Pack (\`${packId}\`)

Generated by \`jag create capability\`.

## Includes

- Manifest (id, version, modules)
- Dependency declarations (edit as needed)
- Validation via \`validateCapabilityPack()\`

## Docs template

| Field | Value |
|-------|-------|
| Pack id | \`${packId}\` |
| Version | \`1.0.0\` |
| Modules | \`${slug}\` |
| Status | draft |

Attach from an Organization Blueprint. Do not put this pack id on an Industry Blueprint.

See: docs/jag-os/sdk/
`;

  const testTs = `import { describe, expect, it } from "vitest";
import {
  assert${constBase.replace(/^\w/, (c) => c.toUpperCase())}PackValid,
  build${constBase.replace(/^\w/, (c) => c.toUpperCase())}CorePack,
} from "./${slug}.core";

describe("${packId}", () => {
  it("builds and validates", () => {
    const pack = build${constBase.replace(/^\w/, (c) => c.toUpperCase())}CorePack();
    expect(pack.id).toBe("${packId}");
    expect(assert${constBase.replace(/^\w/, (c) => c.toUpperCase())}PackValid().ok).toBe(true);
  });
});
`;

  return {
    ok: true,
    kind: "capability-pack",
    id: packId,
    files: Object.freeze([
      Object.freeze({
        path: `src/packages/${slug}/capability-packs/${slug}.core.ts`,
        contents: packTs,
      }),
      Object.freeze({
        path: `src/packages/${slug}/capability-packs/${slug}.core.test.ts`,
        contents: testTs,
      }),
      Object.freeze({
        path: `src/packages/${slug}/capability-packs/README.md`,
        contents: readme,
      }),
    ]),
    notes: Object.freeze([
      "Declare dependencies with version ranges before publishing.",
      "Keep contributions declarative — no ProcessRuntime / DecisionRuntime.",
    ]),
  };
}
