/**
 * Scaffold file templates for a new Industry Blueprint (developer productivity).
 */

import type { ScaffoldResult } from "@/jag/sdk/public-types";
import { listFoundationModules } from "@/jag/sdk/builders/modules";

function slugify(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function scaffoldIndustryBlueprint(name: string): ScaffoldResult {
  const id = slugify(name);
  const label = name.trim() || id;
  const foundation = listFoundationModules().map((m) => `"${m}"`).join(",\n  ");

  const blueprintTs = `/**
 * ${label} Industry Blueprint — generated by JAG SDK scaffold.
 * Edit catalogs and vertical modules; do not add pack ids or runtime logic.
 */

import {
  buildIndustryBlueprint,
  buildIndustryCatalogs,
  createCatalogEntry,
  validateBlueprint,
} from "@/jag/sdk";

const catalogs = buildIndustryCatalogs({
  verticalModules: [],
  identityVocabulary: [
    createCatalogEntry("member", "Member"),
  ],
  documentTypes: [
    createCatalogEntry("policy_doc", "Policy Document", { family: "policy" }),
  ],
  communicationTypes: [
    createCatalogEntry("announcement", "Announcement"),
  ],
  schedulingConventions: [
    createCatalogEntry("meeting", "Meeting", { schedulableTypeHint: "meeting" }),
  ],
  workClassifications: [
    createCatalogEntry("task", "Task", { workType: "task" }),
  ],
  decisionCategories: [
    createCatalogEntry("operational", "Operational Decision", {
      category: "operational",
    }),
  ],
  policyDefaults: [
    createCatalogEntry("code_of_conduct", "Code of Conduct", {
      family: "policy",
    }),
  ],
  reportingDefaults: [
    createCatalogEntry("activity", "Activity Report", {
      reportType: "operational",
    }),
  ],
  analyticsDefaults: [
    createCatalogEntry("utilization", "Utilization", {
      metricHint: "utilization",
    }),
  ],
});

export const ${id.replace(/-/g, "_")}IndustryBlueprint = buildIndustryBlueprint({
  id: "${id}",
  label: "${label}",
  version: "1.0.0",
  description: "Declarative ${label} industry blueprint (SDK scaffold).",
  catalogs,
  studioProfile: {
    locationKinds: ["office", "region"],
    suggestedRoles: [{ id: "admin", label: "Administrator" }],
    questionHints: {
      modules: "Enable foundation modules: ${listFoundationModules().join(", ")}",
    },
  },
});

export function assert${id.replace(/-/g, "_").replace(/^\w/, (c) => c.toUpperCase())}BlueprintValid() {
  return validateBlueprint(${id.replace(/-/g, "_")}IndustryBlueprint);
}

// Foundation modules reference (do not put pack ids here):
// ${foundation}
`;

  const readme = `# ${label} Industry Blueprint

Generated by \`jag create industry\`.

## Rules

- Declarative catalogs only
- No pack ids on the industry blueprint
- Validate with \`validateBlueprint()\` from \`@/jag/sdk\`

See: docs/jag-os/sdk/
`;

  return {
    ok: true,
    kind: "industry",
    id,
    files: Object.freeze([
      Object.freeze({
        path: `src/jag/blueprints/industries/${id}/blueprint.sdk.ts`,
        contents: blueprintTs,
      }),
      Object.freeze({
        path: `src/jag/blueprints/industries/${id}/README.md`,
        contents: readme,
      }),
    ]),
    notes: Object.freeze([
      "Review and merge into the industry catalog registry when ready.",
      "Attach packs only from an Organization Blueprint.",
    ]),
  };
}
