/**
 * Scaffold file templates for a new Organization Blueprint.
 */

import type { ScaffoldResult } from "@/jag/sdk/public-types";

function slugify(input: string): string {
  return input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

export function scaffoldOrganizationBlueprint(
  name: string,
  industryId = "education"
): ScaffoldResult {
  const slug = slugify(name);
  const label = name.trim() || slug;
  const orgConst = slug.replace(/-/g, "_");

  const orgTs = `/**
 * ${label} Organization Blueprint — generated by JAG SDK scaffold.
 * Branding, locations, overlays, and pack attachment only.
 */

import {
  buildDefaultOrganizationAnswers,
  buildOrganizationBlueprint,
  listFoundationModules,
  validateOrganization,
  type CapabilityPack,
  type IndustryBlueprint,
} from "@/jag/sdk";

export function build${orgConst.replace(/^\w/, (c) => c.toUpperCase())}Organization(input: {
  readonly industry: IndustryBlueprint;
  readonly capabilityPacks?: readonly CapabilityPack[];
}) {
  const answers = buildDefaultOrganizationAnswers({
    industryId: input.industry.id,
    organizationId: "${slug}.organization",
    packageId: "${slug}",
    applicationId: "${slug}",
    name: "${label}",
    brand: "${label}",
    enabledModules: listFoundationModules(),
  });

  return buildOrganizationBlueprint({
    industry: input.industry,
    answers,
    capabilityPacks: input.capabilityPacks,
    displayName: "${label}",
    brand: "${label}",
  });
}

export function assert${orgConst.replace(/^\w/, (c) => c.toUpperCase())}OrganizationValid(
  organization: Parameters<typeof validateOrganization>[0]
) {
  return validateOrganization(organization);
}

// Suggested industry id from scaffold: ${industryId}
`;

  const readme = `# ${label} Organization

Generated by \`jag create organization\`.

## Allowed

- branding, locations, structure, org policies, answers
- capability pack attachment

## Not allowed

- runtime logic, compiler hooks, capability definitions

See: docs/jag-os/sdk/
`;

  return {
    ok: true,
    kind: "organization",
    id: slug,
    files: Object.freeze([
      Object.freeze({
        path: `src/packages/${slug}/organization.sdk.ts`,
        contents: orgTs,
      }),
      Object.freeze({
        path: `src/packages/${slug}/README.md`,
        contents: readme,
      }),
    ]),
    notes: Object.freeze([
      "Pass an Industry Blueprint + foundation packs at build time.",
      "Do not duplicate industry catalogs in the organization package.",
    ]),
  };
}
