/**
 * Academy process definitions — declarative contributions for the Process Engine.
 */

export {
  AcademyAdmissionsProcessDefinition,
  ACADEMY_ADMISSIONS_PROCESS_ID,
  ACADEMY_ADMISSIONS_STAGES,
  ACADEMY_ADMISSIONS_TRANSITIONS,
  ACADEMY_ADMISSIONS_FORM_DEFINITION_IDS,
  ACADEMY_ADMISSIONS_DOCUMENT_DEFINITIONS,
  ACADEMY_ADMISSIONS_DOCUMENT_DEFINITION_IDS,
  ACADEMY_ADMISSIONS_DOCUMENT_CATEGORY,
  ACADEMY_ADMISSIONS_DOCUMENT_CATEGORY_ID,
  ACADEMY_ADMISSIONS_COMMUNICATION_DEFINITIONS,
  ACADEMY_ADMISSIONS_COMMUNICATION_TEMPLATES,
  ACADEMY_ADMISSIONS_COMMUNICATION_DEFINITION_IDS,
  ACADEMY_ADMISSIONS_COMMUNICATION_TEMPLATE_ID_LIST,
  ACADEMY_ADMISSIONS_DECISION_DEFINITIONS,
  ACADEMY_ADMISSIONS_DECISION_DEFINITION_IDS,
  ACADEMY_ADMISSIONS_ELIGIBILITY_DECISION,
} from "@/packages/academy/processes/admissions";

import { AcademyAdmissionsProcessDefinition } from "@/packages/academy/processes/admissions/manifest";

export const ACADEMY_PROCESS_DEFINITIONS = Object.freeze([
  AcademyAdmissionsProcessDefinition,
]);
